### ISSUE TITLE
Added monad comprehensions to Coffeescript

### ISSUE THREAD

**Issue by zot** [jashkenas/coffeescript#1032]
I modded the Coffeescript compiler to add monad comprehensions, forked the repo, and pushed my changes to the "mocoffee" branch, here: https://github.com/zot/coffee-script

An example file is here: https://github.com/zot/coffee-script/blob/mocoffee/examples/mofor.coffee

Monad comprehensions are syntactic sugar that helps to reduce the indentation level of your code, if you use monads.  Here are some articles on monads:

http://www.haskell.org/tutorial/monads.html
http://en.wikipedia.org/wiki/Monads_in_functional_programming

They're really useful in functional programming.  In fact, I'm starting a functional programming project that uses Javascript and that's why I'm looking at Coffeescript.  Please let me know what you think of the syntax; I chose "mofor" because it's a monadic for-loop-ish construct.  It looks like this:

```
mofor
  variable1 <- expr1
  ...
  if expr2
  ...
  variable2 <- expr3
  ...
->
  expr4
  ...
```

If used as an expression, it returns the flattened result.  `var <- expr` is a "binding" expression and it binds var to the values in expr.  You can mix filter expressions in with the bindings.  At this point, expr can be an array or anything that understands `map()`, `filter()`, `forEach()`, and `flatMap()` (as in Scala).  The code it generates is a little klugy at this point, and it relies on the existence of `Array.prototype.flatMap()`, if you're using arrays, which I'm just including in my code right now, but I'll improve these things over time.

Mofor translates to a nested group of `map()`, `flatMap()`, `forEach()`, and `filter()` expressions, each binding or filter line increasing the nesting level.  Monad comprehensions help simplify the text.

Here are the examples from the mofor.coffee file:

```
sys.p (mofor
  a <- [1,2,3]
  b <- [4,5,6]
  if a % 2 == 0 or b % 2 == 0
->
  [a + 1, b + 1])
```

outputs:

```
[ [ 2, 5 ]
, [ 2, 7 ]
, [ 3, 5 ]
, [ 3, 6 ]
, [ 3, 7 ]
, [ 4, 5 ]
, [ 4, 7 ]
]
```

and:

```
sys.p (mofor
  a <- new Monad(3)
->
  a
)
```

outputs (I don't have a fancy print-string for monads, yet :) ):

```
{ '0': 3 }
```

**Comment by Leimy** [comment]
It's wrong to say that monads are only useful in functional languages where there's no side-effects.

Just because technique X was applied to a language to solve problems with representing flow, doesn't mean the only use of technique X is in those cases :-).

/bin/sh -e  runs under an error monad (whether you like to believe it or not) for example, which says any failing step that is unchecked in the script causes the whole script to abort.  You could think of it as converting your errors into exceptions that must be caught or they'll terminate the script.

I'm really new to coffeescript but sometimes these abstractions are nice to have.  The problem is they often come with syntactical convenience for the author of code, which makes reading the code, by humans, much more difficult later.

Haskell is full of nice stuff like this, but it makes reading take way more effort than writing the code.
