### ISSUE TITLE
Braceless object `return`

### ISSUE THREAD

**Issue by zdzolton** [jashkenas/coffeescript#1263]
I'd like to be able to return an object literal from a function without typing any braces:

```
makeAwesome = (what, ever) ->
  stuff = doStuff what, ever
  return
    foo: what
    bar: doMore stuff
    baz: stuff
```

Right now, you have to do this:

```
makeAwesome = (what, ever) ->
  stuff = doStuff what, ever
  return {
    foo: what
    bar: doMore stuff
    baz: stuff
  }
```

Not terrible, but come on... We don't wanna type no stinking braces! LOL

Actually, this is legal but I think it looks confusing:

```
makeAwesome = (what, ever) ->
  stuff = doStuff what, ever
  foo: what
  bar: doMore stuff
  baz: stuff
```

**Comment by GeoffreyBooth** [comment]
Closing this issue as it doesn’t appear to be affecting enough people to warrant attention. If someone wants to implement support for this, a pull request is welcome.

**Comment by GeoffreyBooth** [comment]
I’ve noticed that this bug is the root of several similar issues. I’m trying to trace it down but not having much luck so far. Parsing/lexing experts, can anyone tell me why this:

```coffee
throw
  a: 1
  b: 2
```

[compiles as you’d expect](http://localhost/v2/#try:throw%0A%20%20a%3A%201%0A%20%20b%3A%202), but if you replace `throw` with `return` or `export default`, the latter two throw [`error: unexpected indentation`](http://localhost/v2/#try:export%20default%0A%20%20a%3A%201%0A%20%20b%3A%202)?
