### ISSUE TITLE
Adding plugins to coffeescript (i.e. preprocessor for logging)

### ISSUE THREAD

**Issue by tauren** [jashkenas/coffeescript#1466]
I would like to see coffeescript have a plugin system that would allow users to develop enhancements that can be inserted into the coffeescript compile process.  

For instance, I scatter `console.log` output throughout my application, but there are times that I want to have loglevel features, such as console.debug or console.trace. To make this work cross-browser, I create my own logging functions.  The problem is that console output shows the file name and line number of where console.log was called, not where my wrapper function is called. This makes it more time consuming to debug in a browser.

Furthermore, I want all of my logging code to be removed when in production mode. It seems to me that coffeescript would be an ideal place to handle custom logging features, and it could easily choose to include or exclude logging code in production mode. I would love to see coffeescript enhanced to allow users to build preprocessors that would be run on the code before the compiler is run. 

Imagine a preprocessor that defines some custom functions. These functions would inline code in the output based on some condition. For instance, my preprocessor defines a `logger` object and adds some methods to it. This could be used with coffeescript like this:

```
logger.loglevel 'debug'
logger.info 'Info'
logger.debug 'Debug'
logger.trace 'Trace'
```

This would generate:

```
console.log('Info');
console.log('Debug');
```

Note that 'Trace' isn't output because the loglevel excludes it. The values of `logger.loglevel` could be kept simple, or could allow lots of levels: `none`, `fatal`, `error`, `warn`, `info`, `debug`, and `trace`.

The output would be dynamically included depending upon the function called and the current log level. It would be great if the command line compiler could somehow take parameters for preprocessors so that something like `--loglevel none` could be specified when generating production code.

It would be extremely nice if each file could have it's own loglevel scope. That way if I wanted to only see trace level logging in a certain module of my application, I wouldn't have to see the trace output from everything else.

Anyway, does this seem like a useful idea? Since coffeescript is already compiling code, why not plug into it for features like this? Could this be added without changing coffeescript core, or would it need to go into coffeescript core?

**Comment by HeroicAutodidact** [comment]
I know that the original problem this thread set out to solve has been resolved, but I'm looking for information about customizing the coffee compiler. 

Say, for example, that I wanted to augment the functionality of a all arrays and objects with underscore functions, allowing me to do something like `testArray.first()` and have it compile to `_.first(testArray)`

This is something which would be very dangerous to do in plain javascript, as I would have to extend the Array.prototype and might break functionality of the array in other libraries. It seems like it would be safe and fun to do with coffee-script, though!

It would be great if there was a way to do this in a way which is:

1. Modular - I could add multiple pre-processing steps, pulling from different sources which make programming more easy and elegant in different ways. 
2. Integrated - I want to be able to change something in the configuration files of coffeescript so that I don't have to use a custom binary and replace the command in every single development tool which is calling the coffee compiler (for live compilation, etc).

Does this exist built into coffeescript now? If not, it seems like it should. I realize this opens up a can of worms and would probably lead to some horrible misuse. But, hey, with great power comes great responsibility!

**Comment by akre54** [comment]
@HeroicAutodidact leaving aside whether that's a good idea, I don't see a way of doing that without runtime checks. Check out #3171 for a stab at hygenic macros, which may be what you're looking for.

**Comment by carlsmith** [comment]
The desire to avoid runtime checks seems to have caused an unhelpful aversion to runtime in general. It doesn't really matter how much we sugar a user's invocations. It's not a runtime check to compile `2px` to `px(2)` or `with _ then @first array` to `_.first(array)`.

Invocation sugar seems to get conflated with runtime checking.

**Comment by akre54** [comment]
But think of how much slower your app would be if you had to wrap every member access call to `.first()` to see if the variable is an array. It's also surprising behavior that some method invocations would act differently depending on what method was called. This is a poor idea.

**Comment by carlsmith** [comment]
Agreed. I wouldn't want this feature as suggested either.

I was just saying that having more sugar for expressing invocations (the two I mentioned are just for example) is totally different to wrapping stuff in checks.

It just seems like we could allow for a lot more of what people wanted to do if there were more ways to write an expression that invokes a user defined function on the expression's operands. Instead of exploring how to do that best, we tend to dismiss it for sounding like it introduces runtime checks.

You are totally correct though @akre54: We can't fix methods without expensive checks all over the place.

**Comment by GeoffreyBooth** [comment]
Closing this issue as it appears that a `--logLevel` flag or something like it isn’t currently in the plans. However there definitely is need for making the compiler extensible, so if someone wants to propose a feasible way for implementing a plugin architecture that would be greatly appreciated. Please make such suggestions as new issues.
