### ISSUE TITLE
Named function declaration syntax

### ISSUE THREAD

**Issue by mourner** [jashkenas/coffeescript#1640]
I know that this issue is mentioned in the FAQ and there's a reason not to use named functions because of IE bugs, but as I understood it only applies when you use **both** a named function and a function expression at the same time, e.g. `f = function g() { ... }`, and if you just need to do `function g() { ... }`, there's no problem with this.

So, considering this, is there any way you could enable some named functions syntax in CoffeeScript in the future? I figured out that I need this because it turns out that Closure Compiler inlines named functions quite aggressively, while it never inlines function expressions assigned to a variable, so the CoffeeScript equivalent in my case produces a 20% bigger compressed output. Inlining also provides performance benefits.

**Comment by aleclarson** [comment]
I really like @jiangmiao's solution. 

My only need is being able to use `MyConstructor.name` when `MyConstructor` is declared as a function rather than with the `class` keyword. But this is a rare case.

This is my solution:
```Coffeescript
MyConstructor = `function MyConstructor () { 
  return MyConstructor.init.apply(null, arguments) 
}`
MyConstructor.init = (someValues...) ->
  # Do your thing
alert MyConstructor.name
```

[Here's a JSFiddle testing the above code.](http://jsfiddle.net/aleclarsoniv/0drcx390/)

P.S. I'm a new user of Coffeescript and I fucking love it. Thanks for everything. :smile:
