### ISSUE TITLE
Invalid unicode identifiers

### ISSUE THREAD

**Issue by satyr** [jashkenas/coffeescript#1718]
```
$ coffee -bpe '♪ = 1'
var ♪;
♪ = 1;

$ coffee -e '♪ = 1'

.:2
  var ♪;
       ^
SyntaxError: Unexpected token ILLEGAL
```

**Comment by GeoffreyBooth** [comment]
The consensus above seems to be that this isn’t worth the performance hit to the compiler for the compiler to catch such errors, especially since the runtime will do so. If someone wants to submit a pull request that achieves such validation in a performant way, it will be welcomed; but in the meantime I think we’re choosing to take no action here.
