### ISSUE TITLE
process.argv behaves differently to nodejs

### ISSUE THREAD

**Issue by chrislloyd** [jashkenas/coffeescript#1752]
In a file (both valid coffee script and vanilla JS):

```
console.log(process.argv)
```

then call with:

```
$ node argv.js -myargs
[ 'node', '/Users/Chris/Desktop/argv.js', '-myargs' ]
```

and

```
$ coffee argv.js -myargs
[ 'coffee',
  '/Users/Chris/Desktop/argv.js',
  '-m',
  '-y',
  '-a',
  '-r',
  '-g',
  '-s' ]
```

CoffeScript still interprets flags after the script name.

**Comment by amagura** [comment]
@slezica even if you are familiar with the `--` convention, what if your program uses a parser that makes use of `--`?  `--` should not have to passed just to have portable argument parsing between javascript and coffescript, when you're not compiling your coffeescript, and `process.argv` shouldn't be modified when your compiling since that will confuse and irritate people (especially people that write option parsers in coffeescript to be used in both javascript and coffeescript).

**Comment by cosmicexplorer** [comment]
Unless I'm very much mistaken, not all versions of env work the same, or I'm calling it incorrectly. Prefacing a coffeescript file with `#!/usr/bin/env coffee --` does not work, and this issue makes developing an npm module much more frustrating. The input:

```
#!/usr/bin/env coffee --

**Comment by cosmicexplorer** [comment]
Unless I'm very much mistaken, not all versions of env work the same, or I'm calling it incorrectly. Prefacing a coffeescript file with `#!/usr/bin/env coffee --` does not work, and this issue makes developing an npm module much more frustrating. The input:
```coffeescript
#!/usr/bin/env coffee --

console.log process.argv
```
fails when run with the error `/usr/bin/env: coffee --: No such file or directory`. If the `--` is removed, of course, then `process.argv` "unpacks" packed arguments, turning `-ABCD` into `-A -B -C -D`, which screws over the argument processing for the application I'm trying to write (I'm working around it, but it's frustrating). This doesn't need to be a problem; the command processor just needs to not modify the version of process.argv it passes into the forkNode function. I'll make a pull request if it has any chance of getting approved, it'll take five minutes.

**Comment by cosmicexplorer** [comment]
So I did some reading and found [this thread](http://stackoverflow.com/questions/4303128/how-to-use-multiple-arguments-with-a-shebang-i-e) which states that some operating systems parse the `env` line differently. I tested on a mac and found that `#!/usr/bin/env coffee --` does work there, as it is parsed by the operating system as a call to `/usr/bin/env coffee --` ("coffee" and "--" are parsed as separate arguments). However, on every Linux device I've tested it on, it fails, parsing the shebang line as a call to `/usr/bin/env "coffee --"`; obviously, there is no executable on my path named "coffee --", so the call to /usr/bin/env fails.

The best way to deal with this that I can think of is (if there is no `--` argument given) to just check if the first argument to the interpreter is a coffeescript file, and then leaving all options to the right of that alone and passing them directly to the node process. Again, I'd do it, but this also might break some existing scripts that rely on being able to put arguments to coffeescript after the input script name (although running `coffee -h` shows that the correct way to run it is to provide all arguments to the coffeescript compiler _before_ the input script argument, but obviously the `--` argument was introduced so that behavior was not strictly enforced), which is not fun. The probability of that is likely much less than the probability of someone trying to run a coffeescript file using a shebang line on a Linux system, though, so I think it's an appropriate tradeoff.

**Comment by GeoffreyBooth** [comment]
As [commented above](https://github.com/jashkenas/coffeescript/issues/1752#issuecomment-42940164), this is documented in `coffee --help`, and behaving as designed. The `coffee` binary is intended primarily for compiling and debugging, not as a replacement for `node`.
