### ISSUE TITLE
x = y /* z */

### ISSUE THREAD

**Issue by TrevorBurnham** [jashkenas/coffeescript#1772]
Someone on Stack Overflow recently posted [a question on comments](http://stackoverflow.com/questions/7781685/coffeescript-how-to-comment), where they said that

```
/* comment goes here */
```

seems to work when it's not on its own line. An example would be

```
x = y /* z */
```

which compiles to

```
x = y(/* z */);
```

Of course, a JS interpreter will just see that as `x = y();`. A more harmful example is

```
x = /* z */
```

which straightforwardly to

```
x = /* z */;
```

but will obviously cause a runtime error.

The sensible solution is to add a compile-time error for such block comments or, ideally, for all invalid regexes. Note that `new RegExp('* z *')` gives you the helpful feedback `SyntaxError: Invalid regular expression: /* z */: Nothing to repeat`.

**Comment by lydell** [comment]
I just read through #1776, but I don’t understand why that made this issue be reopened.

**Comment by michaelficarra** [comment]
#1776 rejected validating RegExps using the JS engine's RegExp engine. So we need to validate RegExps some other way. Note that CoffeeScript is treating `/* comment */` as a RegExp, even though a RegExp must not start with `*`. I don't see any feasible way to do this other than using the built-in RegExp engine. In other words, it was a mistake to reject #1776, but I was out-voted.

**Comment by lydell** [comment]
> Note that CoffeeScript is treating /* comment */ as a RegExp, even though a RegExp must not start with *

Nope, CoffeeScript throws an error if regexes start with `*`. There are even tests for this.

**Comment by michaelficarra** [comment]
Was. Until the above commit. But that is a hack. There are still many more invalid RegExps allowed.

**Comment by lydell** [comment]
_Is_: https://github.com/jashkenas/coffeescript/blob/9fa77af57698a99d43d401940a4444eaabd77384/src/lexer.coffee#L257-258

Yes it is a hack, but an important one. Other invalid regexes throw errors when the JS is executes, while a regex starting with a `*` might fail silently (bwing interpreted as a comment).

**Comment by michaelficarra** [comment]
> Other invalid regexes throw errors when the JS is executed

Yes, but shouldn't they be detected statically?

**Aside:** I don't understand JavaScripters' distaste for correctness. Underscore papers over passed-in `null` values. Just yesterday I read that `querySelectorAll` failing on invalid queries is *considered a misfeature* by many. They would prefer it return an empty result set with no indication that the query was invalid. Is this really how people want to program?

**Comment by lydell** [comment]
I'm also for correctness. I just wanted to point out why "starting with *" is checked for out of all possible regex errors.

Back on topic, this issue seems to be specifically about the above case, which has been fixed.

Moreover, it seems like the discussion about invalid regexes (as well as invalid identifiers) has already been made. People disagree, but a decision had to be made, which happens to be the "loose" alternative. Other implementations, auch as redux, of course may do it other ways.

**Comment by michaelficarra** [comment]
As I understand it, the decision was made to not implement this validation through the RegExp engine of the interpreter of the compiler because it may differ from the interpreter used on the generated code (say, if experimental or nonstandard flags are supported by the target engine). But that is not a decision to never statically validate RegExps. I re-opened this issue to either implement that feature or explicitly turn it down.

**Comment by jashkenas** [comment]
It's a tradeoff like any other. It would be great to statically validate regexes in advance if such validation can be done easily, without adding a lot of complexity to the codebase. Otherwise, allowing them to be validated at runtime is fine.

**Comment by GeoffreyBooth** [comment]
The issue at the top of this thread is resolved:

```sh
coffee -bpe 'x = y /* z */'
[stdin]:1:8: error: regular expressions cannot begin with *
x = y /* z */
       ^
```

In the interest of clarity, @michaelficarra if you’re still interested in proposing that the lexer catch all invalid regexes before passing off to the runtime to do so, I suggest you open a new issue specifically for that.
