### ISSUE TITLE
Assigning to the result of a call:   Foo(2) = Bar

### ISSUE THREAD

**Issue by mehrdadn** [jashkenas/coffeescript#2024]
This is used in JScript when setting environmental variables:

var WshProcEnv = WScript.CreateObject("WScript.Shell").Environment("Process");
WshProcEnv(k) = 'myvalue';

There is no other way (that I know of) for changing environmental variables in JScript, so if CoffeeScript could support this, I could avoid having to escaped JScript in the middle of my code. :)

**Comment by GeoffreyBooth** [comment]
Closing as this doesn’t appear to affect many people, though a patch would be welcome. In the meantime backticks can be used as a workaround.

```coffee
`WshProcEnv(k) = 'myvalue'`
```

**Comment by carlsmith** [comment]
I'm surprised JavaScript even allows a function to return an actual reference, rather than the value it references. Did the spec authors intend this, or is it just implied by areas of the spec intended to solve a different problem?

If any feature depends on exploiting loopholes, it's a Bad Part. If an API requires the feature, it should be accessed with backticks, then wrapped with a function - my two pennies.
