### ISSUE TITLE
Class name mangled after minification

### ISSUE THREAD

**Issue by wuyuntao** [jashkenas/coffeescript#2052]
JavaScript minification tools rename local functions for performance, and this mangles CoffeeScript class names too.

Since Function.name is a read-only property, forcing class names which implemented in #494 does not work.

How about setting class name to some other property, like `Foo.__name__` or `Foo.className`?

A brief example

``` coffeescript
class Foo
  constructor: ->
    console.log(this.constructor.name)

foo = new Foo()
```

Compiles into

``` javascript
(function() {
  var Foo, foo;
  Foo = (function() {
    Foo.name = 'Foo';
    function Foo() {
      console.log(this.constructor.name);
    }
    return Foo;
  })();
  foo = new Foo();
}).call(this);
// Outputs 'Foo'
```

Minified

``` javascript
(function(){
  var a,b;
  a=(function(){
    a.name='Foo';
    function a(){
      console.log(this.constructor.name);
    }
    return a;
  })();
  b=new a();
}).call(this);
// Outputs 'a'
```

**Comment by CyborgMaster** [comment]
Sorry to bump such an old thread, but I had a few questions.  I am working on a project where we need to get a hold of the class name.  We are building some features into our models for auto-configuration (convention over configuration), where the names of id properties, json urls, etc. are intuited from the model class name (similar to what Rails does).  

What is the current official recommendation from coffeescript on how to do this?  I loved the name property that was added to constructors, but based on this thread, that seems to have been removed.  I also loved the idea of `__name__` to handle minification and browser support issues, but that also seems to have been rejected.  

Is the current recommendation to simply add another property on the class manually? Something like this?
``` coffeescript
class Foo
  @name: 'Foo'
```
That works, but it certainly isn't very DRY.  

If the manual class property is all we've got then I will use it of course, but I just wanted to check what the official recommendation was.  

Sorry if this was the wrong place to ask.  I thought about opening a new issue, because this one is so old, but it seemed like the correct thread.  If there is a better place to ask let me know and I can repost and do better in the future. 

Thanks!

**Comment by epidemian** [comment]
@CyborgMaster you can assign the class to some object's property:

```coffeescript
class Models.Cat
  talk: -> 'meow'

# Or...
Models.Cat = class 
  talk: -> 'meow'

# Or...
@Cat = class
  talk: -> 'meow'
```

That way, you can trust that the name will be preserved upon minification because you've assigned it to a named property on an object, and not just a local variable.

Don't take this for an "official recommendation" though. It's just what i would do to keep a mapping between classes and some names. I hope it helps!

**Comment by davidbonnet** [comment]
If someone else is stumbling on this, here are three solutions:

1. Don't rely on `Function::name` at all, or...

2. Use `uglify` with the `--keep-fnames` flag to leave function names untouched, and...

3. Add support of the `Function::name` property in IE, with the following [snippet](http://stackoverflow.com/a/17056530/492661):

```coffeescript
unless Function::name?
	Object.defineProperty Function::, 'name',
		configurable: yes
		get: ->
			name = ( @toString().match /^\s*function\s*(\S*)\s*\(/ )[1]
			Object.defineProperty @, 'name', value: name
			return name
```
