### ISSUE TITLE
Add option to write shebang line (helpful for developing Npm packages that install executables)

### ISSUE THREAD

**Issue by hickford** [jashkenas/coffeescript#2215]
Hi. I develop a desktop application in Coffeescript. I love Coffeescript. As it happens, I don't actually know Javascript. Still, my app is  distributed as an Npm Javascript package (the only kind), so as to be useful to everyone. The package installs some executables into the path, per https://npmjs.org/doc/json.html#bin .

My `npm prepublish` step compiles my app with the short command `coffee -o lib -c src`. 

The problem is the compiled Javascripts lack shebangs. This makes them broken (when installed to the path) to Unix and Windows MSys users. Anyone trying to run one of the executables from the shell sees an error like

```
./a.js: line 1: syntax error near unexpected token `('
./a.js: line 1: `(function() {'
```

To fix this, I replaced my simple build command with a Cakefile that does the build then adds shebangs manually. This sounds easy enough, but for a folder of scripts, it's several lines to do in a reliable cross-platform fashion.

Thus, it would be helpful to add a `--shebang` switch to the compiler. So building a Coffeescript app with executables would be as simple as `coffee -o lib -c src --shebang`.

**Comment by adius** [comment]
`cat` isn't cross platform compatible. I think a shebang flag sounds like a reasonable solution

**Comment by acidjazz** [comment]
why isn't this built into coffeescript? this makes adding stuff like #!/usr/bin/env node at the top of our .js files impossible

**Comment by lzrski** [comment]
Easy solution is to use backticks, like @erisdev suggested. The trick part is to add a newline before the closing tick, like this:

```coffee
`#!/usr/bin/env node
`
console.log 'hello, terminal'
```

The compiler will add semicolon after the backtic block, and shell won't stand it on the same line as shebang. With newline, the semicolon will be on the second line of the compiled script, which is ok:

```javascript
#!/usr/bin/env node
;
```

Also one needs to use `--no-header` and `--bare` options, otherwise the shebang won't be on the first line.

**Comment by hickford** [comment]
> If I use that backticks bodge, my original coffeescript won't execute :(

**Comment by foxx** [comment]
@jashkenas This is a pretty stupid bug / missing feature tbh.

**Comment by cosmicexplorer** [comment]
`#!` lines aren't cross-platform compatible, and every platform that supports those definitely has `cat` installed. If you're compiling these on windows to use on not-windows, you can use the `type` command to do the same thing. You can have multiple commands in an `npm prepublish` script, so unless I'm mistaken, you should be able to generate files with `#!` lines in all cases unless your build system is the problem.

To make an executable named `executable` from `executable.coffee`:

On not-windows:
``` bash
# generate executable.js
coffee -bc --no-header executable.coffee
echo '#!/usr/bin/env node' | cat - executable.js > executable
chmod +x executable
```

On windows:
``` cmd
# generate executable.js
coffee -bc --no-header executable.coffee
echo #!/usr/bin/env node > executable
type executable.js >>executable
```

Alternatively, you could write an executable script in coffeescript or any other language to do this and call that from your `npm prepublish` script.

**Comment by TheBrenny** [comment]
Old thread and pretty dead, but...

Why not detect shebangs on compilation of a file and keep it when piping it to the generated file? Doesn't need a flag imo, because if you're writing a shebang, you obviously want to keep it?

While the `--bare --no-header` and splitting the backtick across multiple lines does "work" (as a slightly ridiculous workaround), I think having native support for shebang is a should-have feature.

My response to:
> `#!` lines aren't cross-platform compatible...
is that NPM uses them when you want to have [runnable bin files](https://stackoverflow.com/questions/28726970/why-does-running-my-globally-npm-linked-package-simply-open-the-bin-file) (yeah, it's a bit weird). Being platform-agnostic, I think NPM just sees the shebang and creates a different `.cmd` file.

I'm brand new to this whole coffeescript thing (literally 5min old with it) so I feel like my ability to hack the compiler is definitely non-existant. I'll do more research, but hopefully a PR with an endstate of `see shebang > copy/paste shebang` isn't too far in the future...

**Comment by johndeighan** [comment]
Any solution which directly modifies the JavaScript file produced by CoffeeScript is doomed to failure. You should NEVER modify the JS file since it will be rebuilt on the next build. I know, ... I've been bit by this bug. I agree that "if there's a shebang line present, the user will always want to preserve it". Not sure why this bug hasn't been fixed yet.

**Comment by cosmicexplorer** [comment]
I thought there was a relatively good response in 2013? Is that solution not workable? https://github.com/jashkenas/coffeescript/pull/2391#issuecomment-14425405

> Closing. My favorite way to do this in any case is just to write a tiny executable .js wrapper file that calls out to your actual program. That's how coffee and cake are implemented, for example. It's too special-case to bother adding a flag to the compiler for.
