### ISSUE TITLE
Remove implicit returns?

### ISSUE THREAD

**Issue by devongovett** [jashkenas/coffeescript#2477]
After writing CoffeeScript for quite a long a while, I've come to the realization that implicit returns are actually more annoying than useful.  Oftentimes I'll have to go back to a function later and add an explicit `return` statement to prevent CoffeeScript from adding implicit returns.  They are the source of many bugs, and reduce the readability and predictability of CoffeeScript code.
1. Having to go back an add explicit returns happens especially often when a loop is the last thing in the function, where very rarely do I want the function to return an array (if I did, I could easily add an explicit `return`).  Generating and returning that array when I very rarely want it can also have a potentially large performance impact on the function as well, so I always have to remember to add a `return` statement at the end of many of my functions to prevent this.  Just looking at a function with a loop at the end doesn't tell me that it returns an array so when it turns out it does it can be kinda strange.  Usually you end up finding out when you discover another bug related to it or you look at the compiled JavaScript.
2. It can also be inconsistent when combined with conditional logic.  For example:

``` coffeescript
test = ->
        if someCondition
            doSomething()
```

This function returns the result of `doSomething()` only if `someCondition` is truth-y, otherwise it returns `undefined`.  The question is why I would ever want a return value sometimes and not others.  Without an explicit return statement, this seems strange.  It isn't clear that this function returns anything just from looking at it.
1. It can be annoying for functions that do something based on another function's return value.  An example of such a function is jQuery's `each` function, which uses the `false` sentinel return value as a way to break out of the loop.  Using the function in CoffeeScript when the last operation in that function sets a variable to `false` can be a source of bugs since CoffeeScript implicitly returns `false` and this stops the loop.  For example:

``` coffeescript
arr = ['a', 'b', 'c']
map = {}
$.each arr, ->
        map[this] = false
```

Just reading this example doesn't make it clear that the loop will only run once rather than the expected three times.   The variable `map` would equal `{ a: false }` after running this loop.  I would have expected to have gotten `{ a: false, b: false, c: false }`.  Adding an explicit `return` as the last line of the each function fixes the problem, but you wouldn't know to do that without reading the compiled JavaScript.

I could probably come up with many more examples to show that implicit returns are usually not a good idea.  I think CoffeeScript should actually remove implicit returns from the language.  Typing out `return` really isn't so hard and will lead to more readable and predictable code and keep the language closer to the semantics of JavaScript (a good thing when working with libraries written in JavaScript like jQuery from CoffeeScript code).  It would probably be less typing in the end since you will no longer have to add return statements to prevent CoffeeScript from implicitly returning the wrong thing.  I know this would be a large change but I think it would be for the better since it is more of a cause of bugs than a helpful language feature.

Removing features from a language is hard, but sometimes the best thing to do.  What do you think?

**Comment by macgyver** [comment]
> the exception to the rule is when your function ends with a loop, and you're returning a comprehension unnecessarily

I realize this conversation is pretty old but I didn't get to enjoy reading all these thoughts until just this morning.  So that we can all benefit from your knowledge, can somebody quickly describe the problem with returning the result of a comprehension? Is the problem just that it takes a bit of memory space to store the resulting array, then it's discarded immediately?

**Comment by vendethiel** [comment]
Yes.

**Comment by macgyver** [comment]
In that case I can see why nobody's commented on this thread in years - why would you do a comprehension in the first place if you didn't intend to use the result.

**Comment by vendethiel** [comment]
I mean "loop" by "comprehension".

**Comment by macgyver** [comment]
Ah.. I see now - thank you!

**Comment by odraencoded** [comment]
@michaelficarra @jashkenas can I have a link to a project that makes use of that style of programming? It sounds interesting.

CoffeeScript isn't a mere expression-based language. It's also far more convenient and easier to write than Javascript, which is why it's frequently used as a replacement for Javascript.

Given that many of its user are indeed looking for CoffeeScript's convenience in a "side-effect-ful" environment, then there should be an option to disable implicit returns.

I'm not sure on the details but CS must have some sort of compiler options, right? Disabling implicit returns shouldn't be hard to maintain. And any effort spent on it should be much smaller than the effort spent arguing about it and addressing the same issue over and over.

I'm waiting for the links on the projects.

**Comment by macgyver** [comment]
I don't think it's a logically sound argument to say that a thing should be done because discussing it costs more than implementing it.

**Comment by michaelficarra** [comment]
@odraencoded what programming style?

**Comment by git2samus** [comment]
I don't think this is a matter of programming style.

coffeescript isn't a language on its own, it's a facade for javascript and this feature causes it to generate inefficient and sometimes nonsensical code which doesn't seem obvious by looking at the source; THAT'S why it doesn't create problems on languages that support it natively but it does here.

so how about a pragma? something like `'use explicit'` to mimic the `'use strict'` which people is familiar with, that would be opt-in thus keeping compatibity and could help with performance critic scenarios and also those who break with third-party libs.

**Comment by krisnye** [comment]
Reading this entire thread, a few things become obvious.

First, there is no way that the default behavior of Coffeescript is going to be changed. Ever.

Second, the maintainers, knowing this, have worked backwards from that and convinced themselves that there isn't even a problem.

Coffeescript is used for client side code.  Event handlers are always procedural, in HTML. Whatever the functional goals of Coffeescript, HTML is the reality of where it lives. 

I agree that it shouldn't be changed but you are fooling yourself if think it was a good design decision in retrospect.

I have written a reactive language with syntax inspired by Coffeescript and this is what I did:

Single line lambda expressions have an implicit return. 

    double = (x) -> x * 2

Multiline functions require an explicit return.

This works very well in practice.

**Comment by krisnye** [comment]
This also solves the related oddity of constructors behaving differently than other functions by not having an implicit return.

**Comment by AustinBryan** [comment]
This looks almost exactly like the C# one `=>` and we can use it for one-line method bodies as well, and I've never had any of those problems, because it doesn't make those wild assumptions. So, if anything, it should just remove it from those instances. 

But at this point, removing it would probably break more code and cause more bugs than implicit returns in those situations ever did.

**Comment by Inve1951** [comment]
@AustinBryan `=>` already has meaning in coffeescript.
implicit returns have no performance implications as every function alway returns a value, `undifined` if you don't override it. the only times you _have_ to put an empty return is when the function is required to return `undefined` or to prevent _returning_ a loop.

**Comment by krisnye** [comment]
@carlsmith My language did not evaluate all blocks as expressions. Instead, it allowed control flow statements (if/else/for) inside of nested object literals.

    let object = {}
        x: 10
        y: 20
        if foo
            z: 30

**Comment by carlsmith** [comment]
Ok, cool. That's quite different to CoffeeScript syntax.

> I agree that [CoffeeScript's grammar for the arrow operators] shouldn't be changed but you are fooling yourself if think it was a good design decision in retrospect.

I like restricting the arrow operator to Pythonic lambdas, generally, but for CoffeeScript (where blocks are expressions, and can be significantly indented as subexpressions), there's a consistency-based argument for the current approach.
