### ISSUE TITLE
`in` keyword compiles to unnecessarily awkward js...

### ISSUE THREAD

**Issue by torvalamo** [jashkenas/coffeescript#2562]
Unless I'm missing something,

```
if a in array
unless a in array
```

should simply compile to

```
if (~array.indexOf(a))
if (!~array.indexOf(a))
```

rather than the incredibly contrived

```
var __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

if (__indexOf.call(array, a) >= 0)
if (__indexOf.call(array, a) < 0)
```

What ancient browser are you trying to support that doesn't have indexOf on arrays? At the very least learn what the tilde operator does ;)

**Comment by GeoffreyBooth** [comment]
Is `>= 0` more readable than `!== -1`? My habit has been to always write `!== -1`, thinking that it must be faster for the runtime to evaluate a boolean than >=, but apparently [Chrome, at least, is smart enough to treat them identically](https://jsperf.com/indexof-fastest-comparison/1). So I guess it comes down to readability; I guess people find it more readable to check for a positive condition (`>=`) rather than the absence of a negative one (`!==`)?
