### ISSUE TITLE
Support for indexes in range loops

### ISSUE THREAD

**Issue by vasa-chi** [jashkenas/coffeescript#2586]
Right now this code doesn't compile:

```
for number, index in [start..end] # => indexes do not apply to range loops
  # do something with number and index 
```

Maybe it should compile to something like that:

```
//for loop boilerplate from standard compiler output, just added `index`
for (number = _i = start, index = 0; start <= end ? _i <= end : _i >= end; number = start <= end ? ++_i : --_i, index++)  {
  // ...
}
```

A small issue, but it does seem kinda wrong to have indexes in loops over arrays and not have them in loops over ranges.

**Comment by joehannes** [comment]
hi guys, this issue seems to have come up again as regression in coffeescript@next

Ubuntu 17.04
Node 8.1.2
npm 5.0.3
coffeescript 2.0.0-beta2
gulp-coffeescript 0.0.10 (coffeescript 2.0.0-alpha1)

oh, I've just seen it works on the `try coffeescript` page of the official website,
so it probably was an alpha1 issue and is removed/fixed already

I'll report to gulp-coffeescript
