### ISSUE TITLE
sugar for counting arrays/objects?

### ISSUE THREAD

**Issue by pocesar** [jashkenas/coffeescript#2950]
right now, you can call both arrays and objects in an "if" doing

``` coffeescript
if not (k for own k of $scope.corporate).length
```

that compiles to 

``` js
 if (!((function() {
            var _ref, _results;

            _ref = $scope.corporate;
            _results = [];
            for (k in _ref) {
              if (!__hasProp.call(_ref, k)) continue;
              _results.push(k);
            }
            return _results;
          })()).length) {
```

it would be nice to have a sugar syntax to count objects / arrays without having to do a for loop there. detect if it's an array or an object, and either return the length or count the props, maybe a way to hint coffeescript to turn ? into that call, like __countProperties or something to the UTILITIES

**Comment by RNCTX** [comment]
On an atom plugin with hundreds of thousands of downloads/users, I want to add a function to extract all image names from a markdown file in a _drafts/ folder, so that when the "publish" function is executed it iterates over my image_names array and moves the images to the _pages/ folder from the _drafts/ folder.

I got here from google to find that people don't think there's a good use case for checking an array length.  I was looking for the syntax to check array length for an if statement so that I'm not trying to iterate a null array and move a null number of image files.

^ use case.

But hey, stripping out all of the variable functions that my particular content doesn't use from dozens of files is an alternative, so whatevs.
