### ISSUE TITLE
Lexer: Chaining: Object definitions with leading dots on newline throws unexpected newline error

### ISSUE THREAD

**Issue by miklschmidt** [jashkenas/coffeescript#3408]
This breaks in 1.7.1 (works in 1.6.3):

``` coffeescript
class C
    a:
        c: [3..4]
            .concat [5..6]
        d: [7..8]
```

While this works in 1.7.1:

``` coffeescript
class C
    a: {
        c: [3..4]
            .concat [5..6]
        d: [7..8]
    }
```

See [my stackoverflow post](http://stackoverflow.com/questions/22356642/coffeescript-1-7-1-unexpected-newline-weirdness) for more details.

**Comment by GeoffreyBooth** [comment]
I’ve been looking into this, and I’m not sure how (or if) to fix it. So first I created a test:

```coffee
test "#3408: chain after object property", ->
  a = {}
  a.fn = -> 3
  b =
    c: a
      .fn()
  eq b.c, 3
```

Which fails in 2.0.0-beta4, but would pass if the compiler produced the output that the comments above are requesting. As I fiddle with [where this is handled](https://github.com/jashkenas/coffeescript/blob/7c627f9dfd2b9aedce3e4e3cb0f697b485f63853/src/rewriter.coffee#L362) to make the test pass, I invariably cause other tests to start failing. Such as [this one](https://github.com/jashkenas/coffeescript/blob/7c627f9dfd2b9aedce3e4e3cb0f697b485f63853/test/formatting.coffee#L191):

```coffee
  id = (x) -> x
  result = id a: 1
    .a
  eq 1, result
```

This test is expecting `result` to compile to `id({a: 1}).a`, but after getting the new test to pass, `result` instead becomes `id({a: 1.a})`. That happens to be nonsense, but if `1` were an identifier like `b`, `id({a: b.a})` would make sense; but it would be unwanted.

So the question is, if the new test’s `b` is supposed to become `{c: a.fn()}` and not `{c: a}.fn()`, how could the compiler also know to turn `result` into `id({a: 1}).a` and not `id({a: 1.a})`? Are these mutually exclusive, and we simply have to choose one output or the other? Or is there some logical rule that the compiler can follow to produce the desired output in both cases, without breaking any tests?

**Comment by GeoffreyBooth** [comment]
So I thought I had a solution, when I noticed that `{ a: 1 }.a` throws a `SyntaxError`—could we just look for a period after a `}`? But then I remembered how [destructuring requires either an expression or parentheses](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#Assignment_without_declaration), e.g. `({ a } = foo)` or `var { a } = foo`, because starting a line with `{` means you’re starting a block. So then I typed `({ a: 1 }.a)` and the runtime returned `1`. So much for that.

But this brings us back to the original issue. We can reduce it further:

```coffee
a: b
  .a
```
This currently compiles to `({ a: b }).a`, but the OP wants it to be `({ a: b.a })`.

The problem is, `({ a: b }).a` _is valid._ It’s `b`:

```js
var b = 3;
({ a: b }).a; // → 3
```

And thinking about it, this output feels correct. In general, chaining reaches back to the start of a line:

```coffee
fn arg
  .method()
# fn(arg).method(), not fn(arg.method())
```

It’s so unusual to put a property accessor after an object literal (e.g. `{ ... }.property`) that it’s easy to feel like the accessor should affect the last value of the object rather than the object overall; but I think the current output is probably correct. Or at the very least, both interpretations (`({ a: b }).a` or `({ a: b.a })`) are valid JavaScript, so it’s up to us to choose which way we want the compiler to interpret this ambiguous case. And seeing as the current implementation is valid syntactically, and changing it would be a breaking change that would affect existing code (as demonstrated by the many tests that started failing as soon as I changed it) I think we should leave this alone. Anyone who wants the other interpretation can get it easily enough by adding parentheses.

I’m happy to reopen if anyone wants to prove me wrong, and/or can explain a logical rule that the compiler can follow for when it should chain the “other” (i.e. `({ a: b.a })`) way, that doesn’t break existing code.
