### ISSUE TITLE
Invalid JS: Multiline function calls sometimes compile invalidly

### ISSUE THREAD

**Issue by danschumann** [jashkenas/coffeescript#3453]
I'm wondering why the following code does not work and compiles the same as the 2nd example

```
ar = []

ar.push \
  1
  2
  3
  4
```

Ideally, it would `ar.push( 1,2,3,4 )`, not `ar.push(1); 2;3;4;`.  The above code compiles to the same as below... which seems weird because the below code outdents and is what I would expect to compile `ar.push(1);2;3;4;`.

```
ar = []

ar.push \
  1
2
3
4
```

So I'm wondering why?  The first code could do something different.  Currently, it just doesn't care when you outdent or why.

**Comment by xixixao** [comment]
So I think this is the major thing I didn't fix in #3320 and is causing #3484, #3866 and all their duplicates (and other issues probably too).

Here's the simple repro:
```coffee
f 1,
    2
  3
```
compiles to
```
f(1, 2);

3;
```
clearly, a bug (there should be unexpected indent in front of 3 instead). Now with method calls (which are lexed in a weird way where they pretend they are on the same line) this leads to bunch of similar broken cases (method  calls == property accesses).
```coffee
f
  .b()
  2


f 1
  .b()
  3

f
  .b 1,
    1
  .g()
  3
```
outputs
```es6
f.b();

2;

f(1).b();

3;

f.b(1, 1).g();

3;
```
and so on. I don't have a fix for this, it's really tricky and can be probably fixed by changing the lexer or rewriter or both (maybe grammar, but unlikely). Maybe another contributor with more context can figure this out (it's a pretty nasty bug, as seen in the other issues).

**Comment by danschumann** [comment]
The syntax for arrays can work like this:
```
array = [
  1
  2
  3
]
```

For objects
```
ob = 
  foo: 1
  bar: 2
  baz: 3
```

But for function arguments
```
method \
  1
  2
  3
```
is out of the question?

I think there is a reason why the following doesn't work
```
method
  1
  2
  3
```

**Comment by GeoffreyBooth** [comment]
I don’t think this is fixable (without breaking too many other things) for the same reasons as #4630.

**Comment by danschumann** [comment]
It does in this case  (which is how I work around this whole issue)

```
runMethod(
  arg1
  arg2
  arg3
)
```

and in this case (but this doesn't read as well if all arguments are of the same type)


```
runMethod arg1,
  arg2
  arg3
```

both compile to `runMethod(arg1, arg2, arg3)`
