### ISSUE TITLE
try ... catch conditionals

### ISSUE THREAD

**Issue by colelawrence** [jashkenas/coffeescript#3573]
I read [this documentation on try catch with conditionals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch#Conditional_catch_clauses) in ecmascript, and thought it would be a great addition to coffeescript.

``` coffeescript
router.get '/:type', (req, res) ->
  try
   ...
  catch error if error.status isnt 501
    res.status = 404
    res.render 'result', {
      title: 404
      json:{
        message: error.message
      }
    }
```

**Comment by Zaggen** [comment]
I know this is closed and marked as wontfix, but @michaelficarra It seems that loosing stack information was an old bug in chrome, as stated here [http://stackoverflow.com/questions/3734236/how-can-i-rethrow-an-exception-in-javascript-but-preserve-the-stack](http://stackoverflow.com/questions/3734236/how-can-i-rethrow-an-exception-in-javascript-but-preserve-the-stack)
[http://stackoverflow.com/questions/9006490/is-there-any-workaround-to-rethrow-an-exception-and-preserve-the-stacktrace-in-j](http://stackoverflow.com/questions/9006490/is-there-any-workaround-to-rethrow-an-exception-and-preserve-the-stacktrace-in-j)
And According to this issue tracker, is no longer present.
[https://code.google.com/p/chromium/issues/detail?id=60240](https://code.google.com/p/chromium/issues/detail?id=60240)
I've tested it using the sample code provided by ***yangguo@chromium.org***
```
function g() { error; }
function f() { g(); }
function rethrow(e) { throw e; }
function test() {
  try {
    f();
  } catch (e) {
    rethrow(e);
  }
}
try { test() } catch (e) { console.log(e.stack) }
```
Is this a valid reason to not implement this?
We'll be using try catch blocks more and more  now that es6 generators are available as well as node-fibers, i think i'll make a nice syntactic sugar to avoid catching broad errors and manually re-throwing it in an extra else statement every time i don't want to eat it.

I'm not sure if the bug is present in other browsers, but i'll be nice to have this syntax (or something similar to other languages) when working with ***node.js***, if it is still valid, then thanks for clearing that out again :)
