### ISSUE TITLE
Allow dynamic keys for object (hash) definition

### ISSUE THREAD

**Issue by aurium** [jashkenas/coffeescript#3597]
This feature is available in Javascript, but not in Coffee.
```coffee
opts = { s('param'): 'some value' }
# unexpected (
```

```coffee
replacements =
  "#{prefix}keyname1": 'some value 1'
  "#{prefix}keyname2": 'some value 2'
# unexpected string interpolation
```

**Comment by lydell** [comment]
I’d vote for `"a#{b}c": value` to compile to `{["a" + b + "c"]: value}`. Just like `yield`, this would be a feature that works only in supporting environments; it’s up to the developer not to use it if support for an older environment is needed.

**Comment by michaelficarra** [comment]
@lydell: I like that.

**Comment by epidemian** [comment]
@lydell, but, unlike `yield`, this is a feature that can be easily implemented with ES3. 

I'd vote for using the same syntax and a similar implementation than [LiveScript](http://livescript.net/#literals) (see "Dynamic Keys"), where:

```livescript
myObj =
  x: 1
  "#{name}#{i}": 'some value' # Using string interpolation.
  (name + j): 'other value' # Using a parenthesised expression.
  somekey: someValue + myObj.x
```

Compiles to:

```javascript
// Generated by LiveScript 1.3.1
var myObj, ref$;
myObj = (ref$ = {
  x: 1
}, ref$[name + "" + i] = 'some value', ref$[name + j] = 'other value', ref$.somekey = someValue + myObj.x, ref$);
```

(the output probably needs better whitespace handling)

I like the LS syntax because dynamic string literals *look like* strings, which is the benefit of string interpolation in the first place; and because it also allows using any value as a key (using the parentheses syntax), which in turn would be useful if we want to support [Symbol properties](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol) at some point:

```coffeescript
countdown = 
  (Symbol.iterator): *->
    yield 3
    yield 2
    yield 1

# Assuming this compiles to JS's `for ... of`
for n of countdown
  console.log n
```

**Comment by lydell** [comment]
We must not forget #786 and #1731, though.

**Comment by lydell** [comment]
Good point about `Symbol` keys. That means that we need to support an alternate syntax in addition to string interpolation. Both old CoffeeScript and @epidemian used `()`. An argument for this syntax is ease of implementation, as said in https://github.com/jashkenas/coffeescript/issues/786#issuecomment-484874:

> > "#{key}": val
>
> Lexer converts interpolated strings into parenthesized concatenations, so that's actually the same thing for parser.

Another option is to use ES6-style `[]` notation. An argument for this is: Less syntax to learn.

Which is better?

**Comment by jashkenas** [comment]
We don't need to worry about Symbol keys — they're probably going to end up being considered a "nasty" part of JavaScript that CoffeeScript can enthusiastically avoid.

    "#{key}": val

Is probably the best syntax. In an alternate universe, something like: 

    key: val

... might be preferable, but that ship has sailed.

**Comment by pepkin88** [comment]
I vote for `[]` syntax. For majority of my use cases it's shorter by 3 characters comparing to `"#{}"` syntax. Also is compatible with the ES6 syntax, which means it will gain more familiarity. Moreover, I think it is more intuitive, as it's analogous to the property access syntax:
```
foo = { bar: 123 }
foo.bar

foo = { [bar]: 123 }
foo[bar]

foo = { "#{bar}": 123 }
foo"#{bar}" # not quite, looks like tagged string interpolation, also don't work

foo = { ["#{bar}"]: 123 }
foo["#{bar}"]
```

If string interpolation is needed, it can still be used like this `["#{}"]`.

Optionally the `"#{}"` syntax could be implemented additionally, because they don't collide with each other.

**Comment by lydell** [comment]
Yes, _if_ we're adding new syntax in addition to interpolation it should definitely be `[]:` since:

- No need to deviate from JS syntax.
- The symmetry argument from #3828 can be applied in reverse: Since `'a': b` works, `c.'a'` should work. Since `c[a]` works, `[a]: b` should work.
- Because of #3840 the "ease of implementation" argument no longer applies.

**Comment by pepkin88** [comment]
@lydell Oh I'm sorry, I didn't notice, that the `"#{}"` syntax is already implemented, I thought that it is still an open debate.
But still, I think the `[]` syntax for computed properties would be a nice addition, for reasons you stated :)

**Comment by jashkenas** [comment]
Let's not add new syntax for dynamic keys at the moment. If we end up needing it, we can add it later.
