### ISSUE TITLE
Confusion regarding trailing \ at the end of line in Heregex

### ISSUE THREAD

**Issue by kumarharsh** [jashkenas/coffeescript#3642]
In the multiline regexes, there is an anomaly:
```coffee
    ///
    abc\*
    \*
    ///
```
compiles to: `/abc\*\*/;`

```coffee
    ///
    abc\*\
    *
    ///
```
compiles to `/abc\*\n*/;`

I find it very confusing, especially, wrt to how the newer version of coffee-script compile the multiline strings:

```coffee
    """
    a \
    b
    """
```
compiles to `"a b";` and **not** `"a \nb";`

IMO, the `\n` being added to the compiled regex if the line ends with a trailing `\` is **not consistent** with the behaviour for multiline strings.

Also, I would expect to break a multiline-regex into smaller lines from anywhere, and still get the same result. But the addition of the `\n` doesn't satisfy that expectation.

I have taken a look at the discussion at #3214 , and especially at [this comment](https://github.com/jashkenas/coffeescript/pull/3214#issuecomment-26933867), but since the newer versions of coffee-script have changed the behaviour of multiline strings, this anomaly should also be fixed.

**Comment by lydell** [comment]
So, the complaint in the OP is:

> IMO, the \n being added to the compiled regex if the line ends with a trailing \ is **not consistent** with the behaviour for multiline strings.

I’d say that a trailing \ does not need to be “consistent” with multiline strings (assuming heredocs, since that’s what’s in the example in the OP). Why? Because heregexes are not “consistent” with heredocs in the first place! Heredocs preserve newlines and indentation, while heregexes do the opposite: _removing_ whitespace!

Regarding the linked discussion in #3214:

> Seems to me allowing trailing \ as \n is: Much simpler to explain: "Heregexes ignore non-escaped whitespaces."

That’s a good point.

> It may seem somewhat illogical, but my reasoning was that an operator (\ at end of line) shouldn't have two opposite meanings depending on context. (That would be counter-intuitive IMO.)
>
> [...] I think it should compile to /ab/.
>
> > In what context the other meaning comes into play?
>
> ```coffee
x = some.long thing \
      or something.else
```

I see the point. The following:

```coffee
x = some.long thing \
      or something.else
'''
  First line \
    continued here.
  Second line.
'''
'Some text that is line-\
    wrapped to the next line.'
```

is equivalent to:

```coffee
x = some.long thing or something.else
'''
  First line continued here.
  Second line.
''' # This also explains the @connec’s question at the very end of the previous comment.
'Some text that is line-wrapped to the next line.'
```

Following the above, perhaps

```coffee
///
  a \
    b
///
```

should be equivalent to

```coffee
///
  a b
///
```

That might be more “consistent“ with the other uses of \ at the end of a line. On the other hand it is also inconsistent: In the other cases removing the \ makes a difference, while removing it in the heregex wouldn’t.

> Another option is for an end-of-line \ in a heregex to produce a compile-time error. I'm sure we all agree that a literal \n is clearer. Disallowing \ at end of line in this context would remove the possibility for confusion.

That’s also a valid point.

But finally, we have the following quotes from @jashkenas:

> > Isn't this counter-intuitive? I'd expect [...] to mean /a\nb/ rather than /a\b/.
>
> Agreed.
>
> [...]
>
> I think @satyr's reasoning here is convincing. Let's allow it to escape whitespace and newlines

In the end it doesn’t matter that much. Nobody uses a \ at the end of heregexes anyway. So I think it is settled.

**Comment by jashkenas** [comment]
> So I think it is settled.

So you think this can be closed?

**Comment by lydell** [comment]
Oh yes.
