### ISSUE TITLE
script/coffeescript tags don't work in IE 8

### ISSUE THREAD

**Issue by liammclennan** [jashkenas/coffeescript#366]
I get an error immediately when I go to http://jashkenas.github.com/coffee-script/ in Internet Explorer 8. 

The text of the error is: 

User Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; WOW64; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; InfoPath.2; .NET4.0C; .NET4.0E)
Timestamp: Sun, 9 May 2010 06:29:18 UTC

Message: 'prototype' is null or not an object
Line: 1
Char: 251857
Code: 0
URI: http://jashkenas.github.com/coffee-script/extras/coffee-script.js

**Comment by toomim** [comment]
This feature indeed is useful for debugging. What about enabling it as an option that people can enable in development, when testing on chrome/firefox/safari? They could then disable it in production.

I'd also be able to use this option for most of my coffeescript projects because they compile in the browser. So I can detect at run-time if the browser is not IE, and if so, enable the anonymous named functions.
