### ISSUE TITLE
Allow "continue" and "break" within comprehensions, behaving as filters.

### ISSUE THREAD

**Issue by weepy** [jashkenas/coffeescript#372]
<pre>
x: ->
  t: for move in moves
    continue if x
    move  
</pre>

gives

<pre>
var x;
x = function x() {
  var _a, _b, _c, _d, move, t;
  t =   _a = []; _c = moves;
  for (_b = 0, _d = _c.length; _b < _d; _b++) {
    move = _c[_b];
    if (x) {
      continue;
    }
    move;
  }
_a;
};
</pre>

Note the final _a

**Comment by doublerebel** [comment]
:+1: for `break` in the form of `take while`/`take until` as described in #3158.
I think linked lists are a great example of why this is useful as described in #3499.
This is rather related to #899/#869, but then I saw #1669, where `continue` _is_ actually implemented.

I was creating a comprehension in this form (oversimplified example):
```coffee
list = for x in [1,2,3]
  if x is 1
    x
  else if x is 2
    x
```
I was surprised to find Coffee inserting a void(0) at the end.  I would argue in this case the expected behavior would be an implicit `continue`, rather than an implicit `void(0)`, and a `void(0)/undefined/null` should be explicitly specified if needed.

I was able to solve it by using continue as specified in #1669:
```coffee
list = for x in [1,2,3]
  if x is 1
    x
  else if x is 2
    x
  else continue
```
This is counter-intuitive IMHO, but I'm sure swapping the behavior would be a breaking change for dependent code.  Therefore I think the clearest path forward is `take while`/`take until`.
