### ISSUE TITLE
`do variable = (name = 2) ->` doesn't test parameter for null when calling

### ISSUE THREAD

**Issue by xfix** [jashkenas/coffeescript#3820]
Assume following code.

```coffee
do checkDefaultValue = (defaultValue = 'Test passed') ->
  defaultValue

alert checkDefaultValue()
```

Expected result: `Test passed`
Actual result: `undefined`

**Comment by jashkenas** [comment]
That's a very strange bug!

**Comment by michaelficarra** [comment]
That is not a default. This is a special form of `do`. See https://github.com/jashkenas/coffeescript/issues/3776.

**Comment by jashkenas** [comment]
Where did that special form come from again? Is it documented?

**Comment by vendethiel** [comment]
#960, #2362#issuecomment-6025048

**Comment by jashkenas** [comment]
Pretty gross stuff. That's what I get for not paying close attention ;) We should `do` something about it.

**Comment by michaelficarra** [comment]
No, I like this feature.

**Comment by ippeiukai** [comment]
As I pointed out in #3776, `do` behaves in 3 ways: two are understandable and intuitive, and one so weird and unintuitive that I can only explain it as a bug. This ticket is pointing out the existance of the third case again.
Please please `do` something about it.

@jashkenas, wouldn't it be a good start to at least recognise this as an issue and keep the ticket open?

**Comment by michaelficarra** [comment]
But it is not a bug. I assure you, this feature was intentional.

**Comment by ippeiukai** [comment]
@michaelficarra 
You have dismissed my request to document the behaviour too though. If this is intentional yet more tickets about the same unpredictableness is polling in, why can't we agree that something needs be done?

I just say this is so surprising a behaviour and yet is undocumented on the website (so surprising that It is hard for us users to believe a nice language like CoffeeScript do have in its spec). I won't dispute it if it is documented and sealed (though I may personally dislike it like I do PHP).

So, correct me if I'm wrong:
```coffee
do checkDefaultValue = (defaultValue = 'Test passed') ->
  defaultValue
```
This reads: `checkDefaultValue` is assigned with a function that takes one argument with no default value, and gets executed once with `'Test passed'` as that argument (forwarding, so evaluated outside the scope of the function unlike default values). 

If one uses brackets around like this: 
```coffee
do (checkDefaultValue = (defaultValue = 'Test passed') ->
  defaultValue
)
```
`checkDefaultValue` would instead be assigned with a function that takes one argument with default value `'Test passed'` (default value, so evaluated inside the function) and gets executed once without any argument.

Can we include this in the doc somewhere?

**Comment by michaelficarra** [comment]
There are three syntactic forms including `do`, each with separate semantics:

0. `do (<parameter-list>) -> <expression>`
0. `do <identifier> = (<parameter-list>) -> <expression>`
0. `do <expression>` (but not matching either of the above)

Go ahead and open a PR that adds that info to the docs. Or if you'd rather, just open an issue.

**Comment by ippeiukai** [comment]
> Go ahead and open a PR that adds that info to the docs. Or if you'd rather, just open an issue.

I'll do that as soon as I get some time.
Thank you for the syntax snippet. It really helps.
