### ISSUE TITLE
`yield return` isn't documented

### ISSUE THREAD

**Issue by ide** [jashkenas/coffeescript#3825]
It does come in use in a few places. Just making note of the missing documentation here.

**Comment by nfour** [comment]
I've been meaning to test whether these two examples are the same, it's a bit unclear:

```coffee
->
  yield return generatorFn()

->
  return yield generatorFn()
```

**Comment by ide** [comment]
@nfour They are different:
```
(function*() {
  return generatorFn();
});

(function*() {
  return (yield generatorFn());
});
```

If you are using a library like co these snippets are not always interchangeable because co handles completed generators (i.e. after the return statement executes) differently than ones that are still in progress, so `return generatorFn()` and `yield generatorFn()` are treated differently. Arguably co should not make that distinction but it does.

Also `return yield generatorFn();` incurs extra overhead because the generator needs to be resumed one extra time after the `yield` and before the `return`. It's mostly negligible but in a very large codebase with tens of millions of lines this adds up.

**Comment by nfour** [comment]
Ah, thanks @ide, I thought it worked like that.

Im starting to wish we still had a `->*` syntax as, like you said, when you have functions that need to be generators it means you have to explicitly add `yield return` to the end of the function, to the point where it becomes redundant in some cases. If I don't do that, and if the function is refactored to no longer `yield`, it will cease being a generator. Leaving it implicit feels highly ambiguous. Going to take a while to get used to this!

**Comment by epidemian** [comment]
TBH, i don't even understand *why* the `yield return` "idiom" works the way it does. It should be added to the docs, though i'd prefer the decision of adding such construct to be revisited before formalizing it on the docs :sweat_smile:

**Comment by vendethiel** [comment]
> TBH, i don't even understand why the yield return "idiom" works the way it does

Because people wanted a way to have a non-yielding generator (co etc), I (half-jokingly) suggested this syntax and it was accepted/added.

**Comment by lydell** [comment]
Both generators and bound arrow functions were added in ES6. Wouldn’t it have struck the specification writers that if there’s a bound version of regular functions (arrow functions), shouldn’t there also be a bound version of generators? (Perhaps somebody could dig up some meeting notes or something on esdiscuss on this). Since ES6 does not have bound generators, perhaps that is not a common use case? I don’t know, because I haven’t used generators and yield that much myself. _If_ that’s the case, it might make sense to make `~>` the syntax for generators, avoiding both the somewhat strange `yield return` construct and the main argument against adding new syntax for generators: The combinatorial effect on the amount of different arrows. Have anyone used `yield` inside a `=>` function yet?
