### ISSUE TITLE
['1' .. 2] yields ['1', 2]

### ISSUE THREAD

**Issue by alethes** [jashkenas/coffeescript#3865]
I just noticed that `['1' .. 2]` compiles to 
```
var _i, _results;

(function() {
  _results = [];
  for (var _i = '1'; '1' <= 2 ? _i <= 2 : _i >= 2; '1' <= 2 ? _i++ : _i--){ _results.push(_i); }
  return _results;
}).apply(this);

// ---
// generated by coffee-script 1.9.0
```
, so that the resulting array is `['1', 2]`. 

Is this a correct behavior?

**Comment by michaelficarra** [comment]
That's JavaScript for you. Would you have expected something different?

**Comment by epidemian** [comment]
To expand a bit on @michaelficarra's reply, even though `[a..b]` is a CoffeeScript construct, it could be explained in "just JavaScript" with "set `i` to `a` and while `i` is less or equal than `b`, collect `i` and increment it". Unfortunately, both in JavaScript and CoffeeScript, `'1' <= 2` is true, and `i = '1'; i++; i` is 2.

Checking for such oddities in CoffeeScript would make it a saner language, but also a much slower one. And that's the reason we're stuck with these ridiculous things :stuck_out_tongue:

**Comment by epidemian** [comment]
Hmm. I stumbled upon another oddity while playing with this: `x for x in ['1'..3]` evaluates to `["1", 2, 3]`, but `x for x in ['1'..3] by 1` evaluates to `["1"]`. Isn't that weird?

Hint: `x for x in ['1'..1000] by 1` evaluates to `["1", "11", "111"]` :wink: 

Maybe we can force the generated loop variable `i` to coerce to a number at the start of the loop to get rid of both these problems?

`arr = [a..b]` could compile to:

```javascript
var arr, i, results;

arr = (function() {
  results = [];
  for (var i = +a; a <= b ? i <= b : i >= b; a <= b ? i++ : i--){ results.push(i); }
  return results;
}).apply(this);
```

(notice the `+` in `var i = +a`)

This would make `['1'..2]` evaluate to `[1, 2]` and `x for x in ['1'..3] by 1` evaluate to `[1, 2, 3]` instead of them evaluating to `['1', 2]` and `['1']` respectively, which i think is a saner behaviour. 

That being said, it make no sense to consider these cases, as they are still quite nonsensical code hehe.

**Comment by jashkenas** [comment]
I don't think we need to add extra code for this sort of thing.
