### ISSUE TITLE
Custom wrapper function

### ISSUE THREAD

**Issue by kdabir** [jashkenas/coffeescript#3879]
I really like the wrapper that coffeescript generates hence going `-b` is not an option. Is there a way I can provide a custom wrapper function template? for example:

    (function() {
      'use strict'; 
      // generated JS code here
    }).call(this);

**Comment by jashkenas** [comment]
Just put 

    "use strict"

at the top of your file. Voilá.

**Comment by kdabir** [comment]
well, that's already the case. Had it been just one file I wouldn't even mind putting function wrapper myself. The point was automatically having it included in all files that are getting compiled.

**Comment by jashkenas** [comment]
Maybe make it part of your build process then. I'm not personally a huge fan of `use strict`, so I don't think we should make it a flag in CoffeeScript. Hopefully "strict" will simply be the default in future versions of JS, and no bizarro string flag will be required.

**Comment by kdabir** [comment]
Oh `use strict` was just for sake of example. I was generally interested in a getting sort of ability to alter the function wrapper. For some it could be used for `use strict`, or changing the `this` that gets bound, or passing param to IIFE, or anything of that sorts. Nevermind. Before writing grunt task, just wanted to check if I wasn't missing something.

**Comment by jashkenas** [comment]
> changing the this that gets bound

Why?

> or passing param to IIFE

Why?

For us to make changes — we need use cases.

**Comment by kdabir** [comment]
Not really a very common use case, hence I would not treat this a coffescript issue/enhancement.

We are creating a DSL like config files in coffee and instead instead of having users wrap their calls in a function, we could bound a different object instead of `this` to a set of config coffee files so that some custom functions are implicitly available in config files without having to expose those functions on `window` or having to call them on named object.

**Comment by epidemian** [comment]
@kdabir That seems like a reasonable use case to me. Ruby has quite a few examples of those kind of files: `Gemfile`'s get executed in a scope where `gem` or `group` methods are available; `config.ru`'s expect that `map` and `use` exist; etc.

A use case for CS/JS could be, for example, compiling all files in `spec/**.coffee` with a preamble that declared `describe`, `it` and `expect` functions, so that they are available for all those files without having to copy&paste one or two lines of boilerplate for each of them, and without cramming those functions into the `global` scope.
