### ISSUE TITLE
Parameter naming in 1.9.1 breaks existing code

### ISSUE THREAD

**Issue by devongovett** [jashkenas/coffeescript#3891]
In previous versions before 1.9.1, you could do this:

```coffeescript
class Dog
  constructor: (@name) ->
    console.log(name)
```

since `@name` and `name` were the same thing. The parameter of the function was called `name`, and was assigned to `this.name` at the start of the function.

In 1.9.1, the naming changed. The parameter is called `name1` for example, and is assigned to `@name`, so the normal `name` variable is not available and the above code will throw a reference error. This breaks existing code that relied on the old behavior where both a local variable and a property on `this` were available.

I'm already getting [pull requests](https://github.com/devongovett/fontkit/pull/3) to update code to stop using the local variable that was available before. I can update all of these (if I can find them all - thank goodness for tests), but I wanted to make sure that this wasn't an unintended change, especially since it changed in a patch release.

**Comment by vendethiel** [comment]
That's in the changelog.

**Comment by devongovett** [comment]
I don't see anything about this there. It says "Internal compiler variable names no longer start with underscores". This was not an internal compiler variable name, nor did it start with an underscore.

**Comment by devongovett** [comment]
Also, in the future, if you're going to make breaking changes, please do so in a non-patch version (following semver). Otherwise packages built with CoffeeScript will break without them doing anything (npm automatically installs the latest patch version usually).

**Comment by vendethiel** [comment]
> I don't see anything about this there. It says "Internal compiler variable names no longer start with underscores". This was not an internal compiler variable name, nor did it start with an underscore.

This was definitely a compiler-generated variable. Nowhere was `name` declared in your code


> Also, in the future, if you're going to make breaking changes, please do so in a non-patch version (following semver).

I can probably point at @jashkenas ' https://gist.github.com/jashkenas/cbd2b088e20279ae2c8e

**Comment by devongovett** [comment]
I never really wanted this local variable behavior either, and argued against it in #535 where I proposed this feature, but it was how CoffeeScript worked for many many years. @jashkenas may dislike semver, but it is what npm uses and so it is what we must follow to some degree. npm will likely install patch versions automatically, depending on how the CoffeeScript dependency is specified in package.json. So if those patch versions contain breaking changes, you're going to break a lot of code.

I'll update my projects to stop using this behavior. This issue was mostly created in annoyance for breaking my code. :wink:

**Comment by lydell** [comment]
You have confused 1.9.1 and 1.9.0. The change was in 1.9.0 (so it was actually in a _minor_ release, not a _patch_ release to be precise). And the changelog entry for 1.9.0 is pretty clear:

> Changed strategy for the generation of internal compiler variable names. Note that this means that `@example` function parameters are no longer available as naked `example` variables within the function body. 

Moreover, I'd suggest pinning your coffee dependency with `~`.

**Comment by devongovett** [comment]
Clearly I need sleep. Sorry guys.

**Comment by backspaces** [comment]
How in gods name can I find all the places in my code where this breaking change will cause errors? Is there a compiler flag to catch this?

I *always* use local variables where available so this is likely to lurk everywhere.  I need help in converting.

I ran across this due to using gulp-coffee which uses the latest version of coffeescript, so was blind-sided by this.

**Comment by kayhadrin** [comment]
Coffeescript was generating a local variable with the same name as the function's "@" parameter name since quite some time. (At least more than a year)

You can **still** see it in the official page's documentation: http://coffeescript.org/#classes

See excerpt below:

```coffee
class Animal
  constructor: (@name) ->
  # ...
```

Becomes:

```js
// I voluntarily removed some of the util functions to help constructing classes for conciseness
var Animal = (function() {
  function Animal(name) {
    this.name = name;
  }
  // ...
  return Animal;
})();
```

Since this was demonstrated like this, it's not surprising that many people relied on this compiler behaviour. 

Could you reconsider adding this behaviour back?

And by the way, what was the reason for this change in the first place?

It would help understanding the big picture for everyone in this thread.

**Comment by kayhadrin** [comment]
Coffeescript was generating a local variable with the same name as the function's "@" parameter name since a bit more than 4 years.

You can **still** see it in the official page's documentation: http://coffeescript.org/#classes

The excerpt below:

```coffee
class Animal
  constructor: (@name) ->
  # ...
```

Becomes:

*I voluntarily removed some of the util functions to help constructing classes for conciseness.*

In [November 2010](http://web.archive.org/web/20101114070023/http://jashkenas.github.com/coffee-script/):
```js
Animal = function(_arg) {
  this.name = _arg;
  return this;
};
```

In [December 2010](http://web.archive.org/web/20101230111719/http://jashkenas.github.com/coffee-script/) and this is still the same on the current site as of the 1st of April 2015:

```js
function Animal(name) {
  this.name = name;
}
```

In [January 2015](http://js2.coffee/#coffee/try:class%20Animal%0A%20%20constructor%3A%20(%40name)%20-%3E)

```js
function Animal(_at_name) {
  this.name = _at_name;
}
```

Since this was demonstrated like this for so long, it's not surprising that many people relied on this compiler behaviour.

So could you reconsider adding this behaviour back?

And by the way, what was the reason for this change in the first place?
It would help understanding the big picture for everyone in this thread.

**Comment by connec** [comment]
Please read the comments.  This was fixed in 1.9.1 (as long as you don't make a habit of using undefined variables):

```coffee
(@a) ->
```

```js
// Generated by CoffeeScript 1.9.1
(function(a) {
  this.a = a;
});
```

**Comment by kayhadrin** [comment]
Thanks for this example. 
It was not obvious in the comments that the 1.9.1 version restored that compilation behaviour.

**Comment by lydell** [comment]
Nope, it does not. You should change those bare `name`s to `@name`s. That's what you always have been supposed to do, though older versions of CoffeeScript accidentally allowed you to drop the `@`.

**Comment by kayhadrin** [comment]
*One day, a expert network engineer friend told me to care about my users needs. 
Always ask them, what can I do for you, he said.
This usually helps me see past any personal annoyance and try to see the situation through their eyes.*

So here, I can understand that it was not the intended behaviour of the CS creator but I would concede that several facts enabled CoffeeScript users to rely on this.

1. The previous compilation behaviour was present in CoffeeScript
 for the last 4 years.
2. The [official website still demonstrates it](http://coffeescript.org/#classes).  
e.g. `function Animal(name) { this.name = name; }`
3. The [Smooth CoffeeScript online book](http://autotelicum.github.io/Smooth-CoffeeScript/interactive/interactive-coffeescript.html#section-200) referred from [the wiki](https://github.com/jashkenas/coffeescript/wiki#the-coffeescript-wiki) explains it literally: 

	> The constructor for the `Rabbit` class is `constructor: (@adjective) ->`. 
	> The `@adjective` argument to the constructor does two things: 
	> It declares `adjective` as a property on `this` and it uses ‘pattern matching’ 
	> i.e. the same name to assign the argument named `adjective` to a property on `this` that is also named `adjective`. 
	> It could have been written in full form as `constructor: (adjective) -> this.adjective = adjective`.

My only goal is to try to keep my project in sync with the latest CS improvements, but I found this breaking change on the way; and the effort of finding and fixing the impacted functions is not negligible.

So is there any particular reason beside "it was not intended to work like that before" that justifies changing this in the first place?

Otherwise, I don't see any special reason to defend this change that strongly either.

**Comment by lydell** [comment]
> The official website still demonstrates it.
> e.g. function Animal(name) { this.name = name; }

It is also demonstrated that `ref` variables are created sometimes, but you cannot access them either.

> So is there any particular reason beside "it was not intended to work like that before" that justifies changing this in the first place?

Yes, see https://github.com/jashkenas/coffeescript/issues/3927#issuecomment-88742929. Specifically the beginning of #1007.

**Comment by epidemian** [comment]
@lydell i agree with the current semantics of these `@` parameters; the behaviour in CS < 1.9 was wrong. But i think this change could have been released with more consideration for the users that relied on the old behaviour.

Maybe releasing a version of the compiler that would complain about references like `(@foo) -> foo` and tell the user to use `@foo` to refer to the parameter. Either with a warning, or even with a compiler error, because there was no way the user intended for `foo` to refer to a variable on an outside scope (or a global) as the compiler had always interpreted that as a reference to the `@foo` parameter before. After a while, another version with the correct behaviour could be released.

At least that way the compiler would provide some feedback for the users about the new semantics of `@` parameters, instead of silently changing the behaviour of their code.

Maybe we're still on time for doing that. I mean, disabling or warning about code that relied on CS 1.8 on CS 1.9, and leaving the correct behaviour for a future version. Would that be preferable?

**Comment by nkohari** [comment]
This issue caused me to be temporarily concerned for my sanity. :)

I use [forge](https://github.com/nkohari/forge) to manage dependencies in my application. To determine what dependencies a given component needs, it uses `Function.toString()` and regexes out the parameter names from the function definition. It's a terribly dirty hack, but it is (oddly enough) supported by the ECMAScript spec.

It appears that the variable names used in the constructor definition depend on the variables defined elsewhere in the file. For example:

```coffeescript
class ExampleComponent
  constructor: (@foo, @bar) ->
```

Will compile to:

```javascript
(function() {
  var Example;
  Example = (function() {
    function Example(foo, bar) {
      this.foo = foo;
      this.bar = bar;
    }
    return Example;
  })();
}).call(this);
```

But this:

```coffeescript
class Example
  constructor: (@foo, @bar) ->
  doStuff: ->
    foo = 42
```

Compiles to this:

```javascript
(function() {
  var Example;
  Example = (function() {
    function Example(foo1, bar) {
      this.foo = foo1;
      this.bar = bar;
    }
    Example.prototype.doStuff = function() {
      var foo;
      return foo = 42;
    };
    return Example;
  })();
}).call(this);
```

My system expects the constructor parameter to be named `foo`, but since it's actually named `foo1`, it can't do the dependency lookup and everything explodes in a fiery ball of sadness and despair.

Changing the name of `foo` within the function fixes the issue, as:

```coffeescript
class Example
  constructor: (@foo, @bar) ->
  doStuff: ->
    privateFoo = 42
```

Compiles to:

```javascript
(function() {
  var Example;
  Example = (function() {
    function Example(foo, bar) {
      this.foo = foo;
      this.bar = bar;
    }
    Example.prototype.doStuff = function() {
      var privateFoo;
      return privateFoo = 42;
    };
    return Example;
  })();
}).call(this);
```

I recognize that my specific use case is a tad bizarre, but it's sort of strange that the declaration of a variable in a different scope would result in a change to the name of a variable elsewhere. Also, I don't see a need to mangle the names of the constructor parameters in this case. Am I missing something?

**Comment by lydell** [comment]
> it's sort of strange that the declaration of a variable in a different scope would result in a change to the name of a variable elsewhere

Yes, but it's the easiest way to do it. The current logic is that CoffeeScript never names a generated variable the same as any of your own variables, regardless of where in the file they are used.

**Comment by michaelficarra** [comment]
> It's a terribly dirty hack, but it is (oddly enough) supported by the ECMAScript spec.

Not really. ES5 specifies that `Function::toString` must return a string that "has the syntax of a FunctionDeclaration". That is the *only* requirement. ES6 goes quite a bit further in that it requires the string to contain a function that, if executed in the same lexical environment as the `this` value, would behave identically. Still, this does not impose any restrictions on the parameter names. So no, this method has never been reliable, and still is not to this day.

**Comment by kayhadrin** [comment]
+1 for @epidemian's suggestion to add a warning during compilation when `@var` is used as a function parameter and inside the function body.

**Comment by pke** [comment]
+1 to add a compiler warning when such old var is used inside the function.

**Comment by pke** [comment]
@lydell ok, but since this worked for years now, how about a compiler warning when this incorrect behaviour is detected? Manually checking this in tens of dozens of files is quite some work.

**Comment by lydell** [comment]
Good news everyone! Today I got the time and inspiration to write a mod of the
compiler that finds all occurances where you need to add a missing `@`.

https://github.com/lydell/coffee-script/tree/1.8-at-params-warn

```sh
$ npm install lydell/coffee-script#1.8-at-params-warn
coffee-script@1.9.2 node_modules/coffee-script
$ cat file-to-check.coffee
class A
  constructor: (a, @unique) ->
  a: (name) -> name
  b: (@name) ->
    name = name.trim()
    this.name = name
    foo((i, name)->
      alert i + name
    )
    name.name
  c: -> name
$ ./node_modules/.bin/coffee -p file-to-check.coffee >/dev/null
5:5: Rename name to @name
5:12: Rename name to @name
6:17: Rename name to @name
10:5: Rename name to @name
```

Hope it helps.

**Comment by pke** [comment]
Thanks lydell! This should be patched into the next release.

**Comment by lydell** [comment]
@pke I’ve fixed the object literal false positive bug and added filename to the output now (forced pushed).

I’m not sure it is a good idea to merge this and putting it in a release, though. The code is a nasty hack (IMO), and depends on implementation details that could easily break at any time. Also, we’d have to put it behind a flag, since it warns on valid 1.9.0+ usage. Lastly, I’ve written no tests.

**Comment by pke** [comment]
This new version does not catch any errors anymore.

**Comment by lydell** [comment]
@pke Odd, I just tried with a fresh clone and it worked as intended for me.

**Comment by pke** [comment]
I did a "npm update" so I should have your newest version in my local node_modules folder, correct?

**Comment by lydell** [comment]
No, I think `npm update` updates according to package.json.

**Comment by pke** [comment]
Right, I did a npm install from your repo and it worked now! Thanks!

**Comment by aryeh-looker** [comment]
I'm currently upgrading from `1.8.x` to `1.11.1` and am running into this. I have tried the linter that @lydell wrote with great success, but some things are not being caught and are cause for some concern. An example:

CoffeeScript:

```
describe "Main thing I want to test", ->
  beforeEach ->
    inject ($controller) ->
  describe "Other thing I want to test", ->
    beforeEach ->
      inject (@$controller)->
```

Transpiled JS:

```
describe("Main thing I want to test", function() {
  beforeEach(function() {
    return inject(function($controller) {});
  });
  return describe("Other thing I want to test", function() {
    return beforeEach(function() {
      return inject(function($controller1) {
        this.$controller = $controller1;
      });
    });
  });
});
```

I think it might be relatively easy to patch the current compiler to emit warnings for this kind of thing (e.g. look for cases where a number like `1` is being appended to a parameter name). I might look into that. Wondering: has anyone else run into this and found a solution?
