### ISSUE TITLE
yield alone not working as expected

### ISSUE THREAD

**Issue by elclanrs** [jashkenas/coffeescript#3944]
I have the following code in JS:
```javascript
var each = run(function* (f) {
  while (true) {
    f(yield)
  }
})
```
But in Coffee, the following code throws an error:
```coffeescript
each = run (f) ->
  loop
    f yield
  return
```
and the following:
```coffeescript
each = run (f) ->
  loop
    x = yield
    f x
  return
```
compiles to:
```javascript
each = run(function*(f) {
  var x;
  while (true) {
    x = (yield f(x));
  }
});
```
That wasn't what I expected, so I had to do this, which isn't ideal:
```coffeescript
each = run (f) ->
  loop
    x = yield undefined
    f x
  return
```
Is this behavior expected or am I missing something here?

**Comment by vendethiel** [comment]
That seems to be a bug to me. People might argue both ways – it doesn't make sense to not yield anything, but it's allowed in JS.

**Comment by BlaXpirit** [comment]
Of course it makes sense to not yield anything! There are at least 2 good reasons. To pause the coroutine and get a value.

**Comment by jashkenas** [comment]
Paging @alubbe.

**Comment by alubbe** [comment]
I believe it was not allowed in one of the initial specs that I followed during implementation. 

I am ambivalent about having it or not, but I also have not run into the any use case where I would I need this "empty" yield. What's everyone else's take on it?

**Comment by lydell** [comment]
A `yield` is a bit like a `return`. Since `return` is allowed by itself, `yield` should be as well. No need to deviate from JS here.

**Comment by elclanrs** [comment]
There are many use cases of empty yields. Check this library as an example https://github.com/DanShappir/Emit/blob/master/js/emit.js

**Comment by lydell** [comment]
@elclanrs good point. That pretty much settles it, doesn't it?

**Comment by jashkenas** [comment]
> I also have not run into the any use case where I would I need this "empty" yield.

Huh? At any point where you want to retrieve a value, you might need an "empty" yield.

    eachFromStream ->
      value = yield
      ...

**Comment by alubbe** [comment]
Alright, let's do it :)
I'll try to look at it over the next days

**Comment by alubbe** [comment]
I've started playing around with the following implementation https://github.com/alubbe/coffee-script/commit/b1aad8674ed1e5e7b50398caaccd946173ea795b
It fixes the cases described here.

Unfortunately, it somehow gets higher precendence than "YIELD Expression". I've tried reordering in line 551 as well as with the operators array in line 599, but to no avail. Any pointers what I'm missing?

**Comment by alubbe** [comment]
does anyone have input for me on what's causing the change in precendence?

**Comment by lydell** [comment]
@alubbe I know it’s been months since you asked, but here are some thoughts:

Reordering around line 551 is useless, because as far as I remember the order doesn’t matter. Jison takes care of it. This is also mentioned in the comment a few line above:

> Here they are grouped by order of precedence. The actual precedence rules
> are defined at the bottom of the page.

(As a side note: when reading that it feels like the yield stuff should be moved for stylistic purposes ;) )

That comment also says:

>  Arithmetic and logical operators, working on one or more operands.

Note **one or more operands.** A lone `yield` has no operand, right? So does it really make sense to put it here? I tried adding `'YIELD', -> new Literal $1` to `Expression: [...]`. After that, the test suite still passed, and I was able to parse `-> yield` and `-> value = yield`. Perhaps something along these lines is the way to go. Unfortunately, I know too little about yield to finish a PR for it. If you feel like tackling it again it would be great! :)

**Comment by alubbe** [comment]
Thanks for your input @lydell!
Did you run `npm run test-harmony`? I'm getting several failures, esp. on 
```coffee
->
  yield for i in [1..3]
    i * 2
```
Also, when I add 'YIELD' to the expressions, it stops recognizing `YIELD Statement`, `YIELD Expression`, and `YIELD FROM Expression` and builds incorrect code. I assume this is because the rule `YIELD <no args>` is always matched before `YIELD <1 or more args>`. 
Could you double-check what output your local changes produce and if the generators tests pass?

**Comment by lydell** [comment]
Oh, I wasn't even aware of test-harmony. Too bad.

**Comment by alubbe** [comment]
Nooo - not the answer I was hoping for @lydell :wink: 

But seriously, we would need one behaviour for `YIELD <no args>` and another for `YIELD <1 or more args>`, how can we use jison and our setup to do that?

**Comment by lydell** [comment]
Perhaps one could try to match `YIELD TERMINATOR` instead of `YIELD <no args>`.

**Comment by alubbe** [comment]
Won't work either :/ Can I interest you in pair-coding some time week to tackle it together?

**Comment by lydell** [comment]
Perhaps we could!

The only idea I have right now is to emit a different token for lone `yield`, such as `YIELD_EMPTY`, either by using lookahead in the lexer (I think we already do that somewhere), or by adding a new rule to the lovely rewriter.

**Comment by jashkenas** [comment]
A different token shouldn't be necessary.

It should be possible just to have one Jison rule for `YIELD`, and another for `YIELD EXPRESSIONS`

**Comment by alubbe** [comment]
That's what I was hoping to find - but so far `YIELD` always gets precedence over `YIELD <EXPRESSION/STATEMENT/....>`.

**Comment by alubbe** [comment]
@lydell shoot me an email at git@lubbe.org

**Comment by jashkenas** [comment]
Ah, I think this will solve it for you. Instead of just adding a yield as a choice within `Operation`, create a new "Yield" node + section of the grammar. 

Then:

```
Yield: [
  o 'YIELD', -> new XXX
  o 'YIELD Statement',                        -> new Op $1 , $2
  o 'YIELD Expression',                       -> new Op $1 , $2
  o 'YIELD FROM Expression',                  -> new Op $1.concat($2) , $3
]
```

Then, you can tuck `Yield` back under `Operation` if you like, or put it somewhere more appropriate. (It's not really an operation, is it?)

**Comment by alubbe** [comment]
I've tried that this week, but it will still parse every occurrence as the
plain YIELD, never as the others.
Am 11.09.2015 5:20 nachm. schrieb "Jeremy Ashkenas" <
notifications@github.com>:

**Comment by alubbe** [comment]
fixed and merged - give the master a try

**Comment by vendethiel** [comment]
Actually, I'm not sure this issue should be closed, since we lost "some" expressive power by allowing that. But surely, that's for a different ticket...

**Comment by lydell** [comment]
Yes, that'd be a "fix the parsing limitation that prevents us from ... however you summarize it" issue.

**Comment by vendethiel** [comment]
@lydell I guess you're the new thunder-storming janitor now, finding all the duplicates etc :P
