### ISSUE TITLE
try without catch/finally is not documented

### ISSUE THREAD

**Issue by socketpair** [jashkenas/coffeescript#3958]
```
try
  42
```

is NOT (!) syntax error, and converted to

```
try {
  42;
} catch (_error) {}
```

effectively hiding any exceptions in ``try`` block. Either fix implementaion (require either ``finally`` or ``catch`` block), or documentation (say that ``catch``/``finally`` is optional and mean empty body in that case).

I prefer code fixing instead of documenting.

**Comment by michaelficarra** [comment]
This feature is intentional. The `try` documentation needs some improvement.

**Comment by SonOfLilit** [comment]
Currently it is documented as:

```
Try-expressions have the same semantics as try-statements in JavaScript, though in CoffeeScript, you may omit both the catch and finally parts.
```

I'd understand it as saying that this:

```
try
  f()
```

is the same as this:

```
try
  f()
finally
  null
```

which I would expect to do the same as:

```
f()
```

This is not a good description of the implemented behavior, which is to translate

```
try
  f()
```

to

```
try {
  f();
} catch (_error) {}
```

What's worse, this creates a kind of bug that is very hard to notice (hiding exceptions, thus hiding that there was a problem.) Beginners could spend days baffled by this.

Is there a reason not to change:

```
try
  f()
```

into a compiler error, or at least a warning? It would fail to compile some existing code, but I can't think of any situation where such code is written intentionally, and not because of wrong documentation or deleting some code without thinking of the surprising consequences it would have on remaining code.

I recently read a really good explanation of why these situations should be compile errors, by Eric Lippert from the C# design team in [this](http://www.informit.com/articles/article.aspx?p=2425867) article (under "#10: The empty statement does nothing for me"). It's not too late.

**Comment by SonOfLilit** [comment]
Also, since I care, I'd love to submit a PR if the idea is accepted.

**Comment by lydell** [comment]
I’ve seen _lots_ of CoffeeScript code where `try` without `catch` is used, as well as _lots_ of JavaScript code that uses empty `catch` blocks. People do that. This would be a _massive_ backwards compatible change.

I also don’t understand why beginners would have a hard time because of this. Otherwise they’d likely write `try fn() catch` and get the same problem.

**Comment by SonOfLilit** [comment]
Because this:

```
try
  f()
```

doesn't indicate visually that it catches anything, and in fact looks like it should be identical to this:

```
try
  f()
finally
  # nothing
```

(and could be arrived at by erasing that empty finally block, not thinking you've changed anything semantically)

while this:

```
try
  f()
catch
  # nothing
```

looks like you're explicitly trying to swallow exceptions.

Since the bug would be an omission of code and not introduction of code, it would be extremely hard to spot, especially if you're not familiar with this undocumented behavior (that isn't tested in the language unit test suite either, I checked). A beginner might not have experience isolating bugs to specific lines by bisecting.

For the same reason, a reader not well versed in CoffeeScript might assume the wrong thing when seeing this code and introduce a bug elsewhere because of it.

I haven't seen a lot of CoffeeScript code (I'm doing research to consider adopting it for our startup), so maybe many people do use that shortcut in the rare cases they really want to suppress all exceptions, but isn't it OK to ask them to think once again if they *really* intended to suppress exceptions in that case and it's not just an editing mistake?

Of course, I'm no fan of breaking changes, and if a breaking release is planned anytime soon this should definitely wait for it, but I think this would catch and prevent real bugs and create more explicit and readable code, while only rarely inconveniencing users (because lets face it, you rarely want to suppress all exceptions silently).

And lets at least document it properly, since it's definitely a gotcha that would've gotme.

**Comment by lydell** [comment]
> test it properly

?

**Comment by SonOfLilit** [comment]
The exception handling test suite doesn't test the behavior of `try 1/0`, it only tests that it parses correctly, so according to the test suite it's currently undefined behavior (i.e. CoffeeScriptRedux might have handled it differently. They didn't, though, they did catch a bug in how CoffeScript handled this, which is how I learned about the issue: https://github.com/michaelficarra/CoffeeScriptRedux/pull/197

I'm sorry for barging in the door and making so much noise (my comments seem to be quite long today), please guide me on the culture here and how to become a polite and conforming contributor.

I simply want to choose CoffeeScript for our codebase because it looks like so much more fun, but there's some due diligence to be done that I'd rather make it easier for the next CTO to do. You know what they say, "always leave a codebase better than you found it".

**Comment by DylanPiercey** [comment]
This makes sense to me. There are often cases where you need a try catch and the catch does nothing. It seems like your saying the try keyword should do nothing by itself, however I think it reads perfectly clear that it's going to attempt the operation.

```coffeescript
try data = JSON.parse(x)
# data is undefined if it could not be parsed.
```

**Comment by jashkenas** [comment]
Feel free to add a test for `try x` if you like, but it's an intentional feature that we want to keep.

**Comment by SonOfLilit** [comment]
OK, readind @DylanPiercey's comment I can see how CoffeeScripters use it.

It still scares me (and my coworkers) that you remove behavior from `try` just by adding `finally`, but if you use it this way, this proposal would indeed be a huge breaking change.

I'll submit a PR with documentation and a test.

**Comment by lydell** [comment]
Here is a test that makes sure that errors are ignored: https://github.com/jashkenas/coffeescript/blob/98dd1bf8e80aa7974422a5fdef3075a9e7329d00/test/exception_handling.coffee#L76-L81

Also, `1/0` does not throw in JavaScript.

**Comment by SonOfLilit** [comment]
@lydell seems like I didn't look hard enough, embarrassing. Sorry. I'll still submit a patch to docs.

`1/0` is an old python habit that I recalled incorrectly that works in JS as well.

**Comment by carlsmith** [comment]
I personally don't understand the basic problem. In Python, it's not
uncommon to see code like...

try: return something()
except: pass

It is helpful to have an implicit, null except block.

I don't find it confusing either. What else could a lone try statement do
with an error, but 'silently' pass? An if statement with no else block does
the same thing.

**Comment by carlsmith** [comment]
Sorry. Just learnt not to use email to comment on GitHub Issues.

**Comment by DylanPiercey** [comment]
@carlsmith "try" will capture any exceptions. You can still throw inside an "if".

@SonOfLilit I would avoid finally personally. It is a hack in javascript. If you can't do your finally after the try block you are doing something odd.

I would do some research into the problems of finally. Things like returning inside of a finally can completely ignore previous returns, and its even more confusing with generators and async functions.

**Comment by SonOfLilit** [comment]
@jashkenas, can you go over this diff (of the FAQ) and make sure I didn't write anything you don't agree with? I did the grunt work, but I don't think my opinion is representative of core committers':

https://github.com/jashkenas/coffeescript/wiki/FAQ/_compare/0426ce915445d2fc50b35df0941eb7e194bbd2ac...68c62898f520ede4da1960937494168094c52c1b
