### ISSUE TITLE
declaration inside if statement causes compile error

### ISSUE THREAD

**Issue by santoshjoseph99** [jashkenas/coffeescript#3982]
```` coffeescript
a = (b,c,f1,f2) ->
  return b < c unless f1 and bug = f2
````
compiles in coffeescript 1.9
but fails in 2.0 with the following error:
````
Syntax error on line 3, column 34: unexpected '=' (\u003D)
1 : 
2 : a = (b,c,f1,f2) ->
3 :   return b < c unless f1 and bug = f2
^ :~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
4 : 
````

**Comment by michaelficarra** [comment]
2.0 is not released. Are you using CoffeeScriptRedux? This was [an intentional deviation](https://github.com/michaelficarra/CoffeeScriptRedux/wiki/Intentional-deviations-from-jashkenas-coffee-script#intentional-deviations) because I consider it a bug that would have required substantial effort to reproduce.

**Comment by santoshjoseph99** [comment]
yes, CoffeeScriptRedux is what I'm using.
--version shows: CoffeeScript version 2.0.0-beta7
