### ISSUE TITLE
Can we start using rebase?

### ISSUE THREAD

**Issue by dopatraman** [jashkenas/coffeescript#4025]
I just looked at the commit history and more than half are  "Merged pull request" etc. Maybe we can start rebasing and squashing commits to make the history more readable? Just a thought.

**Comment by lydell** [comment]
When writing this there were 4005 commits and [404 merged pull requests](https://github.com/jashkenas/coffeescript/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Amerged), so there should be about 10% "merge pull request" commits, not >50%.

I think `git log --no-merges` should make the history more readable.

If we want to keep the noise down, though, single-commit PRs could be cherry-picked instead of merged. A possible downside to that is that the PR will be marked as closed rather than merged on github.

**Comment by jashkenas** [comment]
No, we can't. CoffeeScript development at the moment is mostly feature branches that are merged in. That's the truth. No need to hide it.
