### ISSUE TITLE
trace variables

### ISSUE THREAD

**Issue by aplicacionamedida** [jashkenas/coffeescript#4037]
Trace variables: A function is called each time a variable is accessed or geted.

**Comment by vendethiel** [comment]
How do you implement that efficiently anyway?

**Comment by aplicacionamedida** [comment]
I think that the only solution is to declare a variable with this special property: to be traced. Perhaps the traced variable can be registered internally by the compiler and associate its corresponding callbacks in case of being geted or setted. The compiler adds after each access to a variable a call to the associated callback.

**Comment by slang800** [comment]
JS already has [getters](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get) and [setters](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/set), so you could probably use that to do your variable tracing. Or you can track variables using the [Blink DevTools](https://developer.chrome.com/devtools)/[Node Inspector](https://github.com/node-inspector/node-inspector).

Though I think that the idea of making tracing a part of CoffeeScript is pretty far out of scope. It would break the "CoffeeScript is just JS" principle, because tracing is way more than just syntactical sugar for common idioms.

**Comment by GeoffreyBooth** [comment]
Closing as this proposal doesn’t appear to have consensus.
