### ISSUE TITLE
Modifying the AST before compiling

### ISSUE THREAD

**Issue by nickdima** [jashkenas/coffeescript#4077]
Would it be possible with the coffeescript module to modify the AST (for example by wrapping a class with a function) and only then compile to JS?

**Comment by vendethiel** [comment]
you'll probably have to hook the "post-parsing phase" (manually).
An example of the "API" is [here](https://github.com/jashkenas/coffeescript/blob/master/src/command.coffee#L173), but I'm not sure that's intended to be public...

**Comment by nickdima** [comment]
Thanks! Anyone knows any open source examples that play with modifying the CoffeeScript AST?

**Comment by carlsmith** [comment]
I heard that CoffeeScript Redux parses CoffeeScript into an AST, then transforms it into a JavaScript AST, then lets [Escodegen][1] generate the JavaScript source. That's a nice approach, if that's how it works. Further along, any JS parser can turn the JavaScript output by the Coffee Compiler back into an AST too.

There's a project named [Black Coffee][2] that does some clever looking magic with hygienic macros, so that may interest you.

[1]: https://github.com/estools/escodegen
[2]: https://github.com/paiq/blackcoffee

**Comment by nickdima** [comment]
OK, thanks! I'll close this as I now have enough information for what I need to do.
