### ISSUE TITLE
Two variations of default constructors.

### ISSUE THREAD

**Issue by mgenereu** [jashkenas/coffeescript#4115]
I searched the issues and didn't find this specific observation.  For the following CoffeeScript:

``` coffee
class Test1 extends TestBase

class Test2 extends TestBase
  constructor: -> super
```

I get these two constructor functions:

``` javascript
function Test1() {
  return Test1.__super__.constructor.apply(this, arguments);
}
```

``` javascript
function Test2() {
  Test2.__super__.constructor.apply(this, arguments);
}
```

One returns and the other doesn't.  I don't think it matters but if it does, this could be a bug looking for a place to happen.

**Comment by GeoffreyBooth** [comment]
This is no longer an issue in CS2, where we compile to ES `class`.

**Comment by connec** [comment]
Also, for CS1 -

The first one returns because that is the implementation of the default constructor (invoke super and return). This ensures that if the superclass is returning an object, it will get returned through the child class.

The second one has no return because there is an explicit constructor with no explicit return. Constructor functions are the only functions in CoffeeScript that do not use implicit returns.
