### ISSUE TITLE
Unexpected exception

### ISSUE THREAD

**Issue by kika** [jashkenas/coffeescript#4124]
Got this on 1.9.2 and 1.10.0
```>> Got an unexpected exception from the coffee-script compiler. The original exception was: TypeError: Cannot read property 'push' of undefined

> > (The coffee-script compiler should not raise unexpected exceptions. You can file this error as an issue of the coffee-script compiler: https://github.com/jashkenas/coffee-script/issues)```

Unfortunately, I failed to isolate the problem completely. The project is 73 files and 5800 lines. But compiling files one by one I found a syntax error which, when fixed, made the above to go away. Individual compilation didn't cause the above exception though.

the problem was in

``` coffeescript
class XXX extends YYY.zzz
    @staticMethod: () ->
         foo = bar()
    return foo
```

The `return` was outdented one step to the left, to the level of `@staticMethod` and individual compilation returned valid diagnostics `error: Class bodies cannot contain pure statements`

**Comment by GeoffreyBooth** [comment]
This is expected behavior.

**Comment by noAlvaro** [comment]
Hey @GeoffreyBooth , I'm facing a similar issue here... can you help?
```
ERROR in ./index.vr.coffee
Module build failed: Error: Got an unexpected exception from the coffeescript compiler. The original exception was: SyntaxError: unknown: Unexpected token (15:11)
(The coffeescript compiler should not raise *unexpected* exceptions. You can file this error as an issue of the coffeescript compiler: https://github.com/jashkenas/coffee-script/issues)
```
The `coffee` file, however, is quite simple and seems to pass through standard transpilations:
```
import React from 'react'
import {
  AppRegistry
  asset
  Pano
  Text
  View
} from 'react-vr'

export default class WelcomeToVR extends React.Component
  render: -> <View><Pano source={asset 'chess-world.jpg'}/></View>

AppRegistry.registerComponent 'WelcomeToVR', => WelcomeToVR
```
_- Any clues in what is going wrong?_

**Comment by GeoffreyBooth** [comment]
You’re clearly not compiling this using the CoffeeScript compiler; of course the compiler raises exceptions, for example whenever there’s a syntax error. Whoever wrote the wrapper you’re using doesn’t know what they’re talking about.

If you copy/paste your code into http://coffeescript.org/#try and the result isn’t what you think it should be, that’s when you should open an issue here. For general troubleshooting help, a better forum is Stack Overflow; or in your case, perhaps the webpage for whatever tool you’re using that tries to catch “expected” exceptions from the CoffeeScript compiler.

**Comment by noAlvaro** [comment]
Thanks for the quick help!

Yeah... The wrapper that seems to be raising the error is the [Coffeescript Loader](https://github.com/webpack-contrib/coffee-loader/blob/master/index.js#L28) for [Webpack](https://webpack.js.org). I can't really evaluate their work, but the code seem to compile accordingly in [coffeescript.org/#try](http://coffeescript.org/#try).

I wrote here the question because the message seemed quite similar to kika's post. But I posted [it on Stackoverflow](https://stackoverflow.com/questions/48898680/is-it-possible-to-use-coffeescript2-with-reactvrs-welcometovr-scaffolded-proj) anyway.

This is all about using Coffeescript2 with ReactVR's pre-built project, and the setup seemed a little over my current domain. I will post on the loader's page anyhow, but thanks for the help!

**Comment by GeoffreyBooth** [comment]
Make sure that you’re using the latest version of CoffeeScript. That project specifies a peer dependency of 1.8+, so you might not be using 2 or the latest 2.

Also it’s your responsibility to ensure that the JavaScript output by the CoffeeScript 2 compiler can run in the environment you’re trying to run it in, or that you transpile it further first. Since you’re using JSX, which no JavaScript runtime supports, you obviously need to pass through Babel or some other transpiler downstream from CoffeeScript. Webpack or Coffeescript Loader should manage that for you (or hook into the CoffeeScript compiler’s `transpile` option).

**Comment by noAlvaro** [comment]
After installation it came as `"coffeescript": "^2.2.1"`. And I suppose Webpack should be running first, as I run `webpack-dev-server` before anything else on the `"start"` script. So I presume the error is happening yet before babel phase takes over.

The strange thing is that the file seems to pass through Webpack twice, on the building logs:

Firstly with:
- `index.vr.js | 325 kB | 0 | [emitted] | [big] | main`

Then:
- `[2] (... until ...) [24]`.

And thereafter with:
- `[25] | ./index.vr.coffee | 478 bytes | {0} | [built] | [failed] | [1 error]`.


I probably am the error on all this, haha. But I'll win in the and :o)

_Thanks man!_
