### ISSUE TITLE
What about adding language extension to enable different transpile process?

### ISSUE THREAD

**Issue by winterland1989** [jashkenas/coffeescript#4176]
As javascript is continue evolving, we will not get rid of transpiler any more, how about borrowing the idea of language extension from other compilers(ghc comes to mind since haskell is evolving so fast). The idea is to add language extension per-file basis, for example by adding these line at the top of a coffee file:

```
#{ES2015_ARROW_FUNCTION}
```

With this extension on, all arrow functions within this file will be mapped to latest stable es version.
Without this extension, all arrow functions within this file will be transpile lowest common denominator js version(keep current behaviour).

Now users can decide to use a feature or not without other's interference, and since its per-file basis, it won't change original workflow no matter what packing tools you use(webpack...). And we can continue pick the feature we want from es standards, and the judgement on which runtime version to target fall on library's author's shoulder.

Do you think this is a good idea? maybe someone post this before? any feedback are welcome.

**Comment by fa7ad** [comment]
As much as I like this idea (and alternatively a compilation flag), this has been rejected a hundred times :cry:

**Comment by tjad** [comment]
Coffeescript is in a bit of a pickle, and will have to start supporting ES6/7 sooner or later (sooner rather than later). As the standards are set, and more browsers begin to support the standard, inevitably the js development community is going to be writing ES6/7.. This means that all new frameworks or newer versions of frameworks will incorporate ES6/7 and hence it will be difficult to use Coffeescript with those frameworks.

Presently, this is catastrophic, and it only gets worse, as right now everything is still transpiling to ES5 as browsers are not fully stable/supporting ES6+. So there is currently still a mutual point where coffeescript can meet new frameworks. As time progresses, ES6 will be the standard of choice for browsers, meaning that coffeescript will be left for legacy and new frameworks will not be transpiling back to ES5 meaning that coffeescript will not be able to use the new frameworks.

I urge the coffeescript team to think about this carefully.

**Comment by GeoffreyBooth** [comment]
It has been given a lot of thought: http://coffeescript.org/v2/#coffeescript-2
