### ISSUE TITLE
Hate this implicit return statement. Proposal to add returnless function arrow

### ISSUE THREAD

**Issue by yivo** [jashkenas/coffeescript#4210]
Hello guys! Thank you for creating and supporting CoffeeScript!

Often when I want to extract loop to separate method I write like this:
```coffee
performEach = ->
  el.perform() for el in collection
```
But always getting loop which collects returned data from `el.perform()`:
```js
var performEach;

performEach = function() {
  var el, i, len, results;
  results = [];
  for (i = 0, len = collection.length; i < len; i++) {
    el = collection[i];
    results.push(el.perform());
  }
  return results;
};
```
Then I add explicit return statement:
```coffee
performEach = ->
  el.perform() for el in collection; return
```
And getting what I want:
```js
var performEach;

performEach = function() {
  var el, i, len;
  for (i = 0, len = collection.length; i < len; i++) {
    el = collection[i];
    el.perform();
  }
};
```
Proposal! What do you think about returnless arrow? Something like this:
```coffee
performEach = |> # Note new syntax: "|>". Fat arrow syntax: "||>" 
  el.perform() for el in collection
```
Compiles to:
```js
var performEach;

performEach = function() {
  var el, i, len;
  for (i = 0, len = collection.length; i < len; i++) {
    el = collection[i];
    el.perform();
  }
};
```
For many APIs is it important what value was returned (for example it is event handlers in jQuery).  
Also there is article about it http://programmaticallyspeaking.com/why-i-hate-implicit-return-in-coffeescript.html

**Comment by bjmiller** [comment]
This has been asked and rejected more times than I can remember off hand.

In 99% of cases, you either want the last statement of the function to be the return value, or the return value is thrown away and it doesn't matter.

For the remaining 1% of cases, you can type `return` at the end of the function, which is much more explicit about your intent, and less complex than Yet Another Operator.

Can people PLEASE stop asking for this not-a-feature now?

**Comment by loveencounterflow** [comment]
this wouldn't be an issue if CS had `"use strict"`-like per module / per function configuration settings ('pragmas', similar to Python's `from __future__ import`). 

Personally I use `return null` all over the place to prevent my functions from accidentally 'leaking' values. In my experience implicit `return` looks attractive in theory but turns out to be a liability in the majority of cases, the exception typically being simple one-liners. 

I'd be totally OK with an explicit syntax for implicit returns (say, `cube = ( x ) <-> x ** 3`), but removing implicit `return` in the absence of 'pragmas' will break backwards compatibility in ways that nobody will support.

**Comment by carlsmith** [comment]
I always use explicit returns unless it's a single expression these days, and would have personally preferred that syntax, but I still don't think it's worth changing CoffeeScript by adding modes at this stage. There's a lot of good ideas for how CoffeeScript could have been improved, but they should just influence new languages.
