### ISSUE TITLE
What's holding up async/await functionality?

### ISSUE THREAD

**Issue by taoeffect** [jashkenas/coffeescript#4228]
After diving head first into ES6 I am wanting to return to CoffeeScript land. The lack of `async/await` support holds me back though, so am wondering what's holding it up?

EDIT: Deleted a bunch of unnecessary text after seeing the open PRs: #3813 #3757

Still not clear to me what's holding up the keywords. I saw the proposal for `!`, but that can always be added later on.

**Comment by taoeffect** [comment]
Also noticed there are two open pull requests: #3813 #3757

So… what's the holdup?

**Comment by brandon-fryslie** [comment]
Additionally, are there any candidates for a CoffeeScript replacement that will be responsive with keeping up with modern JavaScript features?  There is no roadmap for bringing CoffeeScript up to date so it keeps falling farther and farther behind.  At some point there will need to be a fork so we aren't stuck with legacy CoffeeScript which, due to lack of support for modern JavaScript features, is only suitable for small personal projects.

It's a great language, my personal favorite, but the point at which people are "moving on" has passed.  People have moved on, and we need to start looking for a replacement that will keep up to date with modern web development.

**Comment by GabrielRatener** [comment]
Check out #3757, #3813

**Comment by carlsmith** [comment]
I really think we should wait for async to be standardised, then implement it the same way as we do with generators - just compiling to JS async code, not using a shim.

Discuss: https://github.com/coffeescript6/discuss

**Comment by zeekay** [comment]
Sounds like it's reached stage 4 status: https://github.com/tc39/proposals/blob/master/finished-proposals.md

**Comment by GeoffreyBooth** [comment]
Closed via #3757.
