### ISSUE TITLE
[CS2] Replace ‘var’ with ‘let’ everywhere (boost x2)

### ISSUE THREAD

**Issue by Snowshield** [jashkenas/coffeescript#4255]
I made some interesting performance tests. [One of them](http://coffeescript.org/#try:class%20A%0A%20%20fn%20%20%20%3A%20-%3E%0A%20%20%20%20i%20%3D%20j%20%3D%200%3B%20num%20%3D%2010000%0A%20%20%20%20while%20i%3Cnum%0A%20%20%20%20%20%20while%20j%3Cnum%0A%20%20%20%20%20%20%20%201%20%2B%201%0A%20%20%20%20%20%20%20%20%2B%2Bj%0A%20%20%20%20%20%20%2B%2Bi%0A%20%20%20%20undefined%0A%20%20test%20%3A%20-%3E%20%0A%20%20%20%20do%20%3D%3E%20%40fn%28%29%0A%20%20%20%20undefined%0Aa%20%3D%20new%20A%0A%23%0At1%20%3D%20performance.now%28%29%0Aa.test%28%29%0At2%20%3D%20performance.now%28%29%0A%0Adelta%20%3D%20%28t2%20-%20t1%29.toFixed%203%0Aconsole.log%20%22%23%7Bdelta%7D%20ms%22).
**Calculation time : 0.570 ms.**
I made same test in Babel and it was **2x time faster**.
I found bottleneck. I just [replaced](https://jsfiddle.net/b544f3p8/2/) `var` with `let` and got **calculation time : 0.235 ms.**
As you see i get 2x speed boost only by replacing `var` with `let`.

_Main problem_: 'let' is not supported by old browsers.
_Solution_: you can make this optional with compiler flag.

So can u make compile option to put `let` everywhere instead of `var` ?

**Comment by vendethiel** [comment]
We don't really do "compilation flags that change the generated code"... Yet. An ES6 mode has been proposed a few times, btmut I can't search for them on mobile...

**Comment by shakvaal** [comment]
It's understandable that you are under impression of numbers, but think of what you really suggest:  `var` and `let` have slightly different behavior, so simply changing one for another would lead to numerous bugs and break everything.

**Comment by Snowshield** [comment]
> var and let have slightly different behavior, so simply changing one for another would lead to numerous bugs and break everything.

Could you explain it more detail in context of **coffeescript** usage?
As i know in coffeescript all of variable declarations are pushed up to the top of the closest scope so difference should be minimal.

**Comment by vendethiel** [comment]
It's not in the case of for loops.

**Comment by connec** [comment]
It looks like CS already hoists variable declarations in loops.

```coffee
for a in b
  c = 1
# var a, c, i, len;
#
# for (i = 0, len = b.length; i < len; i++) {
#   a = b[i];
#   c = 1;
# }
```

**Comment by trylks** [comment]
This is not my field of expertise, but I would like to point one little thing. If an improvement for this is devised, perhaps `const` could be considered along with `let`. I have not made any numbers, but JavaScript interpreters should be much faster with `const`, in the future if not in the present.

In theory, since the scope of the variables is limited, it should be feasible to check statically if they are assigned once or more than once, to automatically specify `const` where possible (no changes to CoffeeScript syntax). I know that Eclipse has an option to automatically add `final` where possible. Something similar might be possible here.

I do not want to derail the current discussion. Should I open a new issue?

**Comment by Snowshield** [comment]
> I do not want to derail the current discussion. Should I open a new issue?

If I have correctly understood your theory is not based on v8 sources nor performance tests.
Also _automatically specifing_ `const` _where possible_ does not sound as easy to implement as `var` to `let` swap.
So probably yes, you should create new issue.

**Comment by Inve1951** [comment]
replacing all `var` to `let` seems to only not work on the repl and _could_ be implemented on the `2` branch.
[cs6/discuss#35](https://github.com/coffeescript6/discuss/issues/35#issuecomment-247795663)

@GeoffreyBooth, this proposal might interest you

**Comment by GeoffreyBooth** [comment]
I’m sure we could fix the REPL to work with `let`. I just updated the [`let` branch](https://github.com/GeoffreyBooth/coffeescript/tree/let) I mentioned in [my comment](https://github.com/coffeescript6/discuss/issues/35#issuecomment-247795663) that you linked to, with the latest updates from the `2` branch; now it has several more failing tests. So there’s more work to be done than just fixing the REPL, but it’s probably not too drastic.

@Inve1951, perhaps you’d like to take on the task of getting the `let` branch to pass all the tests? And then if there really is a measurable performance boost in real-world use cases, it’s probably worth doing. Since Node supports `let` natively, and plenty of CoffeeScript is intended for a server-side Node environment, there could be real benefits for that use case.

**Comment by GeoffreyBooth** [comment]
This was thoroughly discussed in https://github.com/coffeescript6/discuss/issues/35 and https://github.com/coffeescript6/discuss/issues/58. The findings:

- Modern JavaScript runtimes already optimize things such that there shouldn’t be a noticeable performance benefit between `var`, `let` and `const` in real-world code.
- Simply replacing `var` where it appears now with `let` in the same places, to create a “function-scoped `let`” like in my experimental [`let` branch](https://github.com/GeoffreyBooth/coffeescript/tree/let), should offer zero performance benefits. The benefit would come if the declarations were made more narrowly, at the block level, not at the function level where our `var` declarations are now.
- One of CoffeeScript’s goals is outputting human-readable, sensible code. Outputting this “function-scoped `let`“ violates that principle. `let` implies that the variable it’s declaring is a block-scoped variable. Function-scoped variables should be declared with `var`. That’s what `var` is for.

Based on the last point, I think function-scoped variables will always be declared with `var` for the foreseeable future. If CoffeeScript ever adds support for block-scoped variables (and based on https://github.com/coffeescript6/discuss/issues/58 it looks unlikely), that’s when `let` would be used.
