### ISSUE TITLE
curly bracked export causes that variable to be declared to the global scope

### ISSUE THREAD

**Issue by bdirito** [jashkenas/coffeescript#4394]
```
x = 1
export { x }
````
-> 
```
x = 1;
export {
x
};
```
Current workarounds include doing the variable in escaped javascript or function scoping x. Note that if you function scope x you break es6 spec as export must be at the outer most level (though babel at least has options to ignore the spec).

**Comment by Kovensky** [comment]
Happens regardless of the relative position of the `export` in relation to the variable: http://coffeescript.org/#try:export%20%7B%20foo%20%7D%0Afoo%20%3D%20'foo'

Also affects `class`.

However, this does not affect *renamed* exports as long as the rename target is different: http://coffeescript.org/#try:export%20%7B%20foo%20as%20bar%20%7D%0Afoo%20%3D%20'bar'

Probably a separate bug, but the generated code for `export default class` is not correct, at least if coffeescript `class` is supposed to have the same semantics as a function.

Because coffeescript creates classes in an IIFE and returns their result, `export default class Foo` does not retain live binding, so coffeescript should generate `export { Foo as default }` instead. Fortunately, as the `Foo` binding is renamed (to `default`) in this example, the `export default class` bug can be worked around without hitting this bug.

**Comment by connec** [comment]
@Kovensky can you elaborate on the issue with `export default class`? I'm not familiar with the term 'live binding', but there is certainly no copying going on - the function reference is returned from the IIFE, and furthermore assigned to the identifier for the class, which is what is being exported.

The original issue is an interesting bug. I'm not intimately familiar with the module compilation in CS, but perhaps @GeoffreyBooth can weigh in?

**Comment by Kovensky** [comment]
@connec this example uses Javascript but, in the following code, the default export, observed from outside, should be `null` instead of `class Foo`:

```js
export default class Foo {}
Foo = null
```

"live binding" is a bit complicated to explain, but it might be easier to understand by thinking on how to actually implement it in plain JavaScript. Named exports are easier to explain as they don't have special cases:

```js
export let foo
// is actually implemented in e.g. babel by doing
Object.defineProperty(exports, 'foo', { enumerable: true, get () { return foo; } })
```

Default export of a named function or named class has a similar pattern, only the export is named `default`. However, a default export of an anonymous function, anonymous class, or arbitrary expression, actually works as if you had done:

```js
const $secret$default = (...expression)
export { $secret$default as default }
```

Since the value is saved into a "secret" variable, and you can only observe it through (effectively) a getter, it's not possible to change the value, and thus you don't have live binding. But, for everything else, updating the value of the binding also updates the exports as seen by other modules.

As coffeescript generated code looks like this to the ES6 modules implementation:

```js
var Foo
export default Foo = (function() { return function Foo() {} })()
```

it is treated as the default export of an expression, and not a `class`, so it saves the value of `Foo` to the "`$secret$default`" (this is, by the way, why you can't have `var` / `let` / `const` after `export default`). In order to preserve the "live updateability" that an ES6 `export default function Foo() {}` would have had, the export needs to be emitted as `export { Foo as default }`.

**Comment by connec** [comment]
OK, that's something I did not know, thanks!

Having [checked this out in babel], it seems to behave as you say for named exports, but default exports seem to be bound in that way only if they're hoisted functions, but from [the spec](http://www.ecma-international.org/ecma-262/6.0/#sec-exports-static-semantics-exportentries) this seems like a bug in babel.

Anyway, I'd maybe open another ticket about this since it's a bit more subtle than the original issue posted, and we'll probably have to consider whether or not it's compatible with CS' scoping rules (e.g. having a single type of assignment is regarded as a feature of CS, and a `class` declaration does not comply with those rules).

[checked this out in babel]: https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015&code=export%20default%20function%20Foo%20()%20%7B%7D%0Aexport%20%7B%20Foo%20%7D%0AFoo%20%3D%20null%0A%0A%2F%2Fexport%20default%20class%20Bar%20%7B%7D%0A%2F%2Fexport%20%7B%20Bar%20%7D%0A%2F%2FBar%20%3D%20null%0A%0A%2F%2Fvar%20Baz%20%3D%201%0A%2F%2Fexport%20default%20Baz%0A%2F%2Fexport%20%7B%20Baz%20%7D%0A%2F%2FBaz%20%3D%20null

**Comment by senritsu** [comment]
Is this issue being worked on, or is there a workaround instead of reverting to CommonJS exports?
