### ISSUE TITLE
[CS2] Optimize `do (...args) ->` blocks to use `let`

### ISSUE THREAD

**Issue by isiahmeadows** [jashkenas/coffeescript#4514]
Blocks with `let` implicitly create closures, so you could optimize non-global `do` blocks to use `let` rather than IIFEs to generate smaller, cleaner code.

**Comment by connec** [comment]
@isiahmeadows do you have some example current vs. desirable output?

**Comment by vendethiel** [comment]
We need to make sure `do (i)` still works the same.

**Comment by isiahmeadows** [comment]
@vendethiel That was implied. I was just referring to `do (i) -> ...`

**Comment by GeoffreyBooth** [comment]
Can you please provide examples?

**Comment by isiahmeadows** [comment]
Here's an example:

```coffee
# CoffeeScript
res = do (i = 0) ->
    while i < len
        i += 1 if someCondition((s) -> i < s)
        i += 1
    i
```

```js
// Current JS
var res;
res = (function (i) {
    while (i < len) {
        if (someCondition(function (s) { return i < s })) i += 1;
        i += 1;
    }
    return i;
})(0);

// Proposed JS
var res;
{
    let i = 0;
    while (i < len) {
        if (someCondition(function (s) { return i < s })) i += 1;
        i += 1;
    }
    res = i;
}
```

(I know the ability to expand functions like that exists, because of how `if`/`else` and `for` already expand similarly and recursively in non-returning locations).

**Comment by GeoffreyBooth** [comment]
Basically this is a refactor of `do` that drops the function scope, and uses block scope instead with variables declared by `let` to achieve the same effect. Sure, I guess. It’s more idiomatic ES, I suppose, but it’s not like the current JS is so unreadable.

If you’d like to implement this as a PR I suppose it would be an improvement. I’m not going to keep the issue open though because I don’t think this is something the maintainers would prioritize for one of us to tackle; though if you want to give it a shot, by all means please submit a PR.

**Comment by connec** [comment]
I think this is pretty interesting, especially in the context of #2518.

Something to consider though is that `do` can also be used for function application:

```coffee
something = -> alert 'woah'
do something
```
