### ISSUE TITLE
[CS2] Adjust trailing triple dot array access

### ISSUE THREAD

**Issue by shreeve** [jashkenas/coffeescript#4537]
See the example for `f` and `g` below. Could we adjust so that trailing triple dot array access doesn't include the last element?

```coffee
a = [0,1,2,3]

b = a[0..-1 ] # a.slice(0)
c = a[0...-1] # a.slice(0, -1)

d = a[0..   ] # a.slice(0) shortcut
e = a[..    ] # a.slice(0) shortcut

f = a[0...  ] # a.slice(0) => can we change to a.slice(0, -1) ?
g = a[...   ] # a.slice(0) => can we change to a.slice(0, -1) ?
```

**Comment by GeoffreyBooth** [comment]
This would be a breaking change, would it not? What would justify this? 

Just because we can make breaking changes in 2 doesn't mean we should. We're not trying to fix all the inconsistencies or poor design decisions of the language.

**Comment by shreeve** [comment]
Sounds fine, just noticed the inconsistency and wanted to submit it for review.

**Comment by GeoffreyBooth** [comment]
I don’t see the inconsistency. (Not to say that there isn’t one, just please explain it.)

**Comment by connec** [comment]
I think the idea is that `a..b` (two dots) is generally inclusive of `b`, whereas `a...b` (three dots) is generally exclusive of `b`.

The argued inconsistency is that if `a..` (two dots) is treated as 'up to and including the last element', `a...` (three dots) should be treated as 'up to and excluding the last element'.

Put differently, since `list[a..] == list[a..-1]`, then shouldn't `list[a...] == list[a...-1]`? (Obviously `==` won't actually work here due to object identity.)

**Comment by connec** [comment]
I think the idea is that `a..b` (two dots) is generally inclusive of `b`, whereas `a...b` (three dots) is generally exclusive of `b`.

The argued inconsistency is that if `a..` (two dots) is treated as 'up to and including the last element', `a...` (three dots) should be treated as 'up to and excluding the last element'.

Put differently, since `list[a..] == list[a..-1]`, then shouldn't `list[a...] == list[a...-1]`? (Obviously `==` won't actually work here due to object identity.)

**Comment by lydell** [comment]
The question is: Is this consistency useful enough in practice to motivate a breaking change that may cause very subtle bugs?

**Comment by connec** [comment]
I don't think so. If I was to make here it'd probably be to remove `a..` *and* `a...`, and just use `a..-1` instead if that's what's desired. But that's probably also not a worthwhile breaking change.

**Comment by GeoffreyBooth** [comment]
Closing as consensus appears to be that no action should be taken.
