### ISSUE TITLE
How to Add/Modify CoffeeScript AST and write result to coffescript file

### ISSUE THREAD

**Issue by minostro** [jashkenas/coffeescript#4556]
Hey folks,

I would like to perform some changes in all the CoffeeScript files that are defined in a couple of repos that I have. I saw that I can get a hold of the AST by doing the following

```coffescript
coffeescript = require 'cofffe-script'
ast = coffee.nodes("my-file.coffescript")
```

Is there a way to write the AST back to a coffescript file?

**Comment by GeoffreyBooth** [comment]
As in, generate CoffeeScript code from a set of AST nodes? Not using just the CoffeeScript module itself. The `coffeescript` module just takes Coffee input and generates JS output.

The https://github.com/js2coffee/js2coffee module takes JavaScript and converts it into CoffeeScript, so I guess you could use `coffeescript` to generate JavaScript which you then pass through `js2coffee` to get CoffeeScript back. This wouldn’t be as pointless as it sounds, as such a roundabout would at least clean up style (standardizing whitespace and so on). If you fork `js2coffee` you might find a way to give it an input of AST nodes rather than a JavaScript string.

**Comment by minostro** [comment]
@GeoffreyBooth Thanks! I'll give it a try

**Comment by lydell** [comment]
Somewhat related is that CoffeeScriptRedux was very ambitious and included a CoffeeScript code generator; see https://github.com/michaelficarra/cscodegen

**Comment by minostro** [comment]
@lydell I'll ask them, thanks!

**Comment by jashkenas** [comment]
> Is there a way to write the AST back to a coffescript file?

You sure can! To quote the comment on that method:

```coffeescript
# Parse a string of CoffeeScript code or an array of lexed tokens, and
# return the AST. You can then compile it by calling `.compile()` on the root,
# or traverse it by using `.traverseChildren()` with a callback.
```

So, you can then use `traverseChildren`, passing in a function, to walk the whole AST, modifying if you like as you go ... and then call `.compile` on the root node to get the resulting JavaScript back as a string.

**Comment by minostro** [comment]
@jashkenas np 👍
