### ISSUE TITLE
Coffescript version is still showing older version

### ISSUE THREAD

**Issue by Sibiraj-S** [jashkenas/coffeescript#4582]
I tried updating CoffeeScript to 1.12.6. currently, I have 1.10.

I tried installing with `npm i -g coffeescript` and `brew install coffeescript`. 

In both installations, the download happens correctly. both downloads `1.12` version but when I give `coffee -v`. I always get `CoffeeScript version 1.10.0`. not the latest version

**Comment by lydell** [comment]
You have most likely installed CoffeeScript in more than one way. Your attempts updating succeeds, but there's still a CoffeeScript 1.10.0 lying around somewhere, and it is that one that gets called when you type `coffee -v`.

What you need to do is:

- Check your `$PATH`.
- Check which coffee actually is called. `which coffee` might give you clues.
- Figure out how you'd like to change things.

I'm closing this since I'm pretty confident there's nothing wrong on CoffeeScript's side, but feel free to ask more questions in this issue if needed!

**Comment by Sibiraj-S** [comment]
@lydell . The problem is with npm I guess.

**Comment by GeoffreyBooth** [comment]
Also `coffee` first looks at the current folder to see if there’s a locally installed version of CoffeeScript there. So if you project has CoffeeScript 1.10 installed, and you’re in your project’s folder, `coffee -v` will show your project’s local CoffeeScript 1.10 version rather than the global version.

**Comment by Sibiraj-S** [comment]
Oh that I didn't know. Thanks for the info @GeoffreyBooth

**Comment by lydell** [comment]
@GeoffreyBooth Sorry, I had completely forgotten about that. Thanks for reminding.
