### ISSUE TITLE
Instance methods with `=>` does not works properly if constructor were overwritten in class which extends

### ISSUE THREAD

**Issue by extempl** [jashkenas/coffeescript#4613]
```coffee
class A

  r: () ->
    console.log this

  t: () =>
    console.log this


class B extends A
  constructor: ->


b = new B

$('body').click(b.t).click() # this here is incorrect and equals to body el.
```

This happens because `this.t = bind(this.t, this);` from `A` class is not present in `B` class. 
So it should be added there if constructor were overwritten.

**Comment by GeoffreyBooth** [comment]
What version of CoffeeScript are you using?

**Comment by extempl** [comment]
@GeoffreyBooth  I am using 1.9.3 
But this is also applies to `Try Coffeescript` section on the site, I assume there is the latest version.

**Comment by GeoffreyBooth** [comment]
We’re nearing release of [CoffeeScript 2](http://coffeescript.org/v2/), and as such, we’re not addressing 1.x bugs that don’t also affect 2. In CS2 classes compile to the ES `class` keyword, so classes in general are implemented very differently.

You can try using CoffeeScript 2-beta, it may resolve your issue: `npm install coffeescript@next`.

**Comment by alexkravets** [comment]
@GeoffreyBooth is there any information about when `2` is out of beta?

**Comment by GeoffreyBooth** [comment]
When it’s ready.

**Comment by connec** [comment]
@extempl Unfortunately, what you're describing is the expected behaviour of `=>` in 1.x: bound methods are bound in the constructor. If the constructor is never called the methods are never bound. Adding any kind of warning for this would be a backwards compatibility break, which as @GeoffreyBooth says we want to avoid any more of in 1.x.

The issue you describe can't happen in 2.x as ES2015 mandates that `super` is called in derived classes.
