### ISSUE TITLE
[CS2] Arrow function syntax

### ISSUE THREAD

**Issue by fa7ad** [jashkenas/coffeescript#4635]
Just wondering why this isn't the same as ES6.
Isn't it preferable to be as close to js canon as you can?

![screenshot from 2017-08-07 23 28 38](https://user-images.githubusercontent.com/7447677/29038215-b22f6284-7bc8-11e7-8d49-4583775907ef.png)

The stuff on the right works (node), but the line on the left doesn't.

**Comment by GeoffreyBooth** [comment]
Because in CoffeeScript parentheses are optional, and therefore your example is getting parsed as `text` calling a function, where the arrow function is the argument passed into `text`. See http://coffeescript.org/v2/#try:con%20%3D%20text%20%3D%3E%20console.log%20text

Parentheses are required around function parameters in CoffeeScript. That’s just part of the syntax: http://coffeescript.org/v2/#try:con%20%3D%20(text)%20%3D%3E%20console.log%20text
