### ISSUE TITLE
[CS2] Proposal: compile CSX into React.createElement for running on NodeJS without Babel

### ISSUE THREAD

**Issue by jaredp** [jashkenas/coffeescript#4687]
There's no clear way to run coffeescript with CSX/JSX syntax mixed in the file in nodejs.  The most obvious way would be to run a Coffeescript compile pass then a Babel compile pass.  Two compile passes (and possibly no sourcemaps) before being able to run code would be an uncomfortable development environment.

https://github.com/jashkenas/coffeescript/blob/2/src/nodes.coffee#L1120 is already getting CSX nodes as `Call`s.  If it emitted them as calls to `React.createElement`, we wouldn't need babel.  Then we could happily run the `coffee` command on `.coffee` files with CSX syntax on them.

**Comment by GeoffreyBooth** [comment]
See http://coffeescript.org/v2/#es2015plus-output. The intent is that you pipe the CoffeeScript compiler’s output through Babel, in your case with the JSX transform.

JSX is not React-specific. Vue.js also supports JSX, and sooner or later there will be others. We don’t want to bake references to React into the compiler. We could create some complicated system where you pass a function into the compiler so it knows to output `React.createElement`, but that would probably be more convoluted than just asking you to use Babel, especially since most people will want to use Babel anyway (if they’re using modules, for example).

See the CSX pull request and search the issues for CSX / CJSX / JSX to read the history.
