### ISSUE TITLE
Remove dependency on babel-core@6.x

### ISSUE THREAD

**Issue by loganfsmyth** [jashkenas/coffeescript#4703]
Filing because I want to make sure it gets seen. From https://github.com/jashkenas/coffeescript/pull/4697/files#r139525428

`2.x` has `babel-core@6.x` as an `optionalDependency`, but since those are auto-installed, and there's never a time where `babel-core` should fail to install, it's essentially been made a direct dependency.

Since the logic to load it is already behind  a`try/catch` with a notice to install it, it seems like the `optionalDependencies` block should just be removed. This also opens up users to the possibility of using Babel 7.x in the future, since that will be released in the coming months. As it is now, it'll be a breaking change for `coffeescript@2` to change it to `babel-core@7.x` which would be extremely unfortunate.

**Comment by jashkenas** [comment]
Yes, we should definitely not be installing Babel with CoffeeScript by default. Let's take it out ASAP, and push a 2.0.1 soon.

**Comment by jashkenas** [comment]
Just looking at the file sizes, it's currently adding an 80 megabyte `node_modules` folder to an install that would otherwise be only 500k of JS.

**Comment by GeoffreyBooth** [comment]
Sorry, I thought that `optionalDependency` didn’t install by default. Yeah, if things still work without Babel needing to be in there (i.e. the error message still comes up, without Node crashing on resolving the `require` or something like that) then sure let’s remove it.

The other issue is when CoffeeScript is installed globally, which is the use case when people really would want to use `--transpile`. For `--transpile` to work without it being a dependency, `babel-core` would also need to be installed globally (?) but the Babel docs discourage global installs.

**Comment by jashkenas** [comment]
I think leaving them parallel is probably the right way to go. If you install a global CoffeeScript, you can install a global Babel. And if you install a local CoffeeScript, you can install a local Babel too.

Before pushing, I just tried the tests with just a global babel, and they transpile just fine.

**Comment by loganfsmyth** [comment]
That's an interesting case. I can elaborate on the reasoning behind recommending against global installs. The main thing is that `.babelrc` files are generally tied to specific versions of Babel. Plugins for 7.x may not work for 6.x, and the other way around, so users need to have the right version of `babel-core`.

Perhaps instead of resolving `babel-core` relative to the `coffeescript` package, users could be instructed to install it relative to the files being compiled, and coffeescript could use [`resolve`](https://www.npmjs.com/package/resolve) to find it there, with a fallback to checking globally?

**Comment by GeoffreyBooth** [comment]
The thing is, we _also_ prefer CoffeeScript to be installed per project, though the docs could be clearer about this. Running the `coffee` command will first look to see if you have CoffeeScript installed locally, and then fallback to a globally-installed version.

So I think the way it would work is this:
- For a user with a `script.coffee` file in a folder, and nothing else in that folder, and you want to run `coffee --transpile script.coffee` using a globally-installed CoffeeScript: you need to drop a `.babelrc` in that folder or any parent/grandparent/etc. folder, and you need to have `babel-core` installed globally. So for dev ops folks using CoffeeScript like Bash shell scripts, they can have a `$HOME/.babelrc` and scripts like `$HOME/dev/something.coffee`. They would be fixed to a particular version of Babel, like they’re already fixed to a particular version of CoffeeScript, and that’s fine.
- If they want a different version of Babel (or CoffeeScript) they just need to install one or the other locally in their project. With both installed locally, everything is straightforward and will work the same way 2.0.0 works.
- If they want to use some mix, like global CoffeeScript but local Babel, I don’t know how resolution would work, or what combinations we should support. Can global CoffeeScript `require` local Babel? If not, I think we don’t care to make it so—just throw an error saying to install both CoffeeScript and Babel locally. (I’m assuming @loganfsmyth you wouldn’t want the error to recommend installing Babel globally?) Local CoffeeScript should be able to require global Babel, but that’s also not a recommended combination (?) so it should get the same error, or I guess it’ll just work because there’s no way CoffeeScript would know if the Babel it’s requiring is local or global.

In any event, this needs more thorough testing before we push a 2.0.1.

**Comment by loganfsmyth** [comment]
> Can global CoffeeScript require local Babel?

Not unless you implemented that yourself using the `resolve` package I linked. It does certainly add complexity on both the implementation side _and_ user understanding side, so it's really your call. I don't have strong feelings about supporting that.

> I’m assuming @loganfsmyth you wouldn’t want the error to recommend installing Babel globally

I don't feel strongly. Maybe if that route ends up being taken, just make it clear that the version will be harder to manager?

> Local CoffeeScript should be able to require global Babel, but that’s also not a recommended combination

Does that work? I'd have to go check, but I was under the impression that node didn't try to resolve packages from the global packages unless the thing doing the resolution was also global.

Thanks again for responding to all this, I'm sure it's the last thing you wanted to do after being excited to get 2.0.0 out the door.

**Comment by jashkenas** [comment]
We actually don't prefer CoffeeScript to be installed per-project, and never have. It's meant to be a system-wide, generally compatible tool that you only need to install once, and then can use where-ever you like. Like `node`, like `ruby`, like `python`.

The docs have always recommended `--global` for the install.

Of course, if you want to install it locally, and use `./bin/coffee`, that's cool too.

**Comment by GeoffreyBooth** [comment]
@jashkenas See #4543 and #4049. Back in 1.12.6 we removed the `preferGlobal` flag, and updated the `coffee` and `cake` commands to first look for CoffeeScript installed in the current folder (and if found, run that version) before running the globally-installed version. The idea was that now that there’s 2.x out, older projects may very well need 1.x (if they can’t upgrade easily, for example) and for them you would install 1.x locally; but keep 2.x/latest installed globally.

In general though, other Node command-line tools like Babel and Gulp and Webpack all recommend installing locally. For CoffeeScript 2, which almost demands to be part of a build chain (i.e. chaining to Babel via Gulp or Webpack, or letting CoffeeScript manage the chaining via `transpile`) it probably makes sense to follow their lead. Otherwise we end up with exactly this “user error” issue: we tell people to install CoffeeScript globally, but then they install Babel or Gulp locally, and `--transpile` doesn’t work. If anything we should flip the question around: why _shouldn’t_ we recommend installing locally?

As far as I can tell the only advantage to installing globally is that you can then run CoffeeScript via just `coffee`, rather than `./node_modules/coffeescript/bin/coffee`. But we could just as easily advise people to install CoffeeScript both ways, and get the best of both worlds:

```bash
# Install CoffeeScript globally, to get quick access to the `coffee` command
npm install --global coffeescript

# Install CoffeeScript in your project, to integrate with build chains
npm install --save-dev --no-optional coffeescript
```

Having Babel installed as a dependency of the globally-installed CoffeeScript would solve the problem of getting `--transpile` to work with global `coffee`; and recommending people install locally via `--save-dev --no-optional` avoids the large-download issue. And if someone doesn’t read the docs and leaves out `--no-optional`, eh, so what, they get Babel installed as well. It’s not the end of the world. I’ve never heard of people complaining that an NPM module had too many dependencies (though maybe @loganfsmyth has, because Babel has a helluva lot of dependencies!).

So simply updating the docs with the above (and loosening the version bounds of the `babel-core` optional dependency) would be the easiest solution. Before I get into the other options, how does everyone feel about this?

One question that maybe someone knows the answer to: is it possible to somehow install a dependency _only_ when installing globally? Like maybe installing `coffeescript` globally could trigger installing the `babel-core` dependency, but installing locally would not (without the user needing to know to use `--no-optional`)?

**Comment by GeoffreyBooth** [comment]
> Does that work? I’d have to go check, but I was under the impression that node didn’t try to resolve packages from the global packages unless the thing doing the resolution was also global.

Actually, yes, it can:

```bash
# No globally-installed CoffeeScript
npm uninstall --global coffeescript coffee-script

# Install Babel globally
npm install --global babel-core babel-preset-env

cd /tmp
mkdir test
cd test

npm install --save-dev --no-optional coffeescript
# + coffeescript@2.0.0
# added 1 package in 0.966s

echo '{ "presets": ["env"] }' > .babelrc

./node_modules/.bin/coffee --transpile --eval \
  'import path from "path"; console.log path.sep'
# /

**Comment by lydell** [comment]
> We actually don't prefer CoffeeScript to be installed per-project, and never have.

Huh? I never noticed. Do people really install CoffeeScript globally? I never have. But I may also be the odd one out.

**Comment by GeoffreyBooth** [comment]
> Do people really install CoffeeScript globally?

I only have for testing/dev purposes. But one thing I learned when reading through all our old issues a few months ago, is that there are a lot of users of the `coffee` command in the DevOps world, where `.coffee` files can be more powerful cousins of trusty Bash shell scripts. Just look at all the old issues of people trying to do wacky things like use `child_process` inside a script run via `coffee`, and so on. Those users don’t have “projects” per se, they just have `.coffee` script files that kinda just live on their own. Hence the `~/.babelrc` suggestion above.

**Comment by jashkenas** [comment]
Ideally, CoffeeScript should have no dependencies — and with the reversion to plain markdown inversion, we're back again to that point.

Let's keep `babel-core` out of the `optionalDependencies` (leaving it in devDependencies), and document that you need to install it in http://coffeescript.org/#transpilation, as we do, as we also do in the error.

After that, I like your dual installation recommendation for http://coffeescript.org/#installation — where it looks like it's already in the proper form:

```bash
# Global:
npm install --global coffeescript

# Local:
npm install --save-dev coffeescript
```

**Comment by shreeve** [comment]
> Do people really install CoffeeScript globally?

I definitely do. It's productive, clean, and enjoyable to use, so I find myself using CoffeeScript for many different utility scripts and tools.

**Comment by lydell** [comment]
@shreeve Just out of curiosity, how have you handled breaking changes (such as when the bug `constructor: (@foo) -> foo` bug was fixed, only allowing the correct `constructor: (@foo) -> @foo`)? Upgraded all your projects at once?

**Comment by shreeve** [comment]
@lydell Yes, I just fixed everything at once. It was pretty quick.

**Comment by GeoffreyBooth** [comment]
@jashkenas The issue with telling people to install it is that we'll need to clarify that they need to install it globally if CoffeeScript is being run globally; is there some way that we can detect if we're being run as the local or global copy? Or the error could just be verbose, saying something like “if you’re running globally, install Babel globally” etc. but that's probably going to be confusing for users.

I think ideally we would automatically install Babel as a dependency for global installs and not for local installs. Is that possible? The merit of this approach is that if Babel is a dependency of CoffeeScript at the global level, it can't interfere with other projects that might be trying to require Babel. 

Failing that, sure, we remove it from both and beef up our error messages and docs.

**Comment by jashkenas** [comment]
No -- we really shouldn't be installing it as a dependency under any circumstance. The issue of which Babel to install is one that's more germane to your project, not to the version of the CoffeeScript compiler. Our interface with Babel is minimal: we just want to send it standards-compliant JS.

Ideally, any local/global combination of CoffeeScript would work with any local/global version of Babel. Since local can already `require` local or global Babels, it's really just a matter of making global CoffeeScript able to require a local Babel, if you want.

That could be something as clunky as `coffee --transpile=path/to/transpiler`, or we could have `coffee --transpile` look for the transpiler in the directory hierarchy around the `filename`, a-la Node.

And then going a little bit further — although the Babel integration is a lovely first step forward, it would really be great if `--transpile` supported whichever transpiler you want to use — again, the interface is just standards-compliant JavaScript. You can imagine `--transpile bublé`, `--transpile traceur` or `--transpile esnext` in addition to `--transpile babel`.

**Comment by GeoffreyBooth** [comment]
A globally-installed package can’t require a locally-installed one, only the other way around. That’s why @loganfsmyth was suggesting [resolve](https://www.npmjs.com/package/resolve) up above, which is a package that enables global requiring local. But then we’re adding a dependency.

So how about this:

1. We remove `babel-core` from `optionalDependencies` (done).
1. If it’s possible for CoffeeScript to determine whether it is being run globally vs locally, and `babel-core` is missing, the error message says to install globally or locally as appropriate.
1. Otherwise, the error message says something along the lines of “if you’re running globally-installed CoffeeScript, install `babel-core` globally; otherwise install `babel-core` locally.”
1. We update the docs accordingly, explaining that global `babel-core` is needed if one wants to use `transpile` with globally-installed CoffeeScript.
1. I also think we should update the docs to recommend installing CoffeeScript both locally and globally. Locally so that it can be configured and versioned per project, and globally to provide convenient access to the `coffee` command and for running isolated scripts that aren’t part of a larger project. This would be where the docs would mention that `coffee` first looks in the current folder for locally-installed CoffeeScript (any version, not just 2+) before running the globally-installed one.

**Comment by jashkenas** [comment]
Better to depend on `resolve` (it's real simple!) than to depend on `babel-core`, but your point is well taken.

I like the plan you outline in the comment above. With one tweak:

We don't need to recommend installing CoffeeScript both locally and globally. They're good for different things — it depends on what you're doing: 

If you're working on a large project, or a webapp, then a local CoffeeScript install is ideal. It lets you keep your `coffee` isolated, and keeps you on the same page with everyone on your team.

If you're just writing little scripts hither and yon in your harddrive (I do this frequently), then a global CoffeeScript install is ideal. These are just 50-LOC scripts with no dependencies, run directly with `coffee`. It would be silly to save a compiler alongside each of them.

**Comment by GeoffreyBooth** [comment]
If you’re working on a local project, then yes, CoffeeScript should definitely be installed locally; but why not also install it globally? If it’s _only_ installed locally, you won’t have access to the `coffee` command (aside from via `./node_modules/.bin/coffee`). That’s not an issue if you’re using a build chain like Webpack or Gulp, but still, I don’t see the downside of having it installed in both places.

**Comment by connec** [comment]
> you won’t have access to the coffee command (aside from via ./node_modules/.bin/coffee)

npm 5.2+ actually installs an `npx` executable which runs the subsequent command with the local `node_modules/.bin` on the `PATH`:

```sh
npm i coffeescript # install 'locally'
npx coffee         # run the local `coffee`
```

**Comment by GeoffreyBooth** [comment]
That’s actually pretty brilliant. Is NPM 5.2+ popular enough that we should write our docs to assume it (and `npx`) are available?

This article is a pretty good overview, and talks about local vs global: https://medium.com/@maybekatz/introducing-npx-an-npm-package-runner-55f7d4bd282b

**Comment by GeoffreyBooth** [comment]
It occurs to me that the only reason the `coffee` command requires Node 6+ is because we’re not transpiling the files in the `lib` folder. We could do so, or make a separate `lib/transpiled` folder to go alongside `lib/coffeescript`, and for Node < 6 we could `require('lib/transpiled')` instead of `lib/coffeescript`.

It would make development more annoying, as compiling the compiler would take significantly longer, unless we only compiled `lib/transpiled` at release time like we currently do for the browser compiler. But that’s not a reason to deny better compatibility for end users.

**Comment by jashkenas** [comment]
Or, you could even compile CoffeeScript 2's "src -> lib" with the CoffeeScript 1 compiler.

(Just kidding.)

**Comment by connec** [comment]
> Or, you could even compile CoffeeScript 2's "src -> lib"

I admit I did think that myself 😅 

I suppose if we use babel to transpile `lib` we've at least pushed the burden of supporting ES feature off to babel...

**Comment by jashkenas** [comment]
But seriously, I thought that the point of CoffeeScript 2 making a clean break to target modern JS ... was to make the clean break and target modern JS. I think it's fine if you need Node 6+ to run it.

**Comment by GeoffreyBooth** [comment]
The CoffeeScript 2 compiler's output is definitely modern JS. We didn't make Babel a dependency and transpile automatically, all the time, for example. But that doesn't mean the compiler itself needs to be modern JS when it runs. The CS2 browser compiler isn't. I thought about maybe requiring the browser compiler for Node <6, but the browser compiler doesn't have the command-line code included. 

I'm not sure supporting Node <6 is worth the effort. The argument to do so is that Node 4 isn't end of life until 2018. But maybe CS1 is good enough for Node 4 users.
