### ISSUE TITLE
Proposal: Class fields

### ISSUE THREAD

**Issue by stevefan1999** [jashkenas/coffeescript#4720]
Even though it was not in Stage 4, [Class Fields](
https://github.com/tc39/proposal-class-fields), a recently Stage 3-reached proposal, is widely adapted and accepted in the ES world.

[The Babel transform for Class Fields](https://babeljs.io/docs/plugins/transform-class-properties/) shows a 4M+ monthly download counts in [NPM](https://www.npmjs.com/package/babel-plugin-transform-class-properties).

[Embedded JS is broken inside class with Class Fields](http://coffeescript.org/#try:class%20Foo%0A%20%20%60foo%20%3D%20%22bar%22%60%20%23%20notice%20it%20was%20out%20of%20class), so no workaround, except constructor fields definition, is possible.

Maybe we could ditch the strict requirement a little bit?

**Comment by stevefan1999** [comment]
Related: https://github.com/jashkenas/coffeescript/issues/4552

**Comment by GeoffreyBooth** [comment]
Embedded JS actually [isn’t broken](http://coffeescript.org/#try:class%20Foo%0A%20%20%60foo%20%3D%20%22bar%22%60%20%23%20notice%20it%20was%20out%20of%20class), as of 2.0.1 (just published, probably as you were writing your post).

Our policy is to wait for a feature to reach Stage 4 _to output it using final syntax._ Object destructuring hasn’t reached Stage 4, so we output it using the same way that Babel does, using `Object.assign`. Class fields could be supported now, but they would need to be handled similarly, output using only finalized syntax. And then we’d need to go back and update the compiler later when the proposal reaches Stage 4.

Seeing as the backticks are fixed now, is there any strong reason to add support for this now rather than waiting for it to reach Stage 4?

**Comment by stevefan1999** [comment]
@GeoffreyBooth The biggest difference: Stage
It has come afar to reach Stage 3

**Comment by GeoffreyBooth** [comment]
Closing in favor of #4552. [I said the same thing over there.](https://github.com/jashkenas/coffeescript/issues/4552#issuecomment-309254764) If someone wants to implement a PR for this that outputs class fields using Stage 4 syntax, it would be considered; but since the proposal is likely to reach Stage 4 soon, it might not be worth the effort to do so, compared with just waiting for class fields to reach Stage 4.
