### ISSUE TITLE
Tests fail in Windows

### ISSUE THREAD

**Issue by GeoffreyBooth** [jashkenas/coffeescript#4727]
See https://github.com/nodejs/citgm/pull/487 and https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/1003/nodes=win-vs2015/testReport/(root)/citgm/coffeescript_v2_0_1/

3 of the 4 failed tests seem to stem from #3946 @cosmicexplorer.

**Comment by cosmicexplorer** [comment]
I'll look at these asap.

**Comment by GeoffreyBooth** [comment]
Thanks much! It might be we need to add a few more `return if isWindows()` lines at the start of tests that don’t make sense to run in Windows (assuming `--` stuff is irrelevant to Windows).

**Comment by cosmicexplorer** [comment]
It looks possible that line endings are getting mistreated and could be getting transformed into something weird (the octal escape?), spinning up my Windows box now.

**Comment by cosmicexplorer** [comment]
Ok, I'm pretty sure the way windows paths are templated into `assertErrorFormat()` is incorrect because of backslashes and escaping rules. Specifically, in test `"#2849: compilation error in a require()d file"` in `test/error_messages.coffee`, on my windows box, the backslashes simply go away (I think e.g. `C:\Users\...` turns into a `\U`, which evaluates to just a `U`). That may explain why this error is occurring in the linked test, but that would require the backslash sequence to be interpreted differently than I just described, so not sure if that's the whole story. I'll see how far just doubling backslashes in the `require('...')` templates goes.

**Comment by cosmicexplorer** [comment]
Doubling backslashes in the `require '...'` call fixes that error, but there are a few more test failures to get through.

**Comment by cosmicexplorer** [comment]
Ok, I put up a branch with my current changes at <>, which fixes one of the 4 errors. At least the second one (the first of the 3 remaining) is because I can't figure out how to spawn a subprocess from the `coffee` executable -- all of the  `spawnSync` calls fail with an `ENOENT`, or (more fun) `"unknown"`. Will pick this up again over the weekend.

**Comment by GeoffreyBooth** [comment]
You’re welcome to push a branch to https://github.com/GeoffreyBooth/coffeescript, if you’d like to collaborate there. Thanks for taking this on!

**Comment by cosmicexplorer** [comment]
Ok, I had a branch but polluted it before I set `core.autocrlf` so might take a bit to recover (but not long, I'll push asap). I can definitely solve failure 1, but the rest have been annoying.

**Comment by cosmicexplorer** [comment]
Hey, I have a branch up [here](https://github.com/GeoffreyBooth/coffeescript/tree/cosmicexplorer/fix-windows-test-failures) which fixes 1 of the 4 failures. There are some notes on the second, haven't looked at others.

**Comment by GeoffreyBooth** [comment]
It looks like you’ve dived quite deep on the argument parsing . . . before you go any farther, are those tests even applicable in Windows?

**Comment by GeoffreyBooth** [comment]
@cosmicexplorer I pushed some commits on your branch, I got the tests passing in my (virtual) Windows environment. How do they work for you?

**Comment by GeoffreyBooth** [comment]
FYI the secret to getting `spawnSync` working in windows was the `shell: true` option: https://github.com/nodejs/node/issues/3675#issuecomment-308963807

**Comment by cosmicexplorer** [comment]
@GeoffreyBooth thanks for figuring out `spawnSync` -- I don't think the child_process docs are clear on the need for `{shell: true}` at all.

I think the only tests that don't apply to Windows are just the ones checking `#!` parsing. Something like the windows subsystem for linux would be able to use `#!` lines, but I'm pretty sure `process.platform()` returns `'linux'` in that case, so those tests will run whenever they are applicable, I think.
