### ISSUE TITLE
Docker image for coffeescript

### ISSUE THREAD

**Issue by vaibhavsood** [jashkenas/coffeescript#4734]
Hi,

Want to check if there is a docker image/Dockerfile for coffeescript which is officially supported? I could not find one under dockerhub official images https://hub.docker.com/explore/

If not, want to check if there is any plan to add an official coffeescript image to dockerhub? https://docs.docker.com/docker-hub/official_repos/#how-do-i-create-a-new-official-repository

**Comment by GeoffreyBooth** [comment]
What would you expect such an image to include?

**Comment by GeoffreyBooth** [comment]
From the point of view of CoffeeScript as a language, it seems like it should have an official Docker image like Python or Ruby. But really CoffeeScript is a Node module, and I don’t see any other similar Node modules (TypeScript, Babel, Gulp, Webpack) with official Docker images. I think what you really want is the official `node` image.

Look up examples of Node apps that need a build step before execution (like `npm run build`, for example to transpile with Babel) and how those get built in Docker based on the `node` image. CoffeeScript is similar: your build script would be `coffee` instead of `babel`, for example.
