### ISSUE TITLE
Why not supporting static gets and sets?

### ISSUE THREAD

**Issue by noAlvaro** [jashkenas/coffeescript#4748]
This Coffeescript 2 "[breaking change](http://coffeescript.org/#unsupported-get-set)" drew my attention because of two situations:

1. [Object.defineProperty](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty) only work for objects, being impossible to generate some handy **static accessors**.
2. By assuming _"slightly more verbose"_ as best, Coffeescript somewhat deviates from its prior principles.

_- Doesn't it?_

**Comment by GeoffreyBooth** [comment]
No. 1 is wrong: https://github.com/jashkenas/coffeescript/issues/4746

As for No. 2, our aim is to reveal the best of JavaScript, not support every aspect of it. The code example is only for completeness, to demonstrate that it _is_ still possible to create getters and setters, though we discourage them in general as an antipattern.

**Comment by noAlvaro** [comment]
Hey, thanks for correcting. I just found that you put plenty of thought [on this](https://github.com/coffeescript6/discuss/issues/17#issuecomment-299720423) already.

With my assumed limitation to argue against the decision, the only issue I do have when trying to avoid this pattern is when getting advanced visual effects to work with animation libraries (like in [Framer](https://github.com/koenbok/Framer) and others). These libraries usually need to iterate on numeric properties, so getters and setters really come handy when building components... and I couldn't see how to use standard methods instead.

**Comment by GeoffreyBooth** [comment]
Thanks. If you look in the changelog for the 2.0.0 betas, you’ll see we also walled off calling freestanding functions named `get` or `set` so that it’s possible for us to revisit this later, without it being a breaking change. Basically, if there are too many interoperability issues with forcing people to either avoid getters and setters or to use the verbose syntax, we can “enable” the shorthand syntax without breaking any existing CS2 code.
