### ISSUE TITLE
[CS2] support .babel.coffee for auto-transpile

### ISSUE THREAD

**Issue by Fudoshiki** [jashkenas/coffeescript#4749]
We can now transpile coffee file only via CLI --transpile option, but not for module requires

https://github.com/webpack/webpack/issues/5831
https://github.com/js-cli/js-interpret/issues/46

**Comment by GeoffreyBooth** [comment]
Build chains by definition should be able to chain together transpilers. That’s what they’re good at.

CoffeeScript has required transpilation for modules since 1.11, and for generators since 1.9. That’s a few years now. There are surely examples out there of how to pipe the CoffeeScript module’s output through Babel.

The `--transpile` option was meant as a convenience for testing and debugging and using the `coffee` command. It’s not meant to be a miniature build chain inside a proper build chain like that Webpack provides.
