### ISSUE TITLE
CS1 compile output differences since 1.12.6

### ISSUE THREAD

**Issue by Ingramz** [jashkenas/coffeescript#4760]
Hi!

We updated Atom's CoffeeScript dependency from v1.11.1 to v1.12.7 and found some CoffeeScript files from community packages that are now compiled differently, looks like it was something in v1.12.6. Before reaching out to the maintainers of respective packages and asking them to take action, I would like to know if the new compiled output is correct or intentionally changed to be this way.

The output comparisons with source files can be found at https://github.com/atom/atom/pull/13731#issuecomment-339814262

**Comment by vendethiel** [comment]
Looks like the general case is:

```coffee
a -> b ->
.c ->
```

changed from meaning

```js
a(function () {
  b(function () {}).c(function (){});
});
```

to

```js
a(function () {
  b(function () {});
}).c(function (){});
```


looks like this was a byproduct of 1.12.6.

**Comment by GeoffreyBooth** [comment]
The case @ven cites was intentional. Chained calls should follow the first item in the line, not whatever the last function happened to be. The latter behavior was a bug, undocumented, and it's unfortunate that people relied upon it. 

However the fix is easy: just put parentheses around what you want to chain off of, to make it explicit. Like: 

```coffee
a -> (b ->
).c ->
```

Will generate output equivalent to the original intent.

**Comment by Ingramz** [comment]
Thank you for the clarification.
