### ISSUE TITLE
using --transpile and --inline-map together

### ISSUE THREAD

**Issue by Inve1951** [jashkenas/coffeescript#4830]
My project has a .babelrc file without source map options configured because i conditionally build with or without source maps via a Cakefile.

The coffee command doesn't forward the source map config atm. Is there a way I can forward options to babel like there is with --nodejs?

**Comment by GeoffreyBooth** [comment]
No, and I don’t see us adding such functionality. I suggest you use your Cakefile to use different `.babelrc` files as needed, or separate out the compilation and transpilation steps so that you have direct control over how Babel is run. `--transpile` is meant as a convenience; we’re not trying to turn the `coffee` command into a competitor to Webpack or Gulp.

**Comment by Inve1951** [comment]
didn't think of that.
shouldn't it at least forward the option when compiling coffee with source maps?
seeing as it is existing functionality that gets useless when used with --transpile.

**Comment by GeoffreyBooth** [comment]
We can’t forward it, because it just gets overridden by `.babelrc`.

**Comment by Inve1951** [comment]
Just tried it with a dirty patch in coffeescript.js and it does work.
But yea, I split the transform into it's own thing and works too, thx for the suggestion :+1:
