### ISSUE TITLE
[Awaiting Stage 4] Grammar: Dynamic imports

### ISSUE THREAD

**Issue by jtenner** [jashkenas/coffeescript#4834]
```coffeescript
loadStuff = ->
  await Promise.all [ import './assets', import './stuff' ]
```
Yields...
```
[stdin]:2:40: error: unexpected ,
  await Promise.all [ import './assets', import './stuff' ]
                                       ^
```
Not sure how to help with this sort of thing, but I know that dynamic imports are useful.

**Comment by GeoffreyBooth** [comment]
Your syntax is wrong. You can't leave out the parentheses where the comma would be ambiguous. In your case, it's unclear whether the comma separates function arguments (`import` is a function call) or array elements. 

```coffee
Promise.all [ import('./assets'), import('./stuff') ]
```

**Comment by jtenner** [comment]
```coffeescript
(->
  await import('stuff')
)()
```
Tried right in the online editor yields...

```
[stdin]:2:15: error: unexpected (
  await import('stuff')
              ^
```

I promise I tried this already! I wouldn't have filed an issue unless I tried multiple syntaxes before determining this might be a problem.

**Comment by GeoffreyBooth** [comment]
Ah, okay.

**Comment by jtenner** [comment]
I would also like to note, that as someone who has designed programming languages before, taking multiple inputs that produce a single output is quite easy.  But import is a keyword, and trying to discern if it's actually a function call is going to be quite ambiguous!

**Comment by GeoffreyBooth** [comment]
[Dynamic imports are only Stage 3 syntax at the moment](https://github.com/tc39/proposal-dynamic-import), though [Chrome and Safari have started supporting the syntax](https://developers.google.com/web/updates/2017/11/dynamic-import). It is generally our policy to [wait for a syntax to reach Stage 4](http://coffeescript.org/#contributing), to avoid the syntax changing on us after we’ve implemented it, unless someone wants to implement it now with transpilation (like how we currently support object spread).

Unfortunately there doesn’t appear to be a possible transpilation for this. [Babel basically just passes it through](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=ATDGHsDsGcBdgLbgCYFcA2BTAygB06AJYBmhmATsALzADkAdAPSqyHrT0IBW0tA3ACgQhBLnDlYACiRoseAiTLkAlEJDB6sABaZIk6SgyZl1AHzAA3mvWJDWeskzEAhhinLBNkI0bBASYTA6OAA5tB0ABKEwMTk4AjA2pjAji5uwJgAHmISAIS01uoyRg7g2LCoxMSSHgXevgFBoXQAIuCEkMHAcBXEgGQE-TYAvh5AA&debug=false&circleciRepo=&evaluate=false&lineWrap=true&presets=es2015%2Cstage-2&prettier=false&targets=&version=6.26.0), and if the runtime doesn’t support it, too bad. I suppose we could do the same, but the point of having our policy on experimental features is so that we don’t have to put a warning at the top of the docs like “but if you use feature X, make sure your runtime supports it.” We already have that [warning](http://coffeescript.org/#compatibility) for JSX, which will never be standardized, and we warn about the fact that Node still doesn’t support `import`/`export` despite those being standardized; but the more exceptions we make to this the harder it is to use CoffeeScript.

Furthermore, the Chrome announcement has this warning:
> Note: Although `import()` _looks_ like a function call, it is specified as _syntax_ that just happens to use parentheses (similar to `super()`).

This means it’s potentially not as simple as just allowing `import` to be used as a function call, similar to how `require` can be today. We might need to validate that `import` gets only one argument, or that the argument be a variable name and not a string, or who knows what the final syntax will be. This is the danger if implementing it ahead of standardization. Any thoughts @jashkenas or @lydell?

@jtenner I know it’s ugly, but [in the meantime you can use backticks for this](http://coffeescript.org/#try:loadStuff%20%3D%20-%3E%0A%20%20await%20Promise.all%20%5B%0A%20%20%20%20%60import(‘.%2Fassets’)%60%0A%20%20%20%20%60import(‘.%2Fstuff’)%60%0A%20%20%5D):
```coffee
loadStuff = ->
  await Promise.all [
    `import('./assets')`
    `import('./stuff')`
  ]
```

**Comment by lydell** [comment]
I'm glad that the backtick workaround works so well in this case!

Playing around in the [Babel REPL](http://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&code_lz=JYWwDg9gTgLgFASiA&debug=false&circleciRepo=&evaluate=false&lineWrap=true&presets=es2015%2Ces2016%2Ces2017%2Creact%2Cstage-0%2Cstage-1%2Cstage-2%2Cstage-3&prettier=false&targets=&version=6.26.0), it seems like exactly one parameter is required, yes. Ideally we should have as nice error messages as Babel around this ("import() requires exactly one argument").

One thing to discuss is optional parentheses. Does `import "./foo.js"` mean `import "./foo.js"` or `import("./foo.js")`? Since the regular import is only allowed at the top level, perhaps there won't be much of a conflict, though.

```coffee
import "./foo.js" # regular import

if true
  import "./foo.js" # dynamic import

import("./foo.js") # forced top-level dynamic import
```

**Comment by jtenner** [comment]
@GeoffreyBooth What a great explaination of the problem. I had no idea `import()` was actually built into javascript grammar. And that totally makes sense! I can confirm the backtick grammar compiles well too.

I'm very glad I asked this question, and got such a detailed answer. Thank you so much for your time.

**Comment by GeoffreyBooth** [comment]
I think since the workaround is so straightforward, we might as well wait until Stage 4 for this one. But in the meantime we can work out what our syntax would be. Should we just always require parentheses for this, to disambiguate it from normal `import`? I feel like that could confuse a lot of people, though maybe we could help matters by outputting very specific error messages when we see parentheses-less `import` not at the top level.

I think @lydell’s suggested grammar is closer to CoffeeScript’s style, though it has the problem of ambiguity at the top level. No ideal solution here.

**Comment by jtenner** [comment]
@GeoffreyBooth sounds like a pick your poison sort of deal, which stinks. You either have to disambiguate the syntax, or leave it supported with the tick syntax.  Definitely should wait until stage 4, that's for sure.

**Comment by jtenner** [comment]
What's the status on this?

**Comment by Inve1951** [comment]
Still stage 3. https://github.com/tc39/proposal-dynamic-import

**Comment by GeoffreyBooth** [comment]
I'm wondering if we should support this now, even though it's Stage 3, as browsers have already added support for it and therefore it seems unlikely to change? Since it can't be polyfilled. Or am I just asking for trouble?

I guess another option would be adding some kind of flag to enable Stage 3/experimental stuff, and this lives behind that flag until it graduates to Stage 4.

Neither option seems great.

**Comment by laurentpayot** [comment]
+1 for supporting it. My CS web apps are packed with backticks.

**Comment by Inve1951** [comment]
>Neither option seems great.

Agreed. While it's unlikely to change it's not guaranteed it won't.

The current Stage-4 strategy of CS is perfectly reasonable. I don't see a need to make an exception.

A very simple Babel plugin could take care of it in the meanwhile. Would only need some alias the plugin switches for `import`. E.g. `IMPORT(arg)` could transpile to `import(arg)`.

**Comment by GeoffreyBooth** [comment]
Or the policy in general can be: Certain Stage 3 features that are supported in browsers and/or Node are available in CoffeeScript, but if their implementation changes in browsers or Node they will change likewise in CoffeeScript. Consider them experimental, subject to removal or breaking changes, and use at your own risk.

Which seems incredibly sloppy, but that’s essentially the guarantee that browsers themselves are offering their users, and not even behind a flag for many of these Stage 3 features. So I guess if they take that stance, maybe we should?

**Comment by Inve1951** [comment]
That's generally fine but it likely will cause people to still rely on them.
>Consider them experimental, subject to removal or breaking changes, and use at your own risk.

And in turn prevent those people from updating CS to newer versions if there was a breaking change or removal.

@laurentpayot for example intends to use it (in production?). But I guess they got the same issue with the backtick workaround.

**Comment by jashkenas** [comment]
> Or the policy in general can be: Certain Stage 3 features that are supported in browsers and/or Node are available in CoffeeScript, but if their implementation changes in browsers or Node they will change likewise in CoffeeScript. Consider them experimental, subject to removal or breaking changes, and use at your own risk.
> 
> Which seems incredibly sloppy, but that’s essentially the guarantee that browsers themselves are offering their users, and not even behind a flag for many of these Stage 3 features. So I guess if they take that stance, maybe we should?

To be fair — that's just the good old fashioned general JS feature-support process: the pragmatic. Does it work? If the answer is "yes", go ahead and ship it. The web tends not to break over time.

**Comment by laurentpayot** [comment]
@Inve1951 well dynamic imports are a great way to make your page load faster by loading only needed components. An example [here](https://github.com/sveltejs/svelte.technology/blob/master/src/client.js#L21).

**Comment by GeoffreyBooth** [comment]
So to implement this, I think we need two things (probably best implemented as separate PRs):

- An update to the docs revising our Stage 4 policy.
- An addition to the grammar where `import()`, with required parentheses, refers to dynamic import. It can only accept one argument, but that argument need not be a string (at least, according to the Babel REPL).

Thoughts? Volunteers?

**Comment by Inve1951** [comment]
I liked @lydell's approach:
> ```coffee
> import "./foo.js" # regular import
> 
> if true
>   import "./foo.js" # dynamic import
> 
> import("./foo.js") # forced top-level dynamic import
> ```

Wrapping in a `do` block / IIFE could also force a _top level_ dynamic import.
```coffee
do ->
  import "./foo.js"
```

I don't feel like mandatory parenthesis got a place in coffee for this.

**Comment by GeoffreyBooth** [comment]
I think it's too confusing if `import "./foo.js"` means one thing at the top scope and another thing anywhere else.

**Comment by Inve1951** [comment]
It's no more confusing than being forced to use parens for something that looks like a function call in js. `import(foo)` not actually being a function call is an implementation detail of the runtime.

**Comment by jashkenas** [comment]
I haven't been following this thread too closely, but — [looking at the grammar](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import) — it seems to me that we can disambiguate clearly and cleanly:

* Static imports in JS are statements. You cannot, and must not, use them as values, assigning them to a variable, or chaining them as a promise.

* Dynamic imports in JS are expressions. They’re mostly useless unless you `await` them, assign their return promise to a variable, or chain their return promise with `.then()`.

CoffeeScript's rule could simply be that statement-style unused imports are static, and expression-style imports that are part of a larger piece of the grammar are dynamic, like so:

```coffeescript
import "module" # static

if loaded
  import "module" # static, illegal

await import "module" # dynamic

if loaded
  import("module").then -> # dynamic
    ...

libraryPromise = import "module" # dynamic
```

(And I know this disallows bare dynamic imports that depend on asynchronous, un-awaited global variable manipulation — but I think that's a fine limitation to have. You can always assign it to a variable.) But I'm probably missing something?

**Comment by Inve1951** [comment]
Top-level `await` is illegal. But this sounds good overall.

**Comment by GeoffreyBooth** [comment]
> Top-level `await` is illegal.

A proposal to make it possible is working its way through the pipeline. Likewise, there’s a popular Babel plugin that permits `import` statements to _not_ be at top level (even though that breaks spec).

I still think that having the same sequence of characters mean different things in different places in the file is confusing, especially when some people apparently put `import` statements anywhere. I’m all in on the down-with-parentheses bandwagon, but I think requiring them in this case is the safer approach.

**Comment by Inve1951** [comment]
>Babel plugin that permits `import`

I wasn't aware. CS does [not](https://coffeescript.org/v2/#try:await%20Promise.resolve()) allow for it ATM.

**Comment by voxsoftware** [comment]
@GeoffreyBooth you said: Dynamic imports are only Stage 3 syntax at the moment ... unless someone wants to implement it now with transpilation (like how we currently support object spread).

I want that feature, i developed a runtime that can support import function using transpilation. The bad point is that coffeescript throws an error

**Comment by GeoffreyBooth** [comment]
@voxsoftware I'm leaning toward allowing this now, even though it's just Stage 3, because it's already shipped in browsers and Node. I think we should amend our policy that such features will be supported without transpilation but they're subject to breaking changes, just as they are in the runtimes, until they reach Stage 4.

I also think we need to implement it with required parentheses. Not only is that an easier rule for users to follow, it's far easier to implement the grammar for. It also covers is in the case of future conflicts like top-level `await` with `import()`.

Anyone want to tackle this?

**Comment by voxsoftware** [comment]
I can work on this and make a pull request? @GeoffreyBooth

**Comment by GeoffreyBooth** [comment]
> I can work on this and make a pull request? @GeoffreyBooth

Yes please! Please post a link to your branch in case others want to collaborate.

**Comment by sigi** [comment]
It is great that this is being worked on.  "Required parentheses" is the correct approach in my opinion, clear to understand and it will always work if you need it.

For example, it is mandatory for something like `() => import(...)` to work, because that is the common use case with Webpack (and frameworks such as Vue.js that make heavy use of Webpack).

The current "backtick" workaround is acceptable, but I can't wait for this to ship in Coffeescript proper.

**Comment by Inve1951** [comment]
While I was opposed to mandatory parens, given the insight gained in this discussion I'm now in favor.

**Comment by helixbass** [comment]
Opened #5169 to support dynamic `import()` with mandatory parentheses

@voxsoftware I peeked at your fork and didn't see any branches related to this, apologies if this duplicates work you were doing

**Comment by voxsoftware** [comment]
Don't worry, I don't started
