### ISSUE TITLE
Document best practices of making and publishing a node package on NPM

### ISSUE THREAD

**Issue by mitar** [jashkenas/coffeescript#4856]
Reading through existing documentation I am a bit lost on how to make a NPM package in CoffeeScript 2 which would work when loaded as a regular NPM module.

What I had before was:

```
  "scripts": {
    "build": "coffee --map --compile --output ./lib/ ./src/file1.coffee ./src/file2.coffee",
    "prepare": "npm run build"
  },
  "files": [
    "lib/"
  ]
```

And `coffeescript` package among `devDependencies`.

It seems that this allow on install through git, and before publishing, to compile CoffeeScript to JavaScript. But now it seems also transpiling might be necessary because node does not support imports and exports? It looks that maybe just outputting `.mjs` files instead of `.js` files could solve the problem?

**Comment by GeoffreyBooth** [comment]
Let's take a step back. Is there a Node module using regular old CommonJS you can point to? Or if not, I think that should be the first example: a Node module that doesn't require transpilation. Then we should build on that with an example that shows how to deal with `.mjs` files. Technically those shouldn't require transpilation either, now that Node supports them.

**Comment by mitar** [comment]
So the issue is that current LTS does not support `.mjs` without a switch. So I ended up transpiling things anyway.

My final approach is:

```
  "scripts": {
    "build": "coffee --inline-map --transpile --compile --output ./lib/ ./src/file1.coffee ./src/file2.coffee",
    "prepare": "npm run build"
  },
  "devDependencies": {
    "babel-core": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "coffeescript": "^2.0.3"
  },
  "files": [
    "lib/"
  ]
```

And `.babelrc`:

```
{
  "presets": [
    ["env", {
      "targets": {
        "node": "6.12"
      }
    }]
  ]
}
```

This is more or less what is already in documentation, but my worry is/was that I am not sure if it is the best practice. So documenting that would be useful.

> Is there a Node module using regular old CommonJS you can point to?

What do you mean? All NPM packages use regular old CommonJS.

I couldn't really get `.mjs`  to work well in my version of node (v8). So I am not sure we should go that route for now.

**Comment by GeoffreyBooth** [comment]
> What do you mean? All NPM packages use regular old CommonJS.

I mean a Node module written in CoffeeScript that uses CommonJS. I think we want an example of that first, as a baseline we can point to; there must already be some good examples already in GitHub and NPM. Can you recommend one?

After that, the best-practices example would be what [this article](https://medium.com/@giltayar/native-es-modules-in-nodejs-status-and-future-directions-part-i-ee5ea3001f71) calls a “dual-mode package,” one that can be imported via CommonJS; transpiled/Babel imports; or the new Node native module loader. This _still_ should require no transpilation. The article recommends code like `require('./file')` where the extension is unspecified, and therefore can be resolved at import time to `file.js` if the module is being imported as CommonJS or `file.mjs` if the module is being imported as `.mjs`.

This happens to dovetail really nicely to working with `.coffee` files. Imagine a Node app written in CoffeeScript where every `require` statement is importing an extension-less file. So for example you have the root, `index.coffee`, and it has `require './file'` to import `file.coffee`. You can run this in dev mode via `coffee index.coffee`, and `file.coffee` is imported just fine. When it’s time for production, compile it via `npx coffee --compile --bare --no-header .`; this will create `index.js` and `file.js`. Then you can run the JS versions via `node index.js`—the `require` statement still works, and now it’s importing `file.js` instead of `file.coffee`, without you needing to do anything. That’s just how the file extensions work. The same trick can apply to `.mjs`.

**Comment by GeoffreyBooth** [comment]
Actually, let’s migrate this discussion to #4693 if you don’t mind. That issue was first.
