### ISSUE TITLE
Proposal: Output `for…in` as `.forEach`?

### ISSUE THREAD

**Issue by GeoffreyBooth** [jashkenas/coffeescript#4857]
Consider code like this:

```coffee
for x in [1, 2, 3]
  console.log x  # Prints 1, 2, 3
```

This currently outputs as this:
```js
var i, len, ref, x;

ref = [1, 2, 3];
for (i = 0, len = ref.length; i < len; i++) {
  x = ref[i];
  console.log(x); // Prints 1, 2, 3
}
```

Not very readable. Should it output as this?
```js
[1, 2, 3].forEach(function (x) {
  console.log(x); // Prints 1, 2, 3
});
```

And what dangers lurk in making such a change? See also Decaffeinate’s [“Case study: converting array comprehensions”](https://benchling.engineering/from-200k-lines-of-coffeescript-to-zero-making-decaffeinate-super-stable-4de0ca68d9bc#8c03).

If `[1, 2, 3]` where a variable instead of an array literal, we would need to add `Array.from` to ensure that we were iterating over an array with a `forEach` method:

```js
Array.from(arr).forEach(function (x) {
  console.log(x); // Prints 1, 2, 3, assuming arr = [1, 2, 3]
});
```

While we’re at it, could or should we go even more ES-idiomatic and output using `=>`?

**Comment by mauskin** [comment]
The main distinction in my practice always was that `.forEach` nature is to run code over all the elements, the for loop — run code over each element one _after_ another. The order in `.forEach` could be not obvious.

There’s also no way to break from the `.forEach`.

**Comment by lydell** [comment]
In order to not break compatibility massively, we have to continue to support `break` and `continue`. So `.forEach` wouldn’t work, unfortunately. Also, we could only do it when the compiler is sure that the `for` loop goes over an array (not a `NodeList` for example).

**Comment by vendethiel** [comment]
- That would remove `break` and `continue`.
- `Array.from` would reify whole generators, sometimes causing an infinite loop (for an infinite generator).
- That would make it impossible to iterate .more esoteric "array-like" constructs: `NodeList` and `arguments` are two exemple, but more generally, treating anything with a `.length` property as an iterable is very much a feature.
- That would change scoping rules (since all loop variables would now be "closed over").

**Comment by connec** [comment]
Would a less breaking alternative be to try to move to `for ... of`? This would still allow use of `break` and `continue` but would be more idiomatic -

```coffee
for x in [1, 2, 3]
  console.log x

for x in xs
  console.log x
```

```js
var x
for (x of [1,2,3]) {
  console.log(x)
}

var x
for(x of xs) {
  console.log(x)
}
```

**Comment by vendethiel** [comment]
> Regarding the order issue, doesn’t forEach run for each element in the array, in order? I thought that was its distinction from map.

The distinction is that `map` collects value, but `forEach` doesn't.



> I don’t think the scoping rules would be affected, assuming we don’t tell the nodes what we’re doing. In other words, if a user defines a variable inside the loop block, it would still get its var declaration where it does now as if the forEach were just a normal for loop. This should be possible, if potentially messy.

That still changes scoping rules.

```coffee
xs = []
for x in [1,2,3]
  xs.push -> x
xs[0]()

# currently: 3
# with forEach: 1
```

> is this something worth doing?

I don't think so, seeing everything to consider.

**Comment by GeoffreyBooth** [comment]
Alright, well at least this is a good thread to explain why we’re keeping the current behavior of anyone asks :smile

**Comment by jashkenas** [comment]
For the record -- the main reason (apart from all the above) has historically been performance. CoffeeScript compiling down to raw loops that you don't have to write by hand is what allows us to keep native JS performance in hot loops. Otherwise, (at least in the past), we would be orders of magnitude slower for the most critical paths.
