### ISSUE TITLE
Proposal: generalize exempting of tests requiring advanced V8 features

### ISSUE THREAD

**Issue by rdeforest** [jashkenas/coffeescript#4996]
Per discussion on https://github.com/jashkenas/coffeescript/pull/4893, tests which require switches be passed to node/coffee have their special handling hacked into Cakefile.

My proposal (and I'm already working on a PR) is to move special-case test files to their own directories under test/, accompanied by a config.json which contains the particulars of what's special about those tests.

(I figured it made more sense to open this than to continue off-topic discussion on the aforementioned PR.)

**Comment by rdeforest** [comment]
The first problem I'm seeing is that in the current architecture the scanning of test/ happens after re-invocation of bin/cake with (or without) --harmony. I will probably have to make some relatively invasive changes to implement this suggestion.

**Comment by GeoffreyBooth** [comment]
I don’t think you need to worry about whether `--harmony` is invoked or not. Just use feature detection for each set of tests we might test, and if the runtime supports it (whether because it’s a new enough version or because `--harmony` is used) then we run those tests.

I also don’t like the idea of mixing a JSON file into the codebase. I know its function would be primarily to store data, hence it’s good to use a “data” file type, but editing that file would look very different from editing the rest of the codebase. Could we just use a regular `.coffee` file that simply exports an object?

**Comment by rdeforest** [comment]
I think you just cleared up all my confusion and I think I can keep the PR small. I should have something in an hour or so (fingers crossed).

**Comment by GeoffreyBooth** [comment]
Fixed via #5003.
