### ISSUE TITLE
Proposal:  Update CS to JS comparison in docs

### ISSUE THREAD

**Issue by IamEchelon** [jashkenas/coffeescript#5008]
This might not be the place for this but when I was looking over the docs it occurred to me that the examples aren't as clear as they could be because you're showing the compiled JavaScript output. 

Given how JS has evolved and everything is run through some kind of compilation step, the docs don't need to show a one to one translation of CoffeeScript to JavaScript because who cares. You just need a close approximation and the result of said code. For example:

A simple cs function
```
greeting = (name) -> "Hello #{name}!"
```

instead of showing
``` 
var greeting;

greeting = function(name){
  return `Hello ${name}!`
}
```

just show a regular js function even if it's not a 1 to 1 output

```
function greeting(name){
  return `Hello ${name}!`
}
```

This is a trivial example but for more complex code snippets this would makes a non trivial difference. I know that you would lose the some of the interactivity on the docs page but for clarity sake I think that's okay.

**Comment by GeoffreyBooth** [comment]
I’m not sure why we would show JavaScript output that is untrue. That would seem to make understanding what’s going on considerably difficult, to say the least.

I understand that sometimes the generated JavaScript looks like gobbledegook, but that’s part of the point of showing the two side by side: “look at how much cleaner the CoffeeScript is.” Granted, someone writing JavaScript by hand would likely write things differently, e.g. using `.forEach` instead of a `for` loop, and so therefore for most examples there’s probably an idiomatic way to write in JavaScript that is mostly equivalent to the generated JavaScript; but it’s only _mostly_ equivalent, and I wouldn’t want people to start thinking that a CoffeeScript `for` loop compiles into `.forEach` when it doesn’t, for example. There _are_ differences, for example in this case [`for` loops are faster](https://stackoverflow.com/questions/43031988/javascript-efficiency-for-vs-foreach).

I can understand the motivation for wanting to exclude the `var` declaration line, as we elide that often when discussing CoffeeScript in issues and PRs in this repo. But for beginners learning the language—the target audience for the documentation—I think it’s important to include because it concerns variable scope which is a common source of confusion and frustration for beginners.

**Comment by GeoffreyBooth** [comment]
> CoffeeScript would be better served by having examples of how React and Vue look written in CoffeeScript vs the standard JS you would write, not the compilers mangled output.

Agreed, that would be a nice addition to the docs. Please feel free to submit a pull request.

I don’t think Elm and CoffeeScript are directly comparable. Elm is more like JSX than it is like CoffeeScript: the “output” for both Elm and JSX is the rendered HTML, which is what the Elm docs show as the “after” in their side-by-side [examples](http://elm-lang.org/examples/unordered-list). CoffeeScript is really more of an alternate syntax for JavaScript, and is usable wherever JavaScript is usable, including outside of browser contexts (Node, etc.). Because it can be used in all sorts of different ways, whether for Node command-line tools or in browser `script` blocks, there is no “higher level” output that we could show for CoffeeScript similar to Elm or JSX’s rendered HTML; and showing JavaScript output that’s not the actual compiler output feels misleading. The CoffeeScript compiler has more in common with Babel, I think, and their [REPL](https://babeljs.io/repl/).

**Comment by IamEchelon** [comment]
I'll focus on React first. There doesn't seem to be an area for direct comparison of examples how would you like for me to tackle that?

**Comment by GeoffreyBooth** [comment]
Under Resources we have a section called Examples; it should probably go in there or elsewhere in Resources. The tricky thing is if you want to make side-by-side comparisons that don’t follow the format of the others on the page, where the right side is the compiler output. It might be best to create a separate webpage somewhere else, like in a Git repo, that the docs link to. Then it’s more obvious that it’s not a compiler before-and-after, but rather an idiomatic JS/idiomatic CoffeeScript comparison.

**Comment by IamEchelon** [comment]
Okay cool I'll see what I can come with up.
