### ISSUE TITLE
Coffeescript 2.2.4 used in VueJS 2 and Brunch 2.10.12

### ISSUE THREAD

**Issue by abalam666** [jashkenas/coffeescript#5030]
Hello,

I’m not sure if this is the right place to submit this issue. I found a workaround, but i wonder if it is a known behavior and if it has been already fixed.

I’m using coffeescript for every javascript source. I was on coffeescript 1 with client side brunch+vuejs and i wanted to move to coffeescript 2.

I forked those modules to be able to do that.

https://github.com/abalam666/coffeescript-brunch
https://github.com/abalam666/vue-loader
https://github.com/abalam666/vueify

Then … I found a hard-to-explain bug. The “require” was not found at all because of a “weird” complete file. **# Only when coffee files are finished by comments !**

```coffee
require 'vueify/lib/insert-css'
Vue = require 'vue/dist/vue.js'

# Vue principale
app = require 'vue/index'
new Vue
  el: '#app'

# socket.io
#window.IO = io.connect() 
```

is wrongly compiled into ( lack of the require.register closure ) :  

```js
require.register("main.coffee", function(exports, require, module) {
'use strict';

var Vue, Vuex, app, store;

require('vueify/lib/insert-css');

Vue = require('vue/dist/vue.js');

new Vue({
  el: '#app',
  router: require('lib/router'),
  store: store,
  template: '<app/>',
  components: {
    app: app
  }
});
```

If i move the comment then : 

```coffee
require 'vueify/lib/insert-css'
Vue = require 'vue/dist/vue.js'

# socket.io
#window.IO = io.connect() 

# Vue principale
app = require 'vue/index'
new Vue
  el: '#app'

```

is compiled into :  

```js
require.register("main.coffee", function(exports, require, module) {
'use strict';

var Vue, Vuex, app, store;

require('vueify/lib/insert-css');

Vue = require('vue/dist/vue.js');

// socket.io
//window.IO = io.connect() 

new Vue({
  el: '#app',
  router: require('lib/router'),
  store: store,
  template: '<app/>',
  components: {
    app: app
  }
});});

```
Then it works.

Is it normal ?

**Comment by GeoffreyBooth** [comment]
One of the differences between CoffeeScript 1 and 2 is that 2 outputs line comments, e.g. `#` or `//` comments. So if the packages you forked are just throwing `});` at the end of the last line without a line break first, as it appears that they are since your last example ends with `});});`, then the `});` that’s getting added might be appearing at the end of a line that’s commented out.

That’s just one possible explanation. You really need to dig into what each of those other packages are doing to troubleshoot the source of the issue. It’s not the CoffeeScript compiler that’s adding the `require.register` line and its closure, so whatever package is responsible for that appears to have a bug.
