### ISSUE TITLE
Proposal: Motto change

### ISSUE THREAD

**Issue by vikramdurai** [jashkenas/coffeescript#5037]
Currently the CoffeeScript motto, on both the site and the repository, states that CoffeeScript is "Unfancy JavaScript". However, there are ***many*** features that are exclusive to CoffeeScript. So, it would be valid to argue that it is CoffeeScript that is fancy, and not JavaScript. Rather, JavaScript is primitive, and CoffeeScript is a bit more cultured, a bit more warm, an island of peace in an ecosystem of war. Therefore I would like to change CoffeeScript's motto to "Chocolate-enwrapped JavaScript". That also states that CoffeeScript is actually JavaScript at the core.

### Context

I'm trying to change CoffeeScript's motto to reflect how I imagine CoffeeScript to be. If you believe differently, please tell me what *you* think the Motto should be.

**Comment by GeoffreyBooth** [comment]
Since ES2015 and CoffeeScript 2, JavaScript and CoffeeScript are much more alike now than they were in the past. Now that there are very few features that CoffeeScript has that JavaScript lacks, “unfancy JavaScript” is perhaps more apt than ever before. The main appeal of CoffeeScript now, now that JavaScript has adopted most of our innovations, is CoffeeScript’s clean syntax—its _unfanciness._

**Comment by vikramdurai** [comment]
I didn't realize that. Thanks for pointing that out.
One thought, though - it seems that CoffeeScript syntax is most similar to mainstream scripting languages like Python, Ruby and Perl. You *could* also say that CoffeeScript is "pragmatic JavaScript", right?

That's also true since GitHub is using CS for Atom and Atom Plugins, right? Those are also quite massive. Also, I believe that there are companies *still* using CoffeeScript out in the open. That reinforces the "pragmatic" side of CoffeeScript. People also tend to use list comprehensions a lot, and since CoffeeScript supports that and JavaScript doesn't, it is even *more* pragmatic.

I'm just a beginner, and these are the features that I've seen throughout what little experience of CoffeeScript I've had. You are welcome to criticize this as well.

**Comment by GeoffreyBooth** [comment]
While I’m sure it’s possible to come up with a better motto, the one we have has been our motto [since the beginning](http://web.archive.org/web/20091227193141/https://github.com/jashkenas/coffee-script). Changing it now would suggest that there was some change in direction of the project, which I wouldn’t want to imply.
