### ISSUE TITLE
Bug: Block comment at wrong position in compiled JS

### ISSUE THREAD

**Issue by mdarveau** [jashkenas/coffeescript#5038]
Hi,

I am running `mocha` tests with `Istanbul` for code coverage. `Istanbul` require block comments at a specific position to exclude some lines form code coverage reports. My goal is to tell `Istanbul` to ignore one Promise catch block.

When I write 
```coffee
new Promise()
  .catch ### istanbul ignore next ### ( err ) ->
    console.log "Error"
```
It gets compiled to:
```javascript
new Promise().catch/* istanbul ignore next */(err)(function() {
  return console.log("Error");
});
```
I expected it to be:
```javascript
new Promise().catch(err)( /* istanbul ignore next */ function() {
  return console.log("Error");
});
```

I also tried:
```coffee
new Promise()
.catch( ( err ) ### istanbul ignore next ### ->
  console.log "Error"
)
```
Which gives:
```javascript
new Promise().catch(function(err)/* istanbul ignore next */ {
  return console.log("Error");
});
```
Close, but not exactly what I need.

* CoffeeScript version: 2.2.3
* Node.js version: v8.10.0

Is this a bug or expected behaviour?

Thank you!

Manuel

**Comment by GeoffreyBooth** [comment]
CoffeeScript takes a “best effort” approach to placing comments in the generated JavaScript. Code syntax doesn’t always have a one-to-one translation between CoffeeScript and JavaScript, and so the compiler does its best to place the comment as close as possible to where it’s intended to go.

To get technical, comments are “attached” to the nearest _non-discarded token_, either ahead of or behind the comment, and then output before or after that token in the generated output. In your case, parentheses are a discarded token type, so in your first example the comment is attached to `catch` (to follow it) and in your second example it’s attached to `->` (to precede it, which in this case means to precede the `{`). Since there’s no equivalent in CoffeeScript to the generated `function`, there’s no way to more precisely place the comment before or after `function`.

One solution is to give the comment something else to latch onto:

```coffee
new Promise()
  .catch -> ( err ) ->
    ### istanbul ignore next ###
    if true
      console.log "Error"
```
```js
new Promise().catch(function() {
  return function(err) {
    /* istanbul ignore next */
    if (true) {
      return console.log("Error");
    }
  };
});
```

`if` doesn’t get discarded, and it has a clear counterpart in the generated JavaScript. The comment’s placement in relation to it is predictable and unsurprising. `if (true)` is a pointless addition to your code, but [a good minifier will strip it out](https://babeljs.io/repl/#?babili=true&browsers=&build=&builtIns=false&code_lz=HYUw7gBACgTg9gWwJYGcQAoCUA6AxgQwBdcALdAMwFdhdCk5gsIBvAKAghhEMpmAio06DdCBgxMLdhwgB6AFQRUhfMABGlADZKA5sDhcIoAB6EI82dI5JyEdIRiUQktjJlcefCLgYo4mkGxNOB10ACIAUXEDMMwAbisIAF9pJISk-KA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&lineWrap=true&presets=es2015%2Creact%2Cstage-2%2Cbabili&prettier=false&targets=&version=6.26.0&envVersion=).
