### ISSUE TITLE
Coffeescript 2.3 Breaking Change Spread Operator

### ISSUE THREAD

**Issue by ryansolid** [jashkenas/coffeescript#5061]
I appreciate the process we have for verifying stage 4 before we go ahead on include a feature in the language. However, if a feature is already in the language I think we have to be careful before we remove polyfills when there isn't browser support in atleast all the evergreen browsers. 

With the release of 2.3 code broke in Edge and Safari which don't support spread in Object Literals and in React Native whose JS Engine is based on Safari. I realize a lot of people are transpiling so they wouldn't notice it. But I wanted you all to be aware that this happened. 

For now all our code bases will be locked to 2.2. And I'll reiterate in usual cases when it comes to new features I agree with the Stage 4 position, because I think we should get in the way of people using their Javascript. But we can't take anything already in the language for granted.

**Comment by jashkenas** [comment]
Excellent point.

I too would prefer a general policy of "supported everywhere" before compiling to a given feature, rather than any particular stage in the ECMA process...

**Comment by GeoffreyBooth** [comment]
I appreciate the sentiment, but holding off on supporting syntaxes until browsers catch up with them will limit CoffeeScript’s utility for Node and similar environments. I expect that people targeting browsers will be transpiling, or should have great test coverage to ensure that they don’t accidentally use something that not all browsers support, like async iterators.

Take async iterators (a.k.a. async generator functions) as one case. I can’t even find a source to tell me current browser support for that. I don’t see it in MDN or caniuse.com; there isn’t a browsers equivalent of [node.green](http://node.green/) that I’m aware of. But I think it’s safe to say that currently, it’s probably not “supported everywhere.” Yet people are asking us to support this syntax. So we need to choose:
- Say no and do nothing until support is universal across all modern browsers (or all browsers with a certain market share? IE 11?)
- Say yes but output a polyfill, similar to how we supported object spread while it was still Stage 3; and eventually refactor to remove the polyfill
- Say yes and output the syntax as is, and if people use it and they’re targeting environments that might not support it, they should transpile

I think the first option is unacceptable, because it gives people more reasons not to use CoffeeScript; we’ll be lagging modern JavaScript potentially by years. The second option is more work than we have time for, as it means essentially implementing all new features twice: once as a polyfill, and again as the final version. So that leaves us with the final option, which I think is the least bad option. There is real value in outputting modern syntax, in that it makes debugging easier (object spread looks like object spread, not `Object.assign`) and potentially faster.

Or look at it another way: In CoffeeScript 1, you always had to transpile down to ES5 (-ish): that’s what the compiler itself did. CoffeeScript 2 added a _feature,_ in that you could choose whether to output modern JavaScript _or_ enable transpilation to output legacy JavaScript. And you can configure the transpilation! Add a `.babelrc` file that includes only the object spread transform, to transpile that one syntax while leaving everything else untouched. Then you can use CoffeeScript 2.3.0 but still get the same output as 2.2.0. I think that’s more reasonable for us to ask of users in your situation, rather than ask everyone to wait for object spread (or async iterators, or any other new feature) to be supported in all browsers or all browsers above a certain market share, which might mean waiting until IE 11 disappears over the horizon.

**Comment by vendethiel** [comment]
> I appreciate the sentiment, but holding off on supporting syntaxes

I don't think that's the point of this issue. The point of this issue seems to be: if a feature is currently using a polyfill, it shouldn't get replaced with an es6+ feature (at least in CS 2.x), because it will break codebases.
Supporting new features like yield, await, etc., is not an issue, as CoffeeScript emitted no polyfill for these prior to their "native implementation".

**Comment by GeoffreyBooth** [comment]
> The point of this issue seems to be: if a feature is currently using a polyfill, it shouldn’t get replaced with an es6+ feature (at least in CS 2.x), because it will break codebases.

Yeah, sorry, I responded a little too quickly. But to be more precise, removing a polyfill will only break codebases that aren’t transpiling (or aren’t checking the features they’re using against the runtimes they’re targeting). As I wrote above, there are real benefits to removing polyfills, and I wouldn’t want people to need to wait until CS3 (or universal browser support) to get those benefits; especially when the downside for people like @ryansolid is just that they need to update their `.babelrc` file (or transpile with a minimal `.babelrc`). That’s a bit annoying for @ryansolid, for sure, but it seems to me like a fair tradeoff to enable the better output for others.

**Comment by ryansolid** [comment]
I don't think pointing to transpiling is a responsible answer. I think this is completely avoidable as long as we recognize how to handle these cases. There was a mistake made here at one point in the process. Probably polyfilling this in the first place. I think there are only a handful of features that could fall into this ambiguous zone so I doubt this will happen in the future if the general idea is that we don't add ES features til Stage 4 and never polyfill.  However, It was introduced in CS2 as a Coffeescript feature. I didn't need to be aware of the runtime and changing that is significant change. 

So the way I see it, if a feature is worth developing (or calling a polyfill in hindsight) then removing it should be seen as a breaking change.  Really the only danger area is if CS introduces a feature so compelling the ES picks it up in short order.  If that were to happen I think it's worth considering when to  drop the CS implementation (especially if browsers don't support it).

**Comment by GeoffreyBooth** [comment]
> I didn’t need to be aware of the runtime and changing that is significant change.

What gave you this impression? The big change of CoffeeScript 2 is that you _do_ need to be aware of the runtime, that it no longer automatically transpiles down to legacy JavaScript for you the way CoffeeScript 1 did. Or perhaps you meant that for object rest/spread specifically, you didn’t need to be aware of the runtime? But even that’s not really true, at least in my opinion; the polyfill requires `Object.assign`, which [isn’t supported in Internet Explorer 11](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Browser_compatibility), which is still used by [3% of users](https://caniuse.com/usage-table). Maybe you’ve decided to drop support for IE 11 already, but I’ve always been assuming that anyone targeting browsers will be transpiling (or be operating in a controlled environment, like a kiosk where you control the browser installed).

Object rest/spread was implemented in Stage 3 with a polyfill because it was a compatibility issue with other frameworks. JSX required it, and lots of example code for frameworks like Vue use object spread all over the place. There is no other ES6-or-later feature we’ve added before the feature reached Stage 4, and such a feature would need to present similar interoperability issues for us to consider doing so.

You could argue that we could’ve originally implemented object rest/spread output as the final syntax and _not_ polyfilled it, but at the time that would’ve been a gamble that the Stage 3 syntax wouldn’t change between Stages 3 and 4. Any such changes would’ve been breaking changes to the CoffeeScript language itself, which is why we implemented the polyfill; whereas removing the polyfill is arguably a breaking change to the compiler operation (in that you didn’t need to transpile for this before and now you do). It was a least-bad-option decision, and ultimately language backward compatibility was chosen as the top priority.

Again, I’m sorry for the inconvenience, but I believe there’s real value in outputting object rest/spread as the equivalent real syntax, rather than the polyfill. I think the benefit outweighs the inconvenience that users in your specific situation (targeting runtimes that support `Object.assign` but not object rest/spread) need to start transpiling, at least for this particular feature.

**Comment by ryansolid** [comment]
I know we probably shouldn't get too deep into this as I am less worried about this specific scenario. But more that I think it's dangerous to just shrug it off. IE doesn't support ES6 so one could make the decision not to support IE with their CS2 implementation and not transpile as non-starter. Obviously that isn't true of all projects (even the case across mine). It's just that for other reasons (like things that can't be transpiled, like ES6 Proxies etc) IE is a non-starter anyway. When creating a compile to javascript language there is a world where people don't have Babel in their toolchain. CS1 lived in that world. CS2 mostly can live in that world since ES Next features have been opt in. 

Perhaps there was no great path here given the reliance of JSX on spread operator. It's just that if I knew that it was not going to be continually supported by CS I would have not encouraged use of feature. The answer would not be go through all the projects and add Babel to the build chain. As I said realistically given the migration to CS2 some time and only a few projects fall in this category, this only affects a small handful of files. 

It's more that is the default position of CS2 moving forward that in the case of polyfills or implementations (that get considered polyfills in hindsight as ES adopts it), should there be no expectation that how those are implemented are not guarenteed to exist or maintain consistency? You should expect that CS2 to stay relevant needs to stay on the cutting edge of ESNext acceptance and it is likely you will need additional transpiling as at any point the underlying implementation could change to align with the upcoming JS spec.

This is a reasonable expectation, I just want to know if this is the case so I can re-evaluate how I approach trusting Coffeescript in our code bases.

**Comment by GeoffreyBooth** [comment]
Looking at the current [TC39 proposals](https://github.com/tc39/proposals), I don’t see any features we would consider supporting before they reach Stage 4. And all of the proposals for new classes or methods don’t require any work on CoffeeScript’s side at all, like `Array.flatten`; people can just start using those today, if they have the Babel transform enabled and they’re willing to gamble that the final version doesn’t change in a meaningful way.

So that leaves current CoffeeScript innovations that ECMA might someday support. CoffeeScript 2.0.0 was the big catch-up on those, where we adopted ES2015’s `=>` and `class` and destructuring and default values and so on. 2.3.0 added one more, where we dropped the CS1 polyfill for `**` to start outputting ES2018’s `**` instead, which thankfully was equivalent to ours.

There aren’t many proposals in the pipeline that look like current CoffeeScript features, for which we might drop our implementations in favor of native syntax:
- [Class fields](https://github.com/tc39/proposal-class-fields) is one, where our executable class body _could_ be output as a class field if all that’s happening in the body is a variable assignment.
- [Optional `catch` binding](https://github.com/tc39/proposal-optional-catch-binding) is another. We currently allow `try` without `catch`, and in cases where we’re currently outputting an empty `catch` we could output a more minimal one.
- [`do` expressions](https://github.com/tc39/proposal-do-expressions) overlap with our `do` keyword, and perform essentially the same thing: creating an isolated scope that returns a value. In the proposal’s case, the scope is a block scope that seems to implicitly return the last line, similar to our inline-executed function. This proposal is at an early stage, but if the final version happens to be equivalent with our `do`, we might consider using this syntax (but we wouldn’t adopt it if it meant a breaking change as compared with our `do`). It would be a lot of work to start using this syntax, as CoffeeScript currently doesn’t track block scopes, only function scopes.

Those are the only candidates I see on the list; please let me know if you see any others that potentially overlap existing features, as opposed to wholly new things that we would adopt using new syntax. But of the above features, only the first two are Stage 3, and ES2018 just came out; so the soonest either of the first two could be released would be ES2019, early next year. So unless there are any other current polyfills that we already _can_ replace that I’m not aware of, there won’t be any more dropped polyfills this year.

As for compatibility and what you can expect, I’ve been keeping the docs’ [Compatibility](http://coffeescript.org/#compatibility) section updated, though it is Node-focused. Basically, my assumption is that you can get away without transpilation if your target runtime is Node and you’re careful when using very new features, and I listed all the Node 8+ ones in that section. For browsers, there are too many out there and there are too many versions in active use for us to try to give recommendations; my assumption is that you either transpile, or undertake the research yourself to check every one of your supported browsers for compatibility, including on each new CoffeeScript release. That section includes [a link to run the tests in your browser](http://coffeescript.org/test.html), which you could do for every browser you want to try to support; those tests run every CoffeeScript feature natively, with the exception of modules and JSX, which the section notes always require transpilation. If your list of supported browsers is short enough, you could run that page on each supported browser and version to know if any of them lack support for any CoffeeScript features; and you could look at which tests fail to know which features are unsupported in that browser. If you or someone would like to set up a CI integration that uses [Browserstack](https://www.browserstack.com/) or something like it to run this browser test suite across lots of different browsers and versions, I would be happy to link to the output of such a test suite. That would tell people which CoffeeScript features require transpilation for which browsers and versions.

**Comment by ryansolid** [comment]
I think that developers can be responsible for checking their browser support. In my case I did my research, made a decision, and then had the bottom line raised after committing to it, to a point that would have prompted a different decision. 

The spread operator in objects was new, which is largely why I could shrug it off. But from what I'm getting here there is the potential for any minor version upgrade of CS(even if it's more than a year out) to drop polyfill support for features that have been in the language for 6+ years, if Node LTS supports it.

Your list looks right to my knowledge (I was mostly only thinking about the class fields). The potential of the do expression seems even more dangerous but I have to imagine the block scoping considerations alone would prevent this to just slip in. 

I think if the goal here is over the next couple years complete JS parity I can get behind that. Projects will just lock versions until they are ready to take the next step. No need to be concerned with CS3 (unless we are talking block scoping changes perhaps). CS 2.0.0 was enough of a gift to take things to a certain level I think it's reasonable that throughout it's life CS2 introduces changes just as breaking as CS1-CS2 (ie.. syntax changes, a little bit of declaration reordering). Just tell people to transpile or lock version, as the goal of this project is to get from point a to point b. Node LTS is the guide post for polyfill dropping. It's a consistent message which is really all that matters to me.

**Comment by ryansolid** [comment]
I hate to split hairs pointing this out. But it says supported. Not Stage 4. Supported. Probably means different things to different people. I remember reading it thinking awesome, already had to polyfill Object.assign and moved on.  

I really wasn't trying to get on your case about browser compatibility. MDN, and various other sources are pretty good for that.  I think it's just getting all in the same mindset. Changes to that were necessary or Coffeescript 2 would have gotten stuck I'm sure.  Waiting for browsers to catch up practically doomed Coffeescript. IE11 will prove more of a blight than any of its predecessors(which is quite a feat) when you consider Microsoft is committed to supporting it until 2025. So it's existence creates this ambiguity of a what a reasonable baseline is. Removing IE from the equation makes things a lot simpler but isn't practical for most (yet). So screw the browser and use Node LTS.
