### ISSUE TITLE
Unary "+", "-" precedence

### ISSUE THREAD

**Issue by chrapkowski** [jashkenas/coffeescript#5066]
Could someone explain how to interpret operator precedence in the coffee source:

Precedence table extract:
```coffeescript
  ...
  ['right',     '**']
  ['right',     'UNARY_MATH']
  ['left',      'MATH']
  ['left',      '+', '-']
  ['left',      'SHIFT']
  ...
````

Unary `+`, `-` has lower priority than `**` which is (IMO) sort of unexpected and different than in `JS` (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence) but this is consistent with the compiler behaviour (indeed compiler adds parentheses to balance difference between CS and JS) so we can consider this as annoying only.

What is more important here, the table say that unary `+`, `-` has lower priority than any `MATH` where:

```coffeescript
MATH = ['*', '/', '%', '//', '%%']
``` 

Let's see this in practice:
```coffeescript
-3 * 4
```

compiles to
```javascript
-3 * 4
```

when it should be more like:
```javascript
-(3 * 4)
```

This does not change the final value but another example convience me more that this is not intended optimization:

```coffeescript
-+0 / 5
```

compiles to:

```javascript
-(+0) / 5
```

And here it is visible that parentheses are not in the place we should get in case of the precedence table.

And now something which really affects the final result:

```coffeescript
-4 %% 3
```
compiles to:
```javascript
modulo(-4, 3) // 2
```
instead of
 ```javascript
-modulo(4, 3) // -1
```

Above examples suggest that unary `+` and `-` have different priority than binary `+` and `-` but I cannot find any information about it in the precedence table.

Above suggests that unary `+` and `-` have same priority like `UNARY_MATH` but they are not listed there:

```coffeescript
 UNARY_MATH = ['!', '~']
```

which is not so clear because

```coffeescript
!1 ** 3
-1 ** 3
```

becomes:
```javascript
!1 ** 3
-(1 ** 3)
```

In JS `!` has higher priority than `**` so according to the CS table parentheses should be added - especially that this crashes in JS. In the second case parentheses are added and code does not crash in JS. And if both `-` and `!` have lower priority in CS than `**` then this should behave the same way.

**Comment by GeoffreyBooth** [comment]
We just recently (in 2.3.0) converted `**` from compiling into `Math.pow` to compiling into `**`, so the inconsistencies you see regarding `**` might very well be bugs due to that change. #4881 notes JavaScript’s lack of support for `!1 ** 3` (and `~1 ** 3`), but we treated this as a breaking change that was unlikely to affect anyone in practice. But you’re correct, we could add parentheses to make even those cases compile. Do you have a correction you’d recommend, such as putting `**` inside `MATH`?

I think in your examples regarding `-`, we’ve generally been treating the `-` next to a number as a negative sign, as in `-4 ** 3` meaning “negative 4 to the power of 3” (`(-4 ** 3)`) rather than “subtract the result of 4 to the power of 3” (`-(4 ** 3)`). In other words, `-` without a space separating it from a number is treated as a negative sign, rather than with a space treating it as a subtraction operator; but that’s just my assumption, I haven’t looked through the code. If someone has a better understanding of the order of operations, please feel free to correct me.

**Comment by chrapkowski** [comment]
IMO the prefect solution would be to fix operators order to reflect JS (unary operator with higher priority than `**`) and additionally report compile error on:

```coffeescript
-2 ** 2
!2 ** 2
etc.
```

So people could avoid runtime error where it is obvious to occur at compile time.

but this sounds like backward incompatible change and would require to make decision if this is a big deal or not.

In all my samples I used `+` and `-` as unary operators. Current compiler behaviour puts those operators here `UNARY_PLUS_MINUS`:

```coffeescript
  ...
  ['right',     'UNARY_MATH']
  ['right',     '**']
  ['left',      'UNARY_PLUS_MINUS'],
  ['left',      'MATH']
  ['left',      '+', '-']
  ['left',      'SHIFT']
  ...
```

Note that I moved `UNARY_MATH` above `**` because compiler does not add parentheses around them and they have higher priority than `**` in JS. So the table does not reflect compiler behaviour even though the code fails at runtime.

Alternative solution is to keep `UNARY_MATH` where it is now and extend it by unary `+` and `-` adding parentheses around binary `**` for all of them. This would be more `bugfix` than breaking change.

And the most important table of operators precedence should be in the official documentation, not only in the source because there are differences between `CS` and `JS` which should be mentioned and make clear desired behaviour.

**Comment by GeoffreyBooth** [comment]
I’m going to close this for now, as it seems like anything we do here would be a breaking change and therefore would need pretty strong justification (i.e., could clearly be demonstrated to be a bug). If that is the case please give concrete examples and I’ll reopen (or open a new issue).
