### ISSUE TITLE
Proposal: avoid making a `results` array when all branches end with continue

### ISSUE THREAD

**Issue by aleclarson** [jashkenas/coffeescript#5080]
```coffee
export default ->
  while true
    if foo > 0
      someStuff()
      continue
    doStuff()
    continue
```

transpiles to:

```js
// Generated by CoffeeScript 2.3.0
export default function() {
  var results;
  results = [];
  while (true) {
    if (foo > 0) {
      someStuff();
      continue;
    }
    doStuff();
    continue;
  }
  return results;
};
```

I think the `results` array should be removed.

Of course, you can easily put a `return` after the while loop. So this is a minor issue.

**Comment by connec** [comment]
We can't avoid making an array here since the value of the `while` loop is an array - an empty array in the case that all branches `continue` (or the loop otherwise doesn't run, e.g. `'.' while false`).

The only way to avoid it, as you note, would be to make the value of the `while` loop unused with either an explicit return or other subsequent expression.

That said, we _could_ avoid the declaration/assignment of `results` if we detect that no branches use the array and simply `return []` at the end, but I wouldn't expect that to have a noticeable impact on performance, so it would be an aesthetic change only.

**Comment by vendethiel** [comment]
> so it would be an aesthetic change only.

Yes, and I don't expect it to be worth implementing such analysis.
