### ISSUE TITLE
Bug: Switch case put ! before isNaN function

### ISSUE THREAD

**Issue by TrungRueta** [jashkenas/coffeescript#5146]
### Input Code

```coffee
switch
    when isNaN(value) then Number value
    else value
```

### Expected Behavior
```javascript
switch (false) {
  case isNaN(value):
    Number(value);
    break;
  default:
    value;
}
```

### Current Behavior
```javascript
switch (false) {
  case !isNaN(value):
    Number(value);
    break;
  default:
    value;
}
```

### Possible Solution
`when not isNaN a` should render to `case !isNaN(a)`

### Context
When use `isNaN a` alone it render correct to `isNaN(a)`, and same with `not isNaN a` = `!isNaN(a)`. But when use it inside switch it auto assign extra `!` before code.
If we write `when not isNaN a` then code render to `case !!isNaN(a)

### Environment
I write coffee with nodejs v10. tried run js compiled as well as registion coffee to node via cli

* CoffeeScript version: 2.3.2
* Node.js version: 10

**Comment by Inve1951** [comment]
You are misusing the switch statement as far as i can tell.

[Should probably be](https://coffeescript.org/v2/#try:switch%20isNaN%20value%0A%20%20%20%20when%20yes%20then%20Number%20value%0A%20%20%20%20else%20value):
```coffee
switch isNaN value
    when yes then Number value
    else value
```

But actually CoffeeScript does fullfill the expected behaviour with your code:

```js
switch (false) {
  case !isNaN(value):
    Number(value);
    break;
  default:
    value;
}
```
boils down to:
```coffee
if true is !!isNaN value
  Number value
else
  value
```

When omitting the value to test against, it steps into the first block whose condition is [_truthy_](https://developer.mozilla.org/en-US/docs/Glossary/Truthy).

I wasn't even aware of that feature. :smile:

**Comment by Inve1951** [comment]
Just a heads up, @helixbass. This `switch` syntax/feature isn't yet covered in the AST tests.
