### ISSUE TITLE
One argument arrow function without braces

### ISSUE THREAD

**Issue by talentlessguy** [jashkenas/coffeescript#5151]
Hello CoffeeScripts lovers!

I found one missing feature that arrow functions with arguments without braces don't compile properly and throw an error of invalid syntax. I know this isn't a bug.

Example in **ES6+ JavaScript**:
```js
// Ok
func = (x) => x*x

// Ok
func = x => x*x
```
Example in **CoffeeScript**:
```coffee
# ok
func = (x) -> x*x

# error
func = x -> x*x
```
I commonly see/use such functions in regular JS, but I will be glad to see this syntax feature in CoffeeScript also.

Data that may be helpful:
Node.js version: 11.6
CoffeeScript version: 2.3.2

**Comment by vendethiel** [comment]
This already means something different:

```coffeescript
func = x -> x*x
# means
func = x(-> x * x)
```

**Comment by talentlessguy** [comment]
@vendethiel thanks for explanation of the problem.

**Comment by talentlessguy** [comment]
@Inve1951 yeah I know this

**Comment by phil294** [comment]
Since `x => x * x` is valid syntax anyway, I prefer to simply program in this style and run a custom loader over the code which adds the braces.

The specific code snippet (regular expression) can be found [here](https://github.com/phil294/MEVN-base/blob/d10b71f606fab16f53a97d6afc51c19c3df8fe8f/web/build/custom-loaders/coffee-loader.coffee#L3) or below. Hope this helps someone.

```coffee
// ...
return the_code.replace(///
			(?<=					# before: either
				(?::\s)			|	# ": " or
				(?:=\s)			|	# "= " or
				\(			|	# "(" or
				(?:[a-zA-Z_]\s)		|	# "someword " or
				(?:,\s)			|	# ", " or
				(?:(?:-|=)>\s)			# "-> " or "=> "
			)
			(?<!(?:					# before: neither
				export|import|require
			)\ )
			([\w$@]+)				# singleParam
			(?=
				\ 				# space
				(-|=>)				# "->" or "=>"
			)
		///g, '($1)')
```
or, javascript:
```JS
return the_code.replace(/(?<=(?::\s)|(?:=\s)|\(|(?:[a-zA-Z_]\s)|(?:,\s)|(?:(?:-|=)>\s))(?<!(?:export|import|require) )([\w$@]+)(?= (-|=>))/g, '($1)');
```

should cover most cases
