### ISSUE TITLE
Compilation very slow.

### ISSUE THREAD

**Issue by Jorenm** [jashkenas/coffeescript#5290]
This is with node 12.14.1 and coffeescript 2.5.0 on windows

Compiling 12 files with ~300 lines each is taking 10-20 seconds each time.

I recently updated from coffee-script v1.12.7 which took 500ms to compile the same thing.

Any ideas on why it's so much slower?

**Comment by jashkenas** [comment]
😱 That's very concerning.

If you don't mind troubleshooting a little bit — would you try installing 2.4.1, and letting us know how that fares? (There was a large internal change between 2.4.1 and 2.5.0).

Using the `time` command to get precise times for the runs on different versions would also help.

**Comment by Jorenm** [comment]
Ok I ran it using 2.4.1 and it took 579ms

Then just to confirm nothing else changed after my installing the old coffee-script 1.12.7 I upgraded 2.4.1 to 2.5 and it's back to 12s

Happy to help with any additional testing

**Comment by GeoffreyBooth** [comment]
Compilation has definitely been getting slower over time, but not that dramatically:

```
~/Sites/coffeescript ✦ ➦ 27f21a34 ✦ git checkout 1.12.7
HEAD is now at 27f21a34 1.12.7 (#4617)
~/Sites/coffeescript ✦ ➦ 27f21a34 ✦ cake bench
Lex      243 ms (34888 tokens)
Rewrite  120 ms (38979 tokens)
Parse    233 ms
Compile  190 ms (228094 chars)
total    786 ms
~/Sites/coffeescript ✦ ➦ 27f21a34 ✦ git checkout 2.0.0
Previous HEAD position was 27f21a34 1.12.7 (#4617)
HEAD is now at a2a2e769 Update docs output for 2.0.0
~/Sites/coffeescript ✦ ➦ a2a2e769 ✦ cake bench
Lex      353 ms (43672 tokens)
Rewrite  220 ms (48563 tokens)
Parse    379 ms
Compile  423 ms (369919 chars)
total   1375 ms
~/Sites/coffeescript ✦ ➦ a2a2e769 ✦ git checkout 2.4.1
Previous HEAD position was a2a2e769 Update docs output for 2.0.0
HEAD is now at f4fcf657 Don't publish .DS_Store to npm
~/Sites/coffeescript ✦ ➦ f4fcf657 ✦ cake bench
Lex      376 ms (46342 tokens)
Rewrite  407 ms (51817 tokens)
Parse    440 ms
Compile  485 ms (397336 chars)
total   1708 ms
~/Sites/coffeescript ✦ ➦ f4fcf657 ✦ git checkout 2.5.0
Previous HEAD position was f4fcf657 Don't publish .DS_Store to npm
HEAD is now at 61d408f0 2.5.0 (#5284)
~/Sites/coffeescript ✦ ➦ 61d408f0 ✦ cake bench
Lex      559 ms (61030 tokens)
Rewrite  645 ms (67834 tokens)
Parse    687 ms
Compile  717 ms (520292 chars)
total   2608 ms
```

These numbers don’t _quite_ tell the whole story because the CoffeeScript codebase itself has grown a lot between each version; if you look at the Compile step, it grew from 228K characters in 1.12.7 to 520K characters in 2.5.0. So it’s twice as large and took four times as long, which isn’t great, but not the 20 times as long as you’re seeing.

So you see 300ms in 1.12.7 and 500ms in 2.4.1 but 12 seconds in 2.5.0? If you compile each file separately and add up the compilation times, are there any particular files that are worse than others? It could be that certain syntax is especially expensive to compile, and your app might have a lot of it. If you could narrow down what parts of your codebase are slower than others, that might spotlight the issue.

**Comment by Jorenm** [comment]
> So you see 300ms in 1.12.7 and 500ms in 2.4.1

Yeah, but there's variance in compilation times, so I wouldn't swear by those exact numbers.

> If you compile each file separately and add up the compilation times, are there any particular files that are worse than others?

This was actually the first thing I tried before rolling back versions. It was a fairly linear increase in compilation time as I added the files one by one.

**Comment by jashkenas** [comment]
> It could be that certain syntax is especially expensive to compile

Yeah, this sounds like a case of a potential polynomial time algorithm introduced by the AST changes that his files are triggering somehow (and that we could discover by profiling).

Although, 786ms in 1.x to 2,608ms in 2.5 also isn't too wonderful in isolation. I can imagine quite a few folks might be bothered by a ~ 4x compile slowdown.

Apologies for the grumbling, but I just wanted to voice it. Hopefully there’s an obvious optimization somewhere that can help.

**Comment by Jorenm** [comment]
Is there a relatively straightforward command to profile the compilation that you can paste?

**Comment by GeoffreyBooth** [comment]
> Although, 786ms in 1.x to 2,608ms in 2.5 also isn't too wonderful in isolation. I can imagine quite a few folks might be bothered by a ~ 4x compile slowdown.

That’s not an apples-to-apples comparison because it’s not the same codebase being compiled for each benchmark. That’s the 1.12.7 compiler compiling the _1.12.7 codebase,_ and the 2.5.0 compiler compiling the _2.5.0 codebase,_ which is twice as large. For apples to apples you need to have the 2.5.0 compiler compile the 1.12.7 codebase.

One big change between the two is that 2.x keeps track of and outputs line comments, which 1.x did not. If that’s a source of significant slowdown we could add a flag to suppress output of comments, which people probably don’t want most of the time anyway.

Between 2.4.1 and 2.5.0, besides all the AST stuff we also revised the regexes for numbers to support BigInts and numeric separators. The regexes for numbers are much more complicated now, so if the example codebase has lots of numeric literals that might explain the slowdown. The AST changes cause us to keep many more properties about each node that regular compilation doesn’t necessarily use, so if @Jorenm’s code has a lot of a particular node that is much heavier now, that might also explain it.

> Is there a relatively straightforward command to profile the compilation that you can paste?

`cake bench` is what I used in my example above, but that just profiles the CoffeeScript codebase. You can look in CoffeeScript’s `Cakefile` to see how it works and change it to run against your codebase. https://github.com/jashkenas/coffeescript/blob/master/Cakefile#L378-L397

Another thing to try is to compile your project in Docker or in a Linux VM, to see if Windows has anything to do with it. Ditto with other versions of Node.

**Comment by jashkenas** [comment]
> That’s the 1.12.7 compiler compiling the _1.12.7 codebase,_ and the 2.5.0 compiler compiling the _2.5.0 codebase,_ which is twice as large. For apples to apples you need to have the 2.5.0 compiler compile the 1.12.7 codebase.

Ah, true. Sorry for the brainfart.

I'd recommend doing a more thorough profile with Chrome DevTools, using @Jorenm’s problematic codebase (or something similar to it):

https://medium.com/@paul_irish/debugging-node-js-nightlies-with-chrome-devtools-7c4a1b95ae27

Then you can use the JS profiler (with flamechart), to see if there's any low hanging fruit to be optimized away.

**Comment by GeoffreyBooth** [comment]
@Jorenm If you could share your project in a repo, or share a sanitized version of it, that would help. It would be useful to have realistic codebases to test against as we test each new release of CoffeeScript.

And not to sound dismissive, but my intuition is that compile time is a low priority for most users. During development, a user’s entire project is compiled only on startup of `coffee --watch` or whatever the user’s build tool equivalent is; after that, only the file(s) the user saves should be getting recompiled, with the rest cached. The compile time of individual files should be trivial.

We should certainly fix any low-hanging optimizations, but I would be pretty hesitant to increase performance by removing features or adding significant configuration complexity.

**Comment by Jorenm** [comment]
> cake bench is what I used in my example above, but that just profiles the CoffeeScript codebase.

I got the same results as you running this, so this might not be something unique to my system but rather my code base and changes to the coffee compiler.

> @Jorenm If you could share your project in a repo, or share a sanitized version of it, that would help. It would be useful to have realistic codebases to test against as we test each new release of CoffeeScript.

I'll work on getting together a sanitized test case.

> And not to sound dismissive, but my intuition is that compile time is a low priority for most users. During development, a user’s entire project is compiled only on startup of coffee --watch or whatever the user’s build tool equivalent is; after that, only the file(s) the user saves should be getting recompiled, with the rest cached. The compile time of individual files should be trivial.

Maybe I'm not most users, but almost every project I've worked on you compile everything into a bundled "site.min.js" or something equivalent on every change. Maybe on very large code bases this isn't practical, but up until the very most recent version there was no reason not to just compile everything since it took half a second.

>We should certainly fix any low-hanging optimizations, but I would be pretty hesitant to increase performance by removing features or adding significant configuration complexity.

It's pretty clear we're not hunting a marginal decrease in compile time. 500ms -> 12s is a ridiculous jump and should definitely be fixable.

**Comment by jashkenas** [comment]
> And not to sound dismissive, but my intuition is that compile time is a low priority for most users.

I'll have to disagree. Compile times that are slow enough to be noticeable are a huge pain point for anyone that encounters them, grow worse as your project grows in scope and seriousness, and slow down your ability to iterate and test hypotheses.

In the project that I'm currently working on, our JavaScript compile time (just Rollup) takes ten seconds every time you make a change to the front-end, and it's **terrible**.

> It's pretty clear we're not hunting a marginal decrease in compile time. 500ms -> 12s is a ridiculous jump and should definitely be fixable.

Yes, especially because it sounds like we haven't yet taken a profiling and optimization pass over the AST codebase, I think it's very likely there's something relatively simple that can be fixed, without needing to consider removing features.

**Comment by GeoffreyBooth** [comment]
cc @helixbass

**Comment by GeoffreyBooth** [comment]
> Maybe I'm not most users, but almost every project I've worked on you compile everything into a bundled "site.min.js" or something equivalent on every change.

So the CoffeeScript compiler itself, in `--watch` mode, keeps a cache of all files that it’s watching; when a watched file changes, it only recompiles that one file. Most build pipelines should be doing the same thing, even if afterward all the cached files get merged together into a single output file. The compile time is generally trivial compared to the file I/O.

Now maybe many users aren’t doing a setup like this, and there’s no caching happening, which would certainly make compile time much more painful. I just don’t know how common one set of users is compared to the other.

Absolutely if we can improve performance without any sacrifices, there’s no reason not to. All I was saying is that sacrifices need to be carefully weighed. I don’t want to drop AST support in order to get that performance back, for example. Hopefully it won’t come to that.

**Comment by helixbass** [comment]
I have a suspicion of what's causing it - in the rewriter the additional inspection of all comments' location data when determining `INDENT`/`OUTDENT` location data seemed like it could have poor performance characteristics (in its current non-optimized state)

Other than that I can't think of any AST stuff that would cause dramatic performance differences

I'll take a look

**Comment by GeoffreyBooth** [comment]
@Jorenm Can you try deleting all comments from your project and recompiling, and telling us the difference in compile time? There should be some regex find-and-replace that can eliminate all line comments at least.

**Comment by Jorenm** [comment]
Sure. I'll give that a try.

**Comment by Jorenm** [comment]
@GeoffreyBooth I actually narrowed down to one file that was particularly slow. I tried removing all comments, but that had no noticeable effect. I'm going to try removing chunks to see if I can find a problem section.

**Comment by Jorenm** [comment]
@GeoffreyBooth Ok I have a clue perhaps. My slowest file was also my longest. The odd thing was if I deleted the bottom half or the top half (both by character count and by line count) the compile time went from ~8s to ~2s.

I also tried taking a file that was 280 lines and just copy/pasting its contents to get it up to 1400 lines. It went from 460ms to 10s

Something is causing files to get slower as they get larger at a rate far exceeding linear.

**Comment by helixbass** [comment]
@Jorenm it would be helpful to get profiling info about where it's spending most of that ~8s - I don't have much experience with Node profiling but this worked for me:

Install [`0x`](https://www.npmjs.com/package/0x) globally:
```
npm install -g 0x
```
Then generate a flamechart for a compilation of a single file and open in browser:
```
0x -o bin/coffee -b -p src/nodes.coffee
```
(here `bin/coffee` would be the path to your Coffeescript executable and `src/nodes.coffee` would be the path to your biggest/slowest-compiling file)

Can you try that (or something similar) and possibly share the flamechart file(s)?

**Comment by Jorenm** [comment]
@helixbass I'm not sure how to read this, but here's the result.

[8620.0x.zip](https://github.com/jashkenas/coffeescript/files/4101166/8620.0x.zip)

**Comment by helixbass** [comment]
@Jorenm great thanks! FYI I found that clicking "Merge" in the flamechart gives a pretty linear view of time spent

And this does reveal the culprit. And it makes sense that it's popping up on Windows:

For the AST work we needed to make sure that the location data for *all* syntactic constructs in the original source was accurate in the generated AST (otherwise it quickly causes problems with downstream tools like ESLint and Prettier). But there are some challenges there, including the fact that we strip out all carriage returns (`\r`) from the original source at the beginning of the compilation process

In order to account for these stripped carriage returns, I added a data structure to the lexer to keep track of location data "compensations" (places where we need to make adjustments to account for the alterations to the original source)

And the flamechart shows that the thing that blew up is the calculation of location data in the lexer, since for a Windows file with carriage returns at the end of each line it's iterating through that whole large data structure every time it calculates location data for a new token

So we just have to be less naive about how we handle that data structure for keeping track of location data compensations

That's presumably doable in a way that will not incur big performance penalties (otherwise the rough alternative would be to avoid stripping out carriage returns, but that would be a rough refactor, it is nicely simplifying that the lexer/parser can safely assume that linebreaks === `\n`)

I can take a crack at this :+1:

**Comment by Jorenm** [comment]
@helixbass https://media1.giphy.com/media/zXA5VEmXr7OUg/source.gif

**Comment by jashkenas** [comment]
> I can take a crack at this 👍

Woo hoo! 🥳

**Comment by helixbass** [comment]
Opened #5294 to fix

**Comment by GeoffreyBooth** [comment]
@Jorenm Can you please try compiling your project with the latest CoffeeScript from GitHub `master` and letting me know if the compilation time is back to reasonable? As in it should be no more than double what it was in 2.4.1, say.

You can install a particular version of CoffeeScript for your project via:

```shell
# Install version 2.4.1:
npm install coffeescript@2.4.1

# Install latest master:
npm install https://github.com/jashkenas/coffeescript.git

# Run locally installed version:
npx coffee
```

So if you were previously compiling via `coffee --compile` or similar, use `npx coffee --compile` instead. The GitHub-checkout version will still report itself as version 2.5.0, since I won't bump the version until I publish 2.5.1.

If this issue is fixed on `master`, I'll merge in any other bugfixes @helixbass has in the next day or so and then release these fixes in 2.5.1.

**Comment by Jorenm** [comment]
@GeoffreyBooth @helixbass  compiled in 620ms. Thanks!

**Comment by GeoffreyBooth** [comment]
> @GeoffreyBooth @helixbass compiled in 620ms. Thanks!

So 500ms in 1.12.7 and 620ms in current `master`? Excellent!

Do you mind testing the time in 2.4.1?

**Comment by Jorenm** [comment]
@GeoffreyBooth 500-530ms for 2.4.1

**Comment by GeoffreyBooth** [comment]
2.5.1 has been published. @Jorenm please let me know if it resolves your issue.

**Comment by Jorenm** [comment]
@GeoffreyBooth yep. Works great.
