### ISSUE TITLE
Bug: this.condition.invert is not a function

### ISSUE THREAD

**Issue by ivanreese** [jashkenas/coffeescript#5309]
### Input Code

```coffee
a unless b for b in c
```

### Expected Behavior

The input code should successfully compile, and be equivalent to:
```coffee
a if !b for b in c
````

### Current Behavior
The input code causes a TypeError in the compiler, with the message `this.condition.invert is not a function`, originating from [this line, I believe](https://github.com/jashkenas/coffeescript/blob/master/src/nodes.coffee#L5666).

### Context
I'm using this pattern as a super-simple guard in one of my libs, like so:

```coffee
throw new Error "DOOM was called with a null element" unless elm? for elm in elms
```

### Environment
* CoffeeScript version: The error was introduced when #5161 was merged in 99b7826 for [2.5.0](https://github.com/jashkenas/coffeescript/compare/2.4.1...2.5.0). Prior to that, the input code had compiled and performed fine for years.

Thanks!

**Comment by helixbass** [comment]
Ok opened #5310 to fix

@ivanreese thanks for reporting and tracking down where the bug was introduced

But in fact your code would never have behaved as you intended, what you have gets parsed like:
```
throw new Error "DOOM was called with a null element" unless (elm? for elm in elms)
```
And that condition will never be falsy since it returns an array, ie your code transpiles to:
```
var elm;

if (!(function() {
  var i, len, results;
  results = [];
  for (i = 0, len = elms.length; i < len; i++) {
    elm = elms[i];
    results.push(elm != null);
  }
  return results;
})()) {
  throw new Error("DOOM was called with a null element");
}
```
So to get the intended effect you need explicit parenthesization:
```
(throw new Error "DOOM was called with a null element" unless elm?) for elm in elms
```

This is an easy thing to "guess wrong" syntax-wise when unparenthesized, so I opened issues for the ESLint and Prettier plugins to help make it more obvious: https://github.com/helixbass/eslint-plugin-coffee/issues/37, https://github.com/helixbass/prettier-plugin-coffeescript/issues/167

**Comment by ivanreese** [comment]
Holy cow you're right. Serves me right for not testing. Thanks!

**Comment by GeoffreyBooth** [comment]
Thank you for reporting it though!
