### ISSUE TITLE
Deconstructing issue with object { '0': 'aaa', '1': 'bbb' } 

### ISSUE THREAD

**Issue by RakeshKulangara** [jashkenas/coffeescript#5329]
I've the following code which works fine with 1.0, but breaks on 2.0

```
params = { '0': 'aaa', '1': 'bbb' }`
[device, attachment] = params
```

CoffeeScript 1.0

```
var attachment, device, params;

params = {
  '0': 'aaa',
  '1': 'bbb'
};

device = params[0], attachment = params[1];
```

CoffeeScript 2.0

```
var attachment, device, params;

params = {
  '0': 'aaa',
  '1': 'bbb'
};

[device, attachment] = params;
```

When I run the 2.0 version of the code, it results in 

`TypeError: params is not iterable` (running with node v10.17.0)

Is this a known breaking change, what's the best way to handle this?

**Comment by zdenko** [comment]
Your variable `params`  is an object, and your destructuring  assignment is for the arrays.
So, this destructuring should work in case `params` is an array.

```javascript
params = ['aaa', 'bbb']

[device, attachment] = params
```

The following should work if `params` is an object.

```javascript
params = { '0': 'aaa', '1': 'bbb' }

{0:device, 1:atachement} = params
```

**Comment by RakeshKulangara** [comment]
Thanks, I follow what the issue is. We had this code for a while and seems to have worked with CoffeeScript 1.0, but broken when upgraded to CoffeeScript 2.0. So I guess that takeaway is, it was pure luck that it worked with CoffeeScript 1.0 because of how the object has a `0` and `1` as keys?

**Comment by zdenko** [comment]
The difference between versions 1.0 and 2.0 is in the output.
In your case, the transpilled version  of `device = params[0], attachment = params[1]` in version 1.0, worked becuase your keys are `0`and `1`.
Even if you have any other key in your object, it will still work (e.g., there will be no error), but your variable(s) will be `undefined`.

For example

```javascript
params = { '0': 'aaa', '42': 'bbb' }
[device, attachment] = params
```

will be transpiled to 

```javascript
var attachment, device, params;

params = {
  '0': 'aaa',
  '42': 'bbb'
};
device = params[0], attachment = params[1];
```

In this case `device` will be 'aaa',  but the `attachment` will be `undefined`.

The 2.0 version is transpilled to ES6, so `[device, attachment] = params` will fail since `params` is not iterable, i.e., array.

**Comment by GeoffreyBooth** [comment]
> So I guess that takeaway is, it was pure luck that it worked with CoffeeScript 1.0 because of how the object has a `0` and `1` as keys?

Yes 😁
