### ISSUE TITLE
Rollup writes `this` to `undefined` in CoffeeScript 2

### ISSUE THREAD

**Issue by aminya** [jashkenas/coffeescript#5331]
When an operation is performed in the class (like `Tags.forEach` in the following example), CoffeeScript generates a function to call that. However, rollup rewrites `this` to `undefied`. Is this the desired behavior? What is the point of using `this` here?

```coffee
Tags = [1,2]
class MyClass
  constructor: -> console.log("constructor")
  @hey: -> console.log("hey")

  Tags.forEach (t) ->
    @hey()
    console.log(t)
```

[which is compiled to](https://coffeescript.org/#try:Tags%20%3D%20%5B1%2C2%5D%0Aclass%20MyClass%0A%20%20constructor%3A%20-%3E%20console.log(%22constructor%22)%0A%20%20%40hey%3A%20-%3E%20console.log(%22hey%22)%0A%0A%20%20Tags.forEach%20(t)%20-%3E%0A%20%20%20%20%40hey()%0A%20%20%20%20console.log(t)%0A%0A)
```js
var MyClass, Tags;

Tags = [1, 2];

MyClass = (function() {
  class MyClass {
    constructor() {
      console.log("constructor");
    }

    static hey() {
      return console.log("hey");
    }

  };

  Tags.forEach(function(t) {
    this.hey();
    return console.log(t);
  });

  return MyClass;

}).call(this);
```

Then rollup throws this warning:
```ps1
(!) `this` has been rewritten to `undefined`
https://rollupjs.org/guide/en/#error-this-is-undefined
  return MyClass;

 }).call(this);
            ^
```
`this` is replaced with `undefined`

Ref. https://github.com/lautis/rollup-plugin-coffee-script/issues/7

**Comment by GeoffreyBooth** [comment]
In ES modules, `this` at the top level is undefined; whereas in CommonJS or old browser Scripts, `this` was the global context (`global` or `window`). See https://exploringjs.com/es6/ch_modules.html#_browsers-scripts-versus-modules. I would guess that Rollup is erroring because it’s treating this file as ES module code (presumably because you’ve configured Rollup to do so) and Rollup always errors when it sees `this` at the top level in ESM code, as that’s usually a mistake; since top-level `this` is always undefined in ESM code, presumably the author intended to write `globalThis` instead.

Your code has a bug. `Tags.forEach (t) ->` should be `Tags.forEach (t) =>`, because presumably you are trying to reference the `hey` defined on the class; `@hey` within a `->` function is referencing that particular function, which has no `hey` method. [Here’s a corrected version.](https://coffeescript.org/#try:Tags%20%3D%20%5B1%2C2%5D%0Aclass%20MyClass%0A%20%20constructor%3A%20-%3E%20console.log(%22constructor%22)%0A%20%20%40hey%3A%20-%3E%20console.log(%22hey%22)%0A%0A%20%20Tags.forEach%20(t)%20%3D%3E%0A%20%20%20%20%40hey()%0A%20%20%20%20console.log(t)%0A%20%20%20%20%0A%20%20%20%20%0Anew%20MyClass())

Arbitrary logic within the body of a class isn’t supported in JavaScript, and therefore CoffeeScript does some contortions to try to make it work. If I were you I would just avoid it, and move `Tags.forEach` outside of the class definition; or just define the methods statically. You could also [declare your class inside a `do ->` block](https://coffeescript.org/#try:MyClass%20%3D%20undefined%0A%0Ado%20-%3E%0A%20%20Tags%20%3D%20%5B1%2C2%5D%0A%20%20class%20MyClass%0A%20%20%20%20constructor%3A%20-%3E%20console.log(%22constructor%22)%0A%20%20%20%20%40hey%3A%20-%3E%20console.log(%22hey%22)%0A%0A%20%20%20%20Tags.forEach%20(t)%20%3D%3E%0A%20%20%20%20%20%20%40hey()%0A%20%20%20%20%20%20console.log(t)%0A), where `this` would have a value.

Closing as this isn’t really a bug in CoffeeScript.
