### ISSUE TITLE
Syntatic sugar for objects

### ISSUE THREAD

**Issue by fernandortdias** [jashkenas/coffeescript#5340]
Feature request

### Input Code

```coffee
a[b,c,d] = 10
```

### Expected Behavior

a[b][c][d] = 10

### Current Behavior

error

### Possible Solution

a[b][c][d] = 10;

### Environment

* CoffeeScript version: 2.5.1
* Node.js version: N/A

**Comment by GeoffreyBooth** [comment]
Personally it doesn’t feel like a huge win to offer `,` instead of `][` in between object property names. To me the suggested input `a[b,c,d]` looks more like a function call, `a(b,c,d)`, than it does an object reference.

Since there haven’t been any other comments I’m going to close this, but I’ll reopen if others express interest.
