### ISSUE TITLE
Proposal: Allow functions excecuted from the constructor of the parent class to run AFTER the CS binds

### ISSUE THREAD

**Issue by hawkerboy7** [jashkenas/coffeescript#5350]
Thank you for this project!
I use it a lot, but now I can really use some the ES6 features, so I am upgrading to CS2!
In transfering is was unable to find a good solution for the issue described below.

With the update of ES6 in a class `super()` must run before anything else.
For my project this is an issue, I've tried finding anything describing an elegant solutions but was unable to find it. Below a simplified version of some of the code.

```coffeescript
class View

	constructor: ->
		@events = []
		@initialize?.apply this, arguments

	on: (event, fn) ->
		(@events[event] or= []).push fn

	emit: ->
		event = (args = Array.from arguments).shift()
		fn.apply fn, args for fn in @events[event]


class Main extends View

	initialize: ->
		@on "test:event", @run
		@emit "test:event", {a: true}


	run: (b) =>
		console.log "run", b



main = new Main()
```
This code runs fine on CS1 because `super` runs AFTER the binds of coffeescript.
```coffeescript
  function Main() {
    this.run = bind(this.run, this);
    return Main.__super__.constructor.apply(this, arguments);
  }
```

In CS2 however the `super()` must be called before anything else using ES6 classes.
```coffeescript
Main = class Main extends View {
  constructor() {
    super(...arguments);
    this.run = this.run.bind(this);
  }
```
So here the `initialize` triggers before `this.run` is bound resulting in the error: 
`Bound instance method accessed before binding at boundMethodCheck` which makes sense.

# SO...
Is it possible to add something like this:
```coffeescript
class View

	constructor: ->
		@events = []
		
		*afterSuper* # <-- some clever syntax or anything
		@initialize?.apply this, arguments
```
Which would then be compiled into:
```coffeescript
Main = class Main extends View {
  constructor() {
    super(...arguments);
    this.run = this.run.bind(this);
    var ref;
    if ((ref = this.initialize) != null) {
      ref.apply(this, arguments);
    }
  }
```
On every `class` extending `View` ?

-----
I could imagine this is not the best way to define it,
but the idea is to be able to have some code added by coffescript behind the bindings it does for you.
So you can make use of them when creating a new instance.
Preventing the need for 
```coffeescript
main = new Main()
main.initialize()
```
or initializing on ALL the extended children manunally
```coffeescript
class Main extends View

    constructor: ->
        super()
        @initialize.apply this, arguments

    initialize: ->
        ...
```

**Comment by GeoffreyBooth** [comment]
Thanks for reaching out. I’m a bit befuddled by your example `@initialize?.apply this, arguments`—it seems like you have your _parent_ class reaching down to run a method in its children. This feels like an antipattern in classes extending other classes.

Why not simply have the child class’s `initialize` be the child class’s constructor? Or something called by the child class’s constructor. I feel like there should be a solution here that hews closer to best practices and therefore doesn’t require changes to CoffeeScript (or ES6 classes).

[The `super` restriction comes from JavaScript itself](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/super#description):

> When used in a constructor, the `super` keyword appears alone and must be used before the `this` keyword is used. The `super` keyword can also be used to call functions on a parent object.

Because of this, there’s not much we can do. It was a design decision of CoffeeScript 2 to compile the `class` keyword to ES6 classes, and therefore we inherit their limitations. If you must have the CS1 output, you need to refactor your class declaration to be a function instead; look at your CS1 output JavaScript and rewrite that as CoffeeScript.

**Comment by hawkerboy7** [comment]
Hi @GeoffreyBooth, thank you for your time and awnser!
Changing the `initialize` to constrcutor and call `super()` is going to take a long time since multiple projects I have are built this way and use it a lot, but I was unaware this is likely an antipattern so I will change it.
The change to `constructor` and `super()` call on the child does solve the issue.
Thank you!
